SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE FUNCTION [dbo].[ObservesDaylightSavingTime](@State VARCHAR(3), @ZipCode VARCHAR(15))
RETURNS BIT
AS BEGIN
	IF @State IN ('AZ', 'HI') BEGIN
		RETURN 0;
	END;
	RETURN 1;
END


GO
