SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE FUNCTION [dbo].[fnRemoveUnwantedCharsFromNoteComment](@UID BIGINT)
RETURNS VARCHAR(MAX)
AS BEGIN

	DECLARE @VALUE VARCHAR(MAX)
	SELECT @VALUE = CAST([Comment] as VARCHAR(MAX)) 
	FROM [dbo].[Notes] WITH (NOLOCK)
	WHERE [UID] = @UID
	
	SET @VALUE = REPLACE(REPLACE(REPLACE(@VALUE,CHAR(10),' '),CHAR(13),' '),'|',' ')

	RETURN @VALUE
END
GO
