SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE FUNCTION [dbo].[FormatDate](@input DATETIME, @format INTEGER)
RETURNS VARCHAR(50)
AS BEGIN
	IF @input IS NULL OR @input <= '1900-01-01'
		RETURN '';
	IF @format IS NULL BEGIN
		IF DATEPART(HOUR, @input) = 0 AND DATEPART(MINUTE, @input) = 0 AND DATEPART(SECOND, @input) = 0
			RETURN SUBSTRING(CONVERT(VARCHAR(50), @input, 120), 1, 10);
		ELSE
			RETURN CONVERT(VARCHAR(50), @input, 120);
	END;
	RETURN CONVERT(VARCHAR(50), @input, @format);
END


GO
