SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[WorkFlow_StopAccountWorkFlow] @ExecID UNIQUEIDENTIFIER
AS
SET NOCOUNT ON;

DELETE FROM [dbo].[WorkFlow_Execution]
WHERE [ID] = @ExecID;

RETURN 0;
GO
