SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE procedure [dbo].[Lib_Insert_Customer]
(
      @CCustomerID   int output,
      @CUSTOMER   varchar (7),
      @STATUS   varchar (8),
      @SELECTEDFLAG   varchar (1),
      @NAME   varchar (100),
      @STREET1   varchar (30),
      @STREET2   varchar (30),
      @CITY   varchar (20),
      @STATE   varchar (3),
      @ZIPCODE   varchar (10),
      @CONTACT   varchar (30),
      @PHONE   varchar (20),
      @LETTERCODE   varchar (75),
      @PENALTY   money,
      @BADCHECK   money,
      @CTL   varchar (3),
      @FEES   money,
      @COLLECTIONS   money,
      @MTDNUMBERPLACED   float,
      @MTDDOLLARSPLACED   money,
      @YTDNUMBERPLACED   float,
      @YTDDOLLARSPLACED   money,
      @MTDPDCFEES   money,
      @MTDPDCCOLLECTIONS   money,
      @MTDFEES   money,
      @MTDCOLLECTIONS   money,
      @YTDFEES   money,
      @YTDCOLLECTIONS   money,
      @BANKCODE   varchar (100),
      @ATTORNEYCODE   varchar (30),
      @SALESMANCODE   varchar (30),
      @SIFINFO   text,
      @WORKINFO   text,
      @MISCINFO   text,
      @INVOICETYPE   varchar (20),
      @INVOICEFREQ   varchar (20),
      @INVOICESORT   varchar (20),
      @INVOICEMETHOD   varchar (20),
      @OPTIONS   varchar (50),
      @OPTION1   varchar (50),
      @FAX   varchar (15),
      @HALF   money,
      @CLOSE_   money,
      @FAXNUMBER   varchar (30),
      @AUTORECALLSTATUS   varchar (60),
      @AUTORECALLDAYS   int,
      @AUTORECALLFLAG   varchar (1),
      @LOCATE   money,
      @SPECIALCODE   varchar (20),
      @CUSTOMERGROUP   varchar (10),
      @FULL0   money,
      @AMTDUECLIENT   int,
      @FEECODE2   varchar (30),
      @FEEDAYS   int,
      @COB   varchar (50),
      @COMPANY   varchar (40),
      @LASTINVOICEATTEMPT   datetime,
      @REMITMETHOD   varchar (5),
      @ABAROUTINGNUM   varchar (9),
      @BANKACCTNUM   varchar (20),
      @CUSTGROUP   varchar (7),
      @CHECKHOLDDAYS   int,
      @INVSHOWRCVD   bit,
      @INVSHOWBAL   bit,
      @CCOSTPCT   real,
      @CCOSTBUCKET   int,
      @FEESCHEDULE   varchar (5),
      @ISPODCUST   bit,
      @CBRRPTTYPE   varchar (50),
      @CBRMINBAL   money,
      @CBRWAITDAYS   int,
      @USEEQUIFAX   bit,
      @USETRANSUNION   bit,
      @USEEXPERIAN   bit,
      @USEINNOVIS   bit,
      @EMAIL   varchar (100),
      @CBRCLASS   varchar (40),
      @SHOWREVERSEOFDATE   bit,
      @ONLINECHECKFEE   money,
      @ALPHACODE   varchar (50),
      @SWEEP   bit,
      @SWEEPDAYS   int,
      @SWEEPDAYSPAID   int,
      @SWEEPMINBALANCE   money,
      @SWEEPDESK   varchar (10),
      @DEFAULTDESK   varchar (10),
      @FAXID   varchar (50),
      @CBRACCTRTNSENDDEL   bit,
      @CUSTOMDATE1   datetime,
      @CUSTOMDATE2   datetime,
      @CUSTOMDATE3   datetime,
      @CUSTOMDATE4   datetime,
      @CUSTOMDATE5   datetime,
      @CUSTOMDATE6   datetime,
      @CUSTOMDATE7   datetime,
      @CUSTOMDATE8   datetime,
      @CUSTOMDATE9   datetime,
      @CUSTOMOPTION1   bit,
      @CUSTOMOPTION2   bit,
      @CUSTOMOPTION3   bit,
      @CUSTOMOPTION4   bit,
      @CUSTOMOPTION5   bit,
      @CUSTOMOPTION6   bit,
      @CUSTOMOPTION7   bit,
      @CUSTOMOPTION8   bit,
      @CUSTOMOPTION9   bit,
      @CUSTOMVALUE1   int,
      @CUSTOMVALUE2   int,
      @CUSTOMVALUE3   int,
      @CUSTOMVALUE4   int,
      @CUSTOMVALUE5   int,
      @CUSTOMVALUE6   int,
      @CUSTOMVALUE7   int,
      @CUSTOMVALUE8   int,
      @CUSTOMVALUE9   int,
      @LEGALFEESCHEDULE   varchar (5),
      @LETTERDELIVERYMETHOD   int,
      @DATECREATED   datetime,
      @DATEUPDATED   datetime,
      @FEECODE   varchar (30),
      @BLANKETSIF   float,
      @ISPRINCIPLECUST   bit,
      @CUSTOMTEXT1   varchar (500),
      @CUSTOMTEXT2   varchar (500),
      @CUSTOMTEXT3   varchar (500),
      @CUSTOMTEXT4   varchar (500),
      @CUSTOMTEXT5   varchar (500),
      @BANKID   int,
      @DEFAULTINTEREST   real,
      @INVSHOWOTHER   bit,
      @ACKNOWLEDGENEWBIZ   bit,
      @SALESMAN1ID   int,
      @COLLECTORFEESCHEDULE   varchar (5),
		@CBRACCOUNTTYPE varchar(2),
		@CBRORIGINALCREDITOR varchar(30),
		@CBRCREDITORCLASS varchar(2)
)
as
begin


insert into dbo.Customer
(
      CUSTOMER,
      STATUS,
      SELECTEDFLAG,
      NAME,
      STREET1,
      STREET2,
      CITY,
      STATE,
      ZIPCODE,
      CONTACT,
      PHONE,
      LETTERCODE,
      PENALTY,
      BADCHECK,
      CTL,
      FEES,
      COLLECTIONS,
      MTDNUMBERPLACED,
      MTDDOLLARSPLACED,
      YTDNUMBERPLACED,
      YTDDOLLARSPLACED,
      MTDPDCFEES,
      MTDPDCCOLLECTIONS,
      MTDFEES,
      MTDCOLLECTIONS,
      YTDFEES,
      YTDCOLLECTIONS,
      BANKCODE,
      ATTORNEYCODE,
      SALESMANCODE,
      SIFINFO,
      WORKINFO,
      MISCINFO,
      INVOICETYPE,
      INVOICEFREQ,
      INVOICESORT,
      INVOICEMETHOD,
      OPTIONS,
      OPTION1,
      FAX,
      HALF,
      CLOSE_,
      FAXNUMBER,
      AUTORECALLSTATUS,
      AUTORECALLDAYS,
      AUTORECALLFLAG,
      LOCATE,
      SPECIALCODE,
      CUSTOMERGROUP,
      FULL0,
      AMTDUECLIENT,
      FEECODE2,
      FEEDAYS,
      COB,
      COMPANY,
      LASTINVOICEATTEMPT,
      REMITMETHOD,
      ABAROUTINGNUM,
      BANKACCTNUM,
      CUSTGROUP,
      CHECKHOLDDAYS,
      INVSHOWRCVD,
      INVSHOWBAL,
      CCOSTPCT,
      CCOSTBUCKET,
      FEESCHEDULE,
      ISPODCUST,
      CBRRPTTYPE,
      CBRMINBAL,
      CBRWAITDAYS,
      USEEQUIFAX,
      USETRANSUNION,
      USEEXPERIAN,
      USEINNOVIS,
      EMAIL,
      CBRCLASS,
      SHOWREVERSEOFDATE,
      ONLINECHECKFEE,
      ALPHACODE,
      SWEEP,
      SWEEPDAYS,
      SWEEPDAYSPAID,
      SWEEPMINBALANCE,
      SWEEPDESK,
      DEFAULTDESK,
      FAXID,
      CBRACCTRTNSENDDEL,
      CUSTOMDATE1,
      CUSTOMDATE2,
      CUSTOMDATE3,
      CUSTOMDATE4,
      CUSTOMDATE5,
      CUSTOMDATE6,
      CUSTOMDATE7,
      CUSTOMDATE8,
      CUSTOMDATE9,
      CUSTOMOPTION1,
      CUSTOMOPTION2,
      CUSTOMOPTION3,
      CUSTOMOPTION4,
      CUSTOMOPTION5,
      CUSTOMOPTION6,
      CUSTOMOPTION7,
      CUSTOMOPTION8,
      CUSTOMOPTION9,
      CUSTOMVALUE1,
      CUSTOMVALUE2,
      CUSTOMVALUE3,
      CUSTOMVALUE4,
      CUSTOMVALUE5,
      CUSTOMVALUE6,
      CUSTOMVALUE7,
      CUSTOMVALUE8,
      CUSTOMVALUE9,
      LEGALFEESCHEDULE,
      LETTERDELIVERYMETHOD,
      DATECREATED,
      DATEUPDATED,
      FEECODE,
      BLANKETSIF,
      ISPRINCIPLECUST,
      CUSTOMTEXT1,
      CUSTOMTEXT2,
      CUSTOMTEXT3,
      CUSTOMTEXT4,
      CUSTOMTEXT5,
      BANKID,
      DEFAULTINTEREST,
      INVSHOWOTHER,
      ACKNOWLEDGENEWBIZ,
      SALESMAN1ID,
      COLLECTORFEESCHEDULE,
	  CBRACCOUNTTYPE,
	  CBRORIGINALCREDITOR,
	  CBRCREDITORCLASS
)
values
(
      @CUSTOMER,
      @STATUS,
      @SELECTEDFLAG,
      @NAME,
      @STREET1,
      @STREET2,
      @CITY,
      @STATE,
      @ZIPCODE,
      @CONTACT,
      @PHONE,
      @LETTERCODE,
      @PENALTY,
      @BADCHECK,
      @CTL,
      @FEES,
      @COLLECTIONS,
      @MTDNUMBERPLACED,
      @MTDDOLLARSPLACED,
      @YTDNUMBERPLACED,
      @YTDDOLLARSPLACED,
      @MTDPDCFEES,
      @MTDPDCCOLLECTIONS,
      @MTDFEES,
      @MTDCOLLECTIONS,
      @YTDFEES,
      @YTDCOLLECTIONS,
      @BANKCODE,
      @ATTORNEYCODE,
      @SALESMANCODE,
      @SIFINFO,
      @WORKINFO,
      @MISCINFO,
      @INVOICETYPE,
      @INVOICEFREQ,
      @INVOICESORT,
      @INVOICEMETHOD,
      @OPTIONS,
      @OPTION1,
      @FAX,
      @HALF,
      @CLOSE_,
      @FAXNUMBER,
      @AUTORECALLSTATUS,
      @AUTORECALLDAYS,
      @AUTORECALLFLAG,
      @LOCATE,
      @SPECIALCODE,
      @CUSTOMERGROUP,
      @FULL0,
      @AMTDUECLIENT,
      @FEECODE2,
      @FEEDAYS,
      @COB,
      @COMPANY,
      @LASTINVOICEATTEMPT,
      @REMITMETHOD,
      @ABAROUTINGNUM,
      @BANKACCTNUM,
      @CUSTGROUP,
      @CHECKHOLDDAYS,
      @INVSHOWRCVD,
      @INVSHOWBAL,
      @CCOSTPCT,
      @CCOSTBUCKET,
      @FEESCHEDULE,
      @ISPODCUST,
      @CBRRPTTYPE,
      @CBRMINBAL,
      @CBRWAITDAYS,
      @USEEQUIFAX,
      @USETRANSUNION,
      @USEEXPERIAN,
      @USEINNOVIS,
      @EMAIL,
      @CBRCLASS,
      @SHOWREVERSEOFDATE,
      @ONLINECHECKFEE,
      @ALPHACODE,
      @SWEEP,
      @SWEEPDAYS,
      @SWEEPDAYSPAID,
      @SWEEPMINBALANCE,
      @SWEEPDESK,
      @DEFAULTDESK,
      @FAXID,
      @CBRACCTRTNSENDDEL,
      @CUSTOMDATE1,
      @CUSTOMDATE2,
      @CUSTOMDATE3,
      @CUSTOMDATE4,
      @CUSTOMDATE5,
      @CUSTOMDATE6,
      @CUSTOMDATE7,
      @CUSTOMDATE8,
      @CUSTOMDATE9,
      @CUSTOMOPTION1,
      @CUSTOMOPTION2,
      @CUSTOMOPTION3,
      @CUSTOMOPTION4,
      @CUSTOMOPTION5,
      @CUSTOMOPTION6,
      @CUSTOMOPTION7,
      @CUSTOMOPTION8,
      @CUSTOMOPTION9,
      @CUSTOMVALUE1,
      @CUSTOMVALUE2,
      @CUSTOMVALUE3,
      @CUSTOMVALUE4,
      @CUSTOMVALUE5,
      @CUSTOMVALUE6,
      @CUSTOMVALUE7,
      @CUSTOMVALUE8,
      @CUSTOMVALUE9,
      @LEGALFEESCHEDULE,
      @LETTERDELIVERYMETHOD,
      @DATECREATED,
      @DATEUPDATED,
      @FEECODE,
      @BLANKETSIF,
      @ISPRINCIPLECUST,
      @CUSTOMTEXT1,
      @CUSTOMTEXT2,
      @CUSTOMTEXT3,
      @CUSTOMTEXT4,
      @CUSTOMTEXT5,
      @BANKID,
      @DEFAULTINTEREST,
      @INVSHOWOTHER,
      @ACKNOWLEDGENEWBIZ,
      @SALESMAN1ID,
      @COLLECTORFEESCHEDULE,
	  @CBRACCOUNTTYPE,
	  @CBRORIGINALCREDITOR,
	  @CBRCREDITORCLASS
)

select @CCustomerID = Scope_Identity()
end

GO
