SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
create procedure [dbo].[Lib_Update_CareAndHardship]
(
      @CAREANDHARDSHIPID   int,
      @CARETYPECODE   varchar (20),
      @FINANCIALHARDSHIPCODE   varchar (20),
	  @ACCOUNTID   int,
      @DEBTORID   int,
      @CONTACTLETTER   bit,
      @CONTACTTELEPHONE   bit,
      @CONTACTSMS   bit,
      @CONTACTEMAIL   bit,
      @CONTACTFAX   bit,
      @BRAILLE   bit,
      @LARGEPRINT   bit,
      @AUDIOFILES   bit,
      @COMMENT   varchar (8000),
      @STATUS   varchar (255),
      @CONSENT   bit,
      @HOLDDAYSAPPROVED   bit,
      @HOLDEXPIRATIONDATE   datetime,
      @HOLDDAYS   int,
      @CAREPROOFREQUESTED   bit,
      @CAREPROOFRECEIVED   bit,
      @HARDSHIPPROOFREQUESTED   bit,
      @HARDSHIPPROOFRECEIVED   bit,
      @FINANCIALHARDSHIP   varchar (255),
      @CONFIRMED   bit,
      @CLOSEDDATE   datetime,
      @DDANOTE   varchar (8000),
      @PRISONNAME   varchar (100),
      @PRISONNUMBER   varchar (50),
      @PRISONSENTENCEDATE   datetime,
      @PRISONRELEASEDATE   datetime,
      @PRISONINFORMANT   varchar (100),
      @CREATEDWHEN   datetime,
      @CREATEDBY   varchar (255),
      @MODIFIEDWHEN   datetime,
      @MODIFIEDBY   varchar (255)
)
as
begin


update dbo.CareAndHardship set
      [CARETYPECODE] = @CARETYPECODE,
      [FINANCIALHARDSHIPCODE] = @FINANCIALHARDSHIPCODE,
	  [ACCOUNTID] = @ACCOUNTID,
      [DEBTORID] = @DEBTORID,
      [CONTACTLETTER] = @CONTACTLETTER,
      [CONTACTTELEPHONE] = @CONTACTTELEPHONE,
      [CONTACTSMS] = @CONTACTSMS,
      [CONTACTEMAIL] = @CONTACTEMAIL,
      [CONTACTFAX] = @CONTACTFAX,
      [BRAILLE] = @BRAILLE,
      [LARGEPRINT] = @LARGEPRINT,
      [AUDIOFILES] = @AUDIOFILES,
      [COMMENT] = @COMMENT,
      [STATUS] = @STATUS,
      [CONSENT] = @CONSENT,
      [HOLDDAYSAPPROVED] = @HOLDDAYSAPPROVED,
      [HOLDEXPIRATIONDATE] = @HOLDEXPIRATIONDATE,
      [HOLDDAYS] = @HOLDDAYS,
      [CAREPROOFREQUESTED] = @CAREPROOFREQUESTED,
      [CAREPROOFRECEIVED] = @CAREPROOFRECEIVED,
      [HARDSHIPPROOFREQUESTED] = @HARDSHIPPROOFREQUESTED,
      [HARDSHIPPROOFRECEIVED] = @HARDSHIPPROOFRECEIVED,
      [FINANCIALHARDSHIP] = @FINANCIALHARDSHIP,
      [CONFIRMED] = @CONFIRMED,
      [CLOSEDDATE] = @CLOSEDDATE,
      [DDANOTE] = @DDANOTE,
      [PRISONNAME] = @PRISONNAME,
      [PRISONNUMBER] = @PRISONNUMBER,
      [PRISONSENTENCEDATE] = @PRISONSENTENCEDATE,
      [PRISONRELEASEDATE] = @PRISONRELEASEDATE,
      [PRISONINFORMANT] = @PRISONINFORMANT,
      [CREATEDWHEN] = @CREATEDWHEN,
      [CREATEDBY] = @CREATEDBY,
      [MODIFIEDWHEN] = @MODIFIEDWHEN,
      [MODIFIEDBY] = @MODIFIEDBY
where [CAREANDHARDSHIPID] = @CAREANDHARDSHIPID

end
GO
