SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

create procedure [dbo].[CnvInsPayhistory] (@number int=null, @Seq int=null, @batchtype varchar(3)=null, @matched varchar(1)=null, @ctl varchar(3)=null, @customer varchar(7)=null, @sortdata varchar(30)=null, @paytype varchar(30)=null, @paymethod varchar(30)=null, @systemmonth smallint=null, @systemyear smallint=null, @entered datetime=null, @desk varchar(10)=null, @checknbr varchar(10)=null, @invoiced datetime=null, @InvoiceSort varchar(2)=null, @InvoiceType varchar(2)=null, @InvoicePayType real=null, @comment char(30)=null, @datepaid datetime=null, @totalpaid money=null, @paid1 money=null, @paid2 money=null, @paid3 money=null, @paid4 money=null, @paid5 money=null, @paid6 money=null, @paid7 money=null, @paid8 money=null, @paid9 money=null, @paid10 money=null, @fee1 money=null, @fee2 money=null, @fee3 money=null, @fee4 money=null, @fee5 money=null, @fee6 money=null, @fee7 money=null, @fee8 money=null, @fee9 money=null, @fee10 money=null, @balance money=null, @balance1 money=null, @balance3 money=null, @balance4 money=null, @balance5 money=null, @balance6 money=null, @balance7 money=null, @balance8 money=null, @balance9 money=null, @balance10 money=null, @balance2 money=null, @BatchNumber float=null, @Invoice int=null, @InvoiceFlags varchar(10)=null, @OverPaidAmt money=null, @ForwardeeFee money=null, @ReverseOfUID int=null, @AccruedSurcharge money=null, @TransCost money=null, @Tax money=null, @AttorneyID int=null, @CollectorFee money=null, @PAIdentifier varchar(30)=null, @AIMAgencyId int=null, @AIMDueAgency money=null, @AIMAgencyFee money=null, @FeeSched char(5)=null, @CollectorFeeSched char(5)=null, @PaidToDate money=null,    @datetimeentered datetime=null)as begin
INSERT INTO [Collect2000Simm].[dbo].[payhistory]([number], [Seq], [batchtype], [matched], [ctl], [customer], [sortdata], [paytype], [paymethod], [systemmonth], [systemyear], [entered], [desk], [checknbr], [invoiced], [InvoiceSort], [InvoiceType], [InvoicePayType], [comment], [datepaid], [totalpaid], [paid1], [paid2], [paid3], [paid4], [paid5], [paid6], [paid7], [paid8], [paid9], [paid10], [fee1], [fee2], [fee3], [fee4], [fee5], [fee6], [fee7], [fee8], [fee9], [fee10], [balance], [balance1], [balance3], [balance4], [balance5], [balance6], [balance7], [balance8], [balance9], [balance10], [balance2], [BatchNumber],  [Invoice], [InvoiceFlags], [OverPaidAmt], [ForwardeeFee], [ReverseOfUID], [AccruedSurcharge], [TransCost], [Tax], [AttorneyID], [CollectorFee], [PAIdentifier], [AIMAgencyId], [AIMDueAgency], [AIMAgencyFee], [FeeSched], [CollectorFeeSched], [PaidToDate], [datetimeentered])
VALUES(@number, @Seq, @batchtype, @matched, @ctl, @customer, @sortdata, @paytype, @paymethod, @systemmonth, @systemyear, @entered, @desk, @checknbr, @invoiced, @InvoiceSort, @InvoiceType, @InvoicePayType, @comment, @datepaid, @totalpaid, @paid1, @paid2, @paid3, @paid4, @paid5, @paid6, @paid7, @paid8, @paid9, @paid10, @fee1, @fee2, @fee3, @fee4, @fee5, @fee6, @fee7, @fee8, @fee9, @fee10, @balance, @balance1, @balance3, @balance4, @balance5, @balance6, @balance7, @balance8, @balance9, @balance10, @balance2, @BatchNumber, @Invoice, @InvoiceFlags, @OverPaidAmt, @ForwardeeFee, @ReverseOfUID, @AccruedSurcharge, @TransCost, @Tax, @AttorneyID, @CollectorFee, @PAIdentifier, @AIMAgencyId, @AIMDueAgency, @AIMAgencyFee, @FeeSched, @CollectorFeeSched, @PaidToDate,  @datetimeentered)
end

GO
