SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- Changes:  08/05/2020 BGM - Changed query to look in the main inbound table instead of having to import data into a secondary table in order to save time.
-- =============================================
CREATE PROCEDURE [dbo].[Custom_PPNB_Export_Placement_File_V2]
	-- Add the parameters for the stored procedure here
	--EXEC Custom_PPNB_Export_Placement_File
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

--New feeds off main import table Custom_PayPal_NB_Inbound_File		
--Removed intermediate table Custom_PPNB_Import_Active_Accounts 
--added lookup of accounts to use from Custom_PayPal_NB_Inbound_File table instead	
SELECT  CUSTOMER_ACCOUNT_ID, ACCOUNT_CATEGORY , CUSTOMER_LAST_NAME , CUSTOMER_FIRST_NAME , 
		CUSTOMER_BIRTH_DATE , SOCIAL_SECURITY_NUMBER , CHARGED_OFF_FLAG , CHARGED_OFF_DATE , CUSTOMER_CREATE_DATE , CUSTOMER_BALANCE , FEE_AMOUNT,
		CUSTOMER_BALANCE_CHANGE_REASON , CURRENCY_CODE , PLACEABLE_DAYS , ADDRESS_LINE_1 , ADDRESS_LINE_2 , ADDRESS_CITY , 
		ADDRESS_STATE , ADDRESS_POSTAL_CODE , ADDRESS_COUNTRY , CUSTOMER_PHONE_HOME , CUSTOMER_PHONE_WORK , CUSTOMER_EMAIL , 
		BANK_NAME , PENDING_BALANCE , CONFIRMED_BALANCE , ACCOUNT_STATUS_ID, ACCOUNT_LIMITATIONS , ACCOUNT_LIMITATIONS_FLAG , 
		EXEMPTION , EXEMPTION_FLAG , NEG_BAL_EMAIL_FLAG , ACCOUNT_MANAGED_FLAG , PARENT_STUDENT_ACCOUNT_ID , STUDENT_ACCOUNT_FLAG, TAX_ID_NUMBER , LAST_PAYMENT_DATE , 
		LAST_PAYMENT_AMOUNT , LAST_PAYMENT_TYPE , LAST_LOGIN_DATE , AGENCY_NAME , AGENCY_DATE_SENT , AGENCY_DAYS_PLACED , PREVIOUS_AGENCY_NAME , 
		WAREHOUSE_NAME , WAREHOUSE_DATE_SENT, WAREHOUSE_DAYS_PLACED, PREVIOUS_WAREHOUSE_NAME , SEGMENTATION_GROUP_ID , SEGMENTATION_ID , STRATEGY_ID , APPLICATION_STATUS_ID ,
        APPLICATION_STATUS_EXPIRE_DATE , RANDOM_DIGIT_CODE , INTERNAL_ACCOUNT_ID , ACCOUNT_CYCLE_CODE , DAYS_DELINQUENT_COUNT , CYCLES_DELINQUENT_COUNT , CURRENT_MINIMUM_PAYMENT ,
        PAYMENT_ACTIVITY_HISTORY , COLLECTOR_CODE , LAST_WORK_DATE , NEXT_WORK_DATE , SEC_NEG_BAL_EMAIL_DATE , CYCLE_DATE_NEXT ,
        DAYS_TO_CYCLE , CYCLE_MDATE_NEXT , BUCKET_PENDING_AMOUNT , BUCKET_1_AMOUNT , BUCKET_2_AMOUNT , BUCKET_3_AMOUNT ,
        BUCKET_4_AMOUNT , BUCKET_5_AMOUNT , BUCKET_6_AMOUNT , BUCKET_7_AMOUNT , ALT_PHN_1 , ALT_PHN_2 , ALT_PHN_3 , ALT_PHN_4 , ALT_PHN_5 , ALT_PHN_6 , ALT_PHN_7 ,
        ALT_PHN_8 , ALT_PHN_9 , ALT_PHN_10, RISK_SCORE_1 , RISK_SCORE_2, RISK_SCORE_3 , RISK_SCORE_4 , RISK_SCORE_5 , RISK_SCORE_6 , RISK_SCORE_7 , RISK_SCORE_8 , RISK_SCORE_9 ,
        RISK_SCORE_10 , PPIVR , CUSTOMER_LANGUAGE  , ACCOUNT_LINKING_TYPE_ID , LINKING_DAYS  , 
        LINKING_TYPE_FLAG  , NEGATIVE_BALANCE_REASON , BUYER_SELLER  , TIMEZONE , 
        TIMEZONE_DAY_LIGHT_SAVING_FLAG  , DOB , BUSINESS_NAME
        FROM Custom_PayPal_NB_Inbound_File cppnif WITH (NOLOCK)
        Where CUSTOMER_ACCOUNT_ID NOT IN 
				(SELECT account
		FROM master WITH (NOLOCK)
		WHERE (closed IS NULL OR status IN ('pif', 'sif', 'DPV', 'VDS', 'WDS', 'WVI', 'DSP', 'FRD', 'cnd', 'cad', 'lcp', 'MIL', 'OOS', 
									'RFP', 'SSA', 'AEX', 'rsk', 'aty', 'lit', 'fcd', 'dec', 'BKO', 'bky', 'b07', 'b11', 'b13','CMP','PPY'))
		AND (customer IN ('0002337','0002338')))
		AND CUSTOMER_ACCOUNT_ID NOT IN (SELECT ACCT_ID FROM Custom_PayPal_NB_Post_CO_Master cppnpcm WITH (NOLOCK))

    -- Old
	--SELECT  CUSTOMER_ACCOUNT_ID, ACCOUNT_CATEGORY , CUSTOMER_LAST_NAME , CUSTOMER_FIRST_NAME , 
	--	CUSTOMER_BIRTH_DATE , SOCIAL_SECURITY_NUMBER , CHARGED_OFF_FLAG , CHARGED_OFF_DATE , CUSTOMER_CREATE_DATE , CUSTOMER_BALANCE , FEE_AMOUNT,
	--	CUSTOMER_BALANCE_CHANGE_REASON , CURRENCY_CODE , [Placeable days] AS Placeabledays , ADDRESS_LINE1 , ADDRESS_LINE2 , ADDRESS_CITY , 
	--	ADDRESS_STATE , ADDRESS_POSTAL_CODE , ADDRESS_COUNTRY , CUSTOMER_PHONE_HOME , CUSTOMER_PHONE_WORK , CUSTOMER_EMAIL , 
	--	BANK_NAME , PENDING_BALANCE , CONFIRMED_BALANCE , ACCOUNT_STATUS , ACCOUNT_LIMITATIONS , ACCOUNT_LIMITATIONS_FLAG , 
	--	EXEMPTION , EXEMPTION_FLAG , NEG_BAL_EMAIL_FLAG , ACCOUNT_MANAGED_FLAG , PARENT_STUDENT_ACCOUNT_ID , STUDENT_ACCOUNT_FLAG, TAX_ID_NUMBER , LAST_PAYMENT_DATE , 
	--	LAST_PAYMENT_AMOUNT , LAST_PAYMENT_TYPE , LAST_LOGIN_DATE , AGENCY_NAME , AGENCY_DATE_SENT , AGENCY_DAYS_PLACED , PREVIOUS_AGENCY_NAME , 
	--	WAREHOUSE_NAME , WAREHOUSE_DATE_SENT, WAREHOUSE_DAYS_PLACED, PREVIOUS_WAREHOUSE_NAME , SEGMENTATION_GROUP_ID , SEGMENTATION_ID , STRATEGY_ID , APPLICATION_STATUS_ID ,
 --       APPLICATION_STATUS_EXPIRE_DATE , RANDOM_DIGIT_CODE , INTERNAL_ACCOUNT_ID , ACCOUNT_CYCLE_CODE , DAYS_DELINQUENT_COUNT , CYCLES_DELINQUENT_COUNT , CURRENT_MINIMUM_PAYMENT ,
 --       PAYMENT_ACTIVITY_HISTORY , COLLECTOR_CODE , LAST_WORK_DATE , NEXT_WORK_DATE , SEC_NEG_BAL_EMAIL_DATE , CYCLE_DATE_NEXT ,
 --       DAYS_TO_CYCLE , CYCLE_MDATE_NEXT , BUCKET_PENDING_AMOUNT , BUCKET1_AMOUNT , BUCKET2_AMOUNT , BUCKET3_AMOUNT ,
 --       BUCKET4_AMOUNT , BUCKET5_AMOUNT , BUCKET6_AMOUNT , BUCKET7_AMOUNT , ALT_PHN1 , ALT_PHN2 , ALT_PHN3 , ALT_PHN4 , ALT_PHN5 , ALT_PHN6 , ALT_PHN7 ,
 --       ALT_PHN8 , ALT_PHN9 , ALT_PHN10, RISK_SCORE1 , RISK_SCORE2, RISK_SCORE3 , RISK_SCORE4 , RISK_SCORE5 , RISK_SCORE6 , RISK_SCORE7 , RISK_SCORE8 , RISK_SCORE9 ,
 --       RISK_SCORE10 , [PPIVR #] AS PPIVR, [Customer language] AS Customer_language , [Account linking type ID] AS Account_linking_type_ID, [Linking days] AS Linking_days , 
 --       [Linking type flag] AS Linking_type_flag , [Negative Balance Reason] AS Negative_Balance_Reason , [Buyer Seller] AS Buyer_Seller , Timezone , 
 --       [Timezone-Day Light Saving Flag] AS Timezone_Day_Light_Saving_Flag , DOB , BusinessName 
 --       FROM Custom_PPNB_Import_Active_Accounts cpiaa WITH (NOLOCK)
 --       Where CUSTOMER_ACCOUNT_ID NOT IN 
	--			(SELECT account
	--	FROM master WITH (NOLOCK)
	--	WHERE (closed IS NULL OR status IN ('pif', 'sif', 'DPV', 'VDS', 'WDS', 'WVI', 'DSP', 'FRD', 'cnd', 'cad', 'lcp', 'MIL', 'OOS', 
	--								'RFP', 'SSA', 'AEX', 'rsk', 'aty', 'lit', 'fcd', 'dec', 'BKO', 'bky', 'b07', 'b11', 'b13','CMP','PPY'))
	--	AND (customer IN ('0002337','0002338')))

END
GO
