SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
 
CREATE PROCEDURE [dbo].[cbrAuditDataCapture2] (@MAXDOP INT)
  
AS 
    BEGIN

	TRUNCATE TABLE dbo.CbrDataCycleEnd;
	
	--IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[CbrDataCycleEnd]') AND name = N'PK_CbrDataCycleEnd')
	--ALTER TABLE [dbo].[CbrDataCycleEnd] DROP CONSTRAINT [PK_CbrDataCycleEnd]
	--;

	--IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[CbrDataCycleEnd]') AND name = N'ix_CbrDataCycleEnd')
	--DROP INDEX [ix_CbrDataCycleEnd] ON [dbo].[CbrDataCycleEnd] WITH ( ONLINE = OFF )
	--;

	IF OBJECT_ID('tempdb..#TempcbrDatafx') IS NOT NULL
	BEGIN
		DROP TABLE #TempcbrDatafx
	END

	select * into #TempcbrDatafx
	from cbrdatafx2(null);

INSERT INTO dbo.CbrDataCycleEnd WITH (TABLOCKX)
	(	   [FileId]
		  ,[CbrEnabled]
		  ,[CbrPortfolioType]
		  ,[CbrAccountType]
		  ,[CbrMinBalance]
		  ,[CbrWaitDays]
		  ,[CbrCreditorClass]
		  ,[CbrDefaultOriginalCreditor]
		  ,[CbrUseAccountOriginalCreditor]
		  ,[CbrUseCustomerOriginalCreditor]
		  ,[CbrPrincipalOnly]
		  ,[CbrIncludeCodebtors]
		  ,[CbrDeleteReturns]
		  ,[CbrIndustryCode]
		  ,[CbrCustomercode]
		  ,[CbrCustomerid]
		  ,[CbrCustomerName]
		  ,[CbrCustomerCreditorClass]
		  ,[CbrCustomerOriginalCreditor]
		  ,[CbrParmAbbrev]
		  ,[CbrValueLookup]
		  ,[Customer]
		  ,[number]
		  ,[Status]
		  ,[qlevel]
		  ,[receiveddate]
		  ,[DelinquencyDate]
		  ,[OriginalPrincipal]
		  ,[original]
		  ,[CurrentPrincipal]
		  ,[CurrentBalance]
		  ,[lastpaid]
		  ,[OriginalCreditor]
		  ,[ContractDate]
		  ,[ConsumerAccountNumber]
		  ,[SettlementID]
		  ,[soldportfolio]
		  ,[purchasedportfolio]
		  ,[lastpaidamt]
		  ,[CLIDLP]
		  ,[specialnote]
		  ,[cbrPrevent]
		  ,[CbrOverride]
		  ,[cbrextenddays]
		  ,[PrvCbrException]
		  ,[PersonalReceivership_Amortization]
		  ,[StatusCbrReport]
		  ,[StatusCbrDelete]
		  ,[IsBankruptcy]
		  ,[IsDeceased]
		  ,[IsDisputed]
		  ,[StatusIsPIF]
		  ,[StatusIsSIF]
		  ,[StatusIsFraud]
		  ,[McoChargeoffnumber]
		  ,[McoSecondaryAgencyIdenitifier]
		  ,[McoSecondaryAccountNumber]
		  ,[McoMortgageIdentificationNumber]
		  ,[McoTermsDuration]
		  ,[McoClosedDate]
		  ,[McoChargeOffStatus]
		  ,[McoChargeOffAmount]
		  ,[McoPaymentHistoryProfile]
		  ,[McoPaymentHistoryDate]
		  ,[McoHighestCredit]
		  ,[McoCreditLimit]
		  ,[McoSpecialComment]
		  ,[McoComplianceCondition]
		  ,[portfolioid]
		  ,[AimGroupSeller]
		  ,[AimGroupBuyer]
		  ,[PortfolioSoldDate]
		  ,[debtornumber]
		  ,[PrimaryDebtorID]
		  ,[DebtorID]
		  ,[Debtorseq]
		  ,[Debtorname]
		  ,[DebtorResponsible]
		  ,[CbrExclude]
		  ,[PrvDebtorExceptions]
		  ,[IsBusiness]
		  ,[DebtorSSN]
		  ,[DebtorStreet1]
		  ,[DebtorStreet2]
		  ,[DebtorCity]
		  ,[DebtorState]
		  ,[DebtorZipCode]
		  ,[IsAuthorizedAccountUser]
		  ,[bankruptdebtorid]
		  ,[bankruptchapter]
		  ,[bankruptdateFiled]
		  ,[bankruptdateNotice]
		  ,[bankruptproofFiled]
		  ,[bankruptdateTime341]
		  ,[bankruptWithdrawnDate]
		  ,[bankruptdischargeDate]
		  ,[bankruptdismissalDate]
		  ,[bankruptreaffirmDateFiled]
		  ,[cccdebtorid]
		  ,[CCCS]
		  ,[PrimaryDebtorDispute]
		  ,[datedeceased]
		  ,[lastpaidnumber]
		  ,[LastPaymentDate]
		  ,[lastPaymentAmount]
		  ,[payhistorydatepaid]
		  --,[DateCreated]
	 )
	SELECT  
		   FileId
		  ,[CbrEnabled]
		  ,[PortfolioType]
		  ,[AccountType]
		  ,[MinBalance]
		  ,[WaitDays]
		  ,[CreditorClass]
		  ,[DefaultOriginalCreditor]
		  ,[UseAccountOriginalCreditor]
		  ,[UseCustomerOriginalCreditor]
		  ,[PrincipalOnly]
		  ,[IncludeCodebtors]
		  ,[DeleteReturns]
		  ,[IndustryCode]
		  ,[Customercode]
		  ,[Customerid]
		  ,[CustomerName]
		  ,[CustomerCreditorClass]
		  ,[CustomerOriginalCreditor]
		  ,[Abbrev]
		  ,[Lookup]
		  ,[Customer]
		  ,[number]
		  ,[Status]
		  ,[qlevel]
		  ,[receiveddate]
		  ,[DelinquencyDate]
		  ,[OriginalPrincipal]
		  ,[original]
		  ,[CurrentPrincipal]
		  ,[CurrentBalance]
		  ,[lastpaid]
		  ,[OriginalCreditor]
		  ,[ContractDate]
		  ,[ConsumerAccountNumber]
		  ,[SettlementID]
		  ,[soldportfolio]
		  ,[purchasedportfolio]
		  ,[lastpaidamt]
		  ,[CLIDLP]
		  ,[specialnote]
		  ,[cbrPrevent]
		  ,[CbrOverride]
		  ,[extenddays]
		  ,[PrvCbrException]
		  ,[PersonalReceivership_Amortization]
		  ,[StatusCbrReport]
		  ,[StatusCbrDelete]
		  ,[IsBankruptcy]
		  ,[IsDeceased]
		  ,[IsDisputed]
		  ,[StatusIsPIF]
		  ,[StatusIsSIF]
		  ,[StatusIsFraud]
		  ,[Chargeoffnumber]
		  ,[SecondaryAgencyIdenitifier]
		  ,[SecondaryAccountNumber]
		  ,[MortgageIdentificationNumber]
		  ,[TermsDuration]
		  ,[ClosedDate]
		  ,[ChargeOffStatus]
		  ,[ChargeOffAmount]
		  ,[PaymentHistoryProfile]
		  ,[PaymentHistoryDate]
		  ,[HighestCredit]
		  ,[CreditLimit]
		  ,[McoSpecialComment]
		  ,[McoComplianceCondition]
		  ,[portfolioid]
		  ,[AimGroupSeller]
		  ,[AimGroupBuyer]
		  ,[PortfolioSoldDate]
		  ,[debtornumber]
		  ,[PrimaryDebtorID]
		  ,[DebtorID]
		  ,[seq]
		  ,[Debtorname]
		  ,[Responsible]
		  ,[CbrExclude]
		  ,[PrvDebtorExceptions]
		  ,[IsBusiness]
		  ,[DebtorSSN]
		  ,[DebtorStreet1]
		  ,[DebtorStreet2]
		  ,[DebtorCity]
		  ,[DebtorState]
		  ,[DebtorZipCode]
		  ,[IsAuthorizedAccountUser]
		  ,[bankruptdebtorid]
		  ,[chapter]
		  ,[dateFiled]
		  ,[dateNotice]
		  ,[proofFiled]
		  ,[dateTime341]
		  ,[WithdrawnDate]
		  ,[dischargeDate]
		  ,[dismissalDate]
		  ,[reaffirmDateFiled]
		  ,[cccdebtorid]
		  ,[CCCS]
		  ,[PrimaryDebtorDispute]
		  ,[datedeceased]
		  ,[lastpaidnumber]
		  ,[LastPaymentDate]
		  ,[lastPaymentAmount]
		  ,[payhistorydatepaid]
		  --,[DateCreated]
	FROM #TempcbrDatafx;
	
	--ALTER TABLE [dbo].[CbrDataCycleEnd] ADD  CONSTRAINT [PK_CbrDataCycleEnd] PRIMARY KEY NONCLUSTERED 
	--(
	--	[FileId] DESC,
	--	[DebtorID] ASC
	--)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Cbr_Audit_Index]
	--;

	--CREATE NONCLUSTERED INDEX [ix_CbrDataCycleEnd] ON [dbo].[CbrDataCycleEnd] 
	--(
	--	[number] ASC
	--)
	--INCLUDE ( [Customer]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Cbr_Audit_Index]
	--;

	TRUNCATE TABLE cbrCustomGroup;
END


GO
