SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE procedure [dbo].[Lib_Update_Legal_Ledger]
(
      @LEGAL_LEDGERID   int,
      @ACCOUNTID   int,
      @CUSTOMER   varchar (7),
      @ITEMDATE   datetime,
      @DESCRIPTION   varchar (50),
      @DEBITAMT   money,
      @CREDITAMT   money,
      @PAYHISTORYID   int,
      @INVOICEABLE   bit,
      @INVOICE   int,
      @LEGALLEDGERTYPEID int,
	  @APPROVEDBY varchar(50),
	  @ACCOUNTINGLEDGERID varchar(50),
	  @APPROVEDAMOUNT money,
	  @APPROVEDON datetime,
	  @CREATED datetime,
	  @AIMINVOICEID varchar(50),
	  @AIMUNIQUEID varchar(50),
	  @AIMID int,
	  @EXPORTEDFORAPPROVALON datetime
)
as
begin


update dbo.Legal_Ledger set
      ACCOUNTID = @ACCOUNTID,
      CUSTOMER = @CUSTOMER,
      ITEMDATE = @ITEMDATE,
      DESCRIPTION = @DESCRIPTION,
      DEBITAMT = @DEBITAMT,
      CREDITAMT = @CREDITAMT,
      PAYHISTORYID = @PAYHISTORYID,
      INVOICEABLE = @INVOICEABLE,
      INVOICE = @INVOICE,
      LEGALLEDGERTYPEID = @LEGALLEDGERTYPEID, 
	  APPROVEDBY = @APPROVEDBY,
	  ACCOUNTINGLEDGERID = @ACCOUNTINGLEDGERID,
	  APPROVEDAMOUNT = @APPROVEDAMOUNT,
	  APPROVEDON = @APPROVEDON,
	  AIMINVOICEID = @AIMINVOICEID, 
	  AIMUNIQUEID = @AIMUNIQUEID,
	  AIMID = @AIMID ,
	  EXPORTEDFORAPPROVALON = @EXPORTEDFORAPPROVALON
where LEGAL_LEDGERID = @LEGAL_LEDGERID

end

GO
