SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO



/*dbo.sp_LetterRequest_Add*/
CREATE   Procedure [dbo].[sp_LetterRequest_Add]
@LetterRequestID int OUTPUT,
@AccountID int,
@CustomerCode varchar(7),
@LetterID int,
@LetterCode varchar(5),
@SubjDebtorID int,
@DateRequested Datetime,
@DateProcessed Datetime,
@JobName varchar(256),
@DueDate Datetime,
@AmountDue money,
@UserName varchar(10),
@SenderID int,
@RequesterID int,
@Suspend bit,
@SifPmt1 varchar(30),
@SifPmt2 varchar(30),
@SifPmt3 varchar(30),
@SifPmt4 varchar(30),
@SifPmt5 varchar(30),
@SifPmt6 varchar(30),
@SifPmt7 varchar(30) = '',
@SifPmt8 varchar(30) = '',
@SifPmt9 varchar(30) = '',
@SifPmt10 varchar(30) = '',
@SifPmt11 varchar(30) = '',
@SifPmt12 varchar(30) = '',
@SifPmt13 varchar(30) = '',
@SifPmt14 varchar(30) = '',
@SifPmt15 varchar(30) = '',
@SifPmt16 varchar(30) = '',
@SifPmt17 varchar(30) = '',
@SifPmt18 varchar(30) = '',
@SifPmt19 varchar(30) = '',
@SifPmt20 varchar(30) = '',
@SifPmt21 varchar(30) = '',
@SifPmt22 varchar(30) = '',
@SifPmt23 varchar(30) = '',
@SifPmt24 varchar(30) = '',
@Manual bit,
@AddEditMode bit,
@Edited bit,
@DocumentData image,
@Deleted bit,
@CopyCustomer bit,
@SaveImage bit,
@ProcessingMethod int,
@ErrorDescription varchar(200)
AS

INSERT INTO LetterRequest
(
AccountID,
CustomerCode,
LetterID,
LetterCode,
SubjDebtorID,
DateRequested,
DateProcessed,
JobName,
DueDate,
AmountDue,
UserName,
SenderID,
RequesterID,
Suspend,
SifPmt1,
SifPmt2,
SifPmt3,
SifPmt4,
SifPmt5,
SifPmt6,
SifPmt7,
SifPmt8,
SifPmt9,
SifPmt10,
SifPmt11,
SifPmt12,
SifPmt13,
SifPmt14,
SifPmt15,
SifPmt16,
SifPmt17,
SifPmt18,
SifPmt19,
SifPmt20,
SifPmt21,
SifPmt22,
SifPmt23,
SifPmt24,
Manual,
AddEditMode,
Edited,
DocumentData,
Deleted,
CopyCustomer,
SaveImage,
ProcessingMethod,
ErrorDescription
)
VALUES
(
@AccountID,
@CustomerCode,
@LetterID,
@LetterCode,
@SubjDebtorID,
@DateRequested,
@DateProcessed,
@JobName,
@DueDate,
@AmountDue,
@UserName,
@SenderID,
@RequesterID,
@Suspend,
@SifPmt1,
@SifPmt2,
@SifPmt3,
@SifPmt4,
@SifPmt5,
@SifPmt6,
@SifPmt7,
@SifPmt8,
@SifPmt9,
@SifPmt10,
@SifPmt11,
@SifPmt12,
@SifPmt13,
@SifPmt14,
@SifPmt15,
@SifPmt16,
@SifPmt17,
@SifPmt18,
@SifPmt19,
@SifPmt20,
@SifPmt21,
@SifPmt22,
@SifPmt23,
@SifPmt24,
@Manual,
@AddEditMode,
@Edited,
@DocumentData,
@Deleted,
@CopyCustomer,
@SaveImage,
@ProcessingMethod,
@ErrorDescription
)

SET @LetterRequestID = SCOPE_IDENTITY()



GO
