SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE  PROCEDURE [dbo].[ins_Custom_DiscoverRMSMTNotes]
@number    int,
@Data       VARCHAR(1000),
@User       VARCHAR(10)
AS

SET NOCOUNT ON


DECLARE @Comment   VARCHAR(100)


IF ((UPPER(SUBSTRING(@Data, 35,1)) = 'C') AND 
    (ISNUMERIC(SUBSTRING(@Data, 36,2)) = 1))
     BEGIN
          SET @Comment = 'Comaker ' + UPPER(SUBSTRING(@Data, 36,2))
          SET @Comment = @Comment + (Select CASE UPPER(SUBSTRING(@Data, 38,3))
                                            WHEN 'AD1' THEN ' Address Line 1('+ UPPER(SUBSTRING(@Data, 35, 6)) + '): '  + SUBSTRING(@DATA, 41, 40)
	                                    WHEN 'AD2' THEN ' Address Line 2('+ UPPER(SUBSTRING(@Data, 35, 6)) + '): '  + SUBSTRING(@DATA, 41, 40)
	                                    WHEN 'BDY' THEN ' Birthday('+ UPPER(SUBSTRING(@Data, 35, 6)) + '): '  + SUBSTRING(@DATA, 41, 40)
	                                    WHEN 'CNM' THEN ' CORP. Comaker Name('+ UPPER(SUBSTRING(@Data, 35, 6)) + '): '  + SUBSTRING(@DATA, 41, 40)
	                                    WHEN 'CNT' THEN ' County('+ UPPER(SUBSTRING(@Data, 35, 6)) + '): '  + SUBSTRING(@DATA, 41, 40)
	                                    WHEN 'CTY' THEN ' City('+ UPPER(SUBSTRING(@Data, 35, 6)) + '): '  + SUBSTRING(@DATA, 41, 40)
	                                    WHEN 'EAD' THEN ' Employer Address('+ UPPER(SUBSTRING(@Data, 35, 6)) + '): '  + SUBSTRING(@DATA, 41, 40)
	                                    WHEN 'ENM' THEN ' Employer('+ UPPER(SUBSTRING(@Data, 35, 6)) + '): '  + SUBSTRING(@DATA, 41, 40)
	                                    WHEN 'FNM' THEN ' Ind Comk First Name('+ UPPER(SUBSTRING(@Data, 35, 6)) + '): '  + SUBSTRING(@DATA, 41, 40)
	                                    WHEN 'HPH' THEN ' Homephone('+ UPPER(SUBSTRING(@Data, 35, 6)) + '): '  + SUBSTRING(@DATA, 41, 40)
	                                    WHEN 'LNM' THEN ' Ind Comk Last Name('+ UPPER(SUBSTRING(@Data, 35, 6)) + '): '  + SUBSTRING(@DATA, 41, 40)
	                                    WHEN 'OPH' THEN ' Office Phone('+ UPPER(SUBSTRING(@Data, 35, 6)) + '): '  + SUBSTRING(@DATA, 41, 40)
	                                    WHEN 'STC' THEN ' State Code('+ UPPER(SUBSTRING(@Data, 35, 6)) + '): '  + SUBSTRING(@DATA, 41, 40)
	                                    WHEN 'TAX' THEN ' Tax ID('+ UPPER(SUBSTRING(@Data, 35, 6)) + '): '  + SUBSTRING(@DATA, 41, 40)
	                                    WHEN 'TYP' THEN ' Customer Type('+ UPPER(SUBSTRING(@Data, 35, 6)) + '): '  + SUBSTRING(@DATA, 41, 40)
	                                    WHEN 'ZIP' THEN ' ZipCode('+ UPPER(SUBSTRING(@Data, 35, 6)) + '): '  + SUBSTRING(@DATA, 41, 40)
                                            END
	                            )
                                    
     END
ELSE
     BEGIN
          SET @Comment = (SELECT CASE UPPER(SUBSTRING(@Data, 35, 6))
	                     WHEN 'ANNAD1' THEN 'Defendant Attorney Address 1(ANNAD1): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'ANNAD2' THEN 'Defendant Attorney Address 2(ANNAD2): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'ANNNAM' THEN 'CM Attorney Name(ANNNAM): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'ANNOPH' THEN 'CM Attorney Phone(ANNOPH): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'ANNCTY' THEN 'CM Attorney City(ANNCTY): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'ANNSTC' THEN 'CM Attorney State Code(ANNSTC): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'ANNZIP' THEN 'CM Attorney Zip Code(ANNZIP): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'ANNAD1' THEN 'CM Attorney Address 1(ANNAD1): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'ANNAD2' THEN 'CM Attorney Address 2(ANNAD2): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'C01TAX' THEN 'Co-Maker Tax-ID(SSN)(C01TAX): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'C01LFB' THEN 'Co-Maker Liable Flag(C01LFB): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASSTC' THEN 'State(MASSTC): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASZIP' THEN 'Zip Code(MASZIP): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASDCO' THEN 'Date Charged Off(MASDCO): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'CORDES' THEN 'Charge Off Description(CORDES): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'CRTAD1' THEN 'Court Address Line 1(CRTAD1): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'CRTAD2' THEN 'Court Address Line 2(CRTAD2): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'CRTCDD' THEN 'Court Code(CRTCDD): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'CRTCTY' THEN 'Court City(CRTCTY): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'CRTNAM' THEN 'Court Name(CRTNAM): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'CRTOPH' THEN 'Court Office Phone(CRTOPH): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'CRTSTC' THEN 'Court State Code(CRTSTC): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'CRTZIP' THEN 'Court Zip Code(CRTZIP): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'DLRDES' THEN 'Dealer Description(DLRDES): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'LTPDES' THEN 'Load Type Description(LTPDES): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MAS2FN' THEN 'Cosignor First Name(MAS2FN): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MAS2LN' THEN 'Cosignor Last Name(MAS2LN): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASACS' THEN 'Associated Costs(MASACS): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASACT' THEN 'Account Number(MASACT): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASAD1' THEN 'Debtor Address Line 1(MASAD1): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASAD2' THEN 'Debtor Address Line 2(MASAD2): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASAD3' THEN 'Debtor Address Line 3(MASAD3): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASAD4' THEN 'Debtor Address Line 4(MASAD4): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASADF' THEN 'Address Flag(MASADF): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASAIN' THEN 'Accrued Interest(MASAIN): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASATT' THEN 'Attorney Code(MASATT): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASBAM' THEN 'Previous Bill Amount(MASBAM): ' + CONVERT(VARCHAR(1000),(SELECT dbo.Custom_ConvertIBMSignedtoDecimal(SUBSTRING(@DATA, 41, 40))))
	                     WHEN 'MASBDT' THEN 'Previous Bill Date(MASBDT): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASBDY' THEN 'Debtor Birthday(MASBDY): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASBIA' THEN 'Prev Bill Init Amt(MASBIA): ' + CONVERT(VARCHAR(1000),(SELECT dbo.Custom_ConvertIBMSignedtoDecimal(SUBSTRING(@DATA, 41, 40))))
	                     WHEN 'MASBID' THEN 'Prev Bill Init Date(MASBID): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASBPC' THEN 'Block Payment Code(MASBPC): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASBPD' THEN 'Previous Bill Past Due(MASBPD): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASCCC' THEN 'Comp Call Code(MASCCC): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASCDT' THEN 'Contract Date(MASCDT): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASCFI' THEN 'Contract Frequency Indicator(MASCFI): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASCFQ' THEN 'Contract Frequency(MASCFQ): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASCKF' THEN 'Comaker Flag(MASCKF): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASCNM' THEN 'Debtor Corp. Name(MASCNM): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASCNT' THEN 'Debtor County(MASCNT): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASCOA' THEN 'Charge Off Amount(MASCOA): ' + CONVERT(VARCHAR(1000),(SELECT dbo.Custom_ConvertIBMSignedtoDecimal(SUBSTRING(@DATA, 41, 40))))
	                     WHEN 'MASCOM' THEN 'Commission(MASCOM): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASCOR' THEN 'Charge Off Reason(MASCOR): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASCRT' THEN 'Court Code(MASCRT): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASCTY' THEN 'City(MASCTY): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASCYC' THEN 'Cycle(MASCYC): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASDAS' THEN 'Date Assigned(MASDAS): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASDBC' THEN 'Database Code(MASDBC): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASDCO' THEN 'Date Charge Off(MASDCO): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASDDT' THEN 'Date Dead(MASDDT): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASDLR' THEN 'Dealer Code(MASDLR): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASEAD' THEN 'Debtor Employer Address(MASEAD): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASENM' THEN 'New Employer Name(MASENM): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASFCV' THEN 'Recoverer Code(MASFCV): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASFNM' THEN 'First Name(MASFNM): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASFRC' THEN 'Financial Recoverer(MASFRC): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASFRD' THEN 'Date Received(MASFRD): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASHC1' THEN 'Last Comment 1(MASHC1): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASHC2' THEN 'Last Comment 2(MASHC2): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASHC3' THEN 'Last Comment 3(MASHC3): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASHPF' THEN 'Home Phone Flag(MASHPF): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASHPH' THEN 'Home Phone# (MASHPH): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASIOD' THEN 'Prev Bill Init PST Due(MASIOD): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASIPA' THEN 'Initial Payment Amount(MASIPA): ' + CONVERT(VARCHAR(1000),(SELECT dbo.Custom_ConvertIBMSignedtoDecimal(SUBSTRING(@DATA, 41, 40))))
	                     WHEN 'MASIPD' THEN 'Initial Payment Date(MASIPD): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASIRC' THEN 'Interest Rate(MASIRC): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASJCF' THEN 'Judgement Charge Off(MASJCF): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASJCS' THEN 'Judgement Costs(MASJCS): ' + CONVERT(VARCHAR(1000),(SELECT dbo.Custom_ConvertIBMSignedtoDecimal(SUBSTRING(@DATA, 41, 40))))
	                     WHEN 'MASJDT' THEN 'Judgement Date(MASJDT): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASJEK' THEN 'Book(MASJEK): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASJEX' THEN 'Judgement Excess(MASJEX): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASJIN' THEN 'Judgement Interests(MASJIN): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASJON' THEN 'Judgement On(MASJON): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASJPG' THEN 'Page(MASJPG): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASJRC' THEN 'Judgement Recorded(MASJRC): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASJRV' THEN 'Judgement Recovered(MASJRV): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASJXD' THEN 'Judgement Expire Date(MASJXD): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASLBD' THEN 'Last Bill Date(MASLBD): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASLCC' THEN 'Court Description(MASLCC): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASLCD' THEN 'Last Contract Date(MASLCD): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASLCN' THEN 'Case Number(MASLCN): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASLCT' THEN 'Court Time(MASLCT): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASLDT' THEN 'Court Date(MASLDT): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASLID' THEN 'Last Interest Date(MASLID): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASLIR' THEN 'Lending Income Rate(MASLIR): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASLLV' THEN 'Lending Levels(MASLLV): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASLMD' THEN 'Last Comment Date(MASLMD): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASLNM' THEN 'Last Name(MASLNM): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASLOC' THEN 'File Location(MASLOC): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASLPD' THEN 'Last Payment Date(MASLPD): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASLTR' THEN 'Letter Name(MASLTR): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASMEX' THEN 'Debtor Monthly Expense(MASMEX): ' + CONVERT(VARCHAR(1000),(SELECT dbo.Custom_ConvertIBMSignedtoDecimal(SUBSTRING(@DATA, 41, 40))))
	                     WHEN 'MASMIN' THEN 'Debtor Monthly Income(MASMIN): ' + CONVERT(VARCHAR(1000),(SELECT dbo.Custom_ConvertIBMSignedtoDecimal(SUBSTRING(@DATA, 41, 40))))
	                     WHEN 'MASOEX' THEN 'Debtor Other Expense(MASOEX): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASNCD' THEN 'Next Contact Date(MASNCD): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASOEX' THEN 'Debtor Other Expense(MASOEX): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASOFF' THEN 'Officer Code(MASOFF): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASOIN' THEN 'Debtor Other Incomce(MASOIN): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASON' THEN 'Debtor Own/Rent Code(MASON): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASOPE' THEN 'Office Phone Flag(MASOPE): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASOPH' THEN 'Office Phone# (MASOPH): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASPA1' THEN 'Past Due Amount 1(MASPA1): ' + CONVERT(VARCHAR(1000),(SELECT dbo.Custom_ConvertIBMSignedtoDecimal(SUBSTRING(@DATA, 41, 40))))
	                     WHEN 'MASPA2' THEN 'Past Due Amount 2(MASPA2): ' + CONVERT(VARCHAR(1000),(SELECT dbo.Custom_ConvertIBMSignedtoDecimal(SUBSTRING(@DATA, 41, 40))))
	                     WHEN 'MASPA3' THEN 'Past Due Amount 3(MASPA3): ' + CONVERT(VARCHAR(1000),(SELECT dbo.Custom_ConvertIBMSignedtoDecimal(SUBSTRING(@DATA, 41, 40))))
	                     WHEN 'MASPA4' THEN 'Past Due Amount 4(MASPA4): ' + CONVERT(VARCHAR(1000),(SELECT dbo.Custom_ConvertIBMSignedtoDecimal(SUBSTRING(@DATA, 41, 40))))
	                     WHEN 'MASPA5' THEN 'Past Due Amount 5(MASPA5): ' + CONVERT(VARCHAR(1000),(SELECT dbo.Custom_ConvertIBMSignedtoDecimal(SUBSTRING(@DATA, 41, 40))))
	                     WHEN 'MASPA6' THEN 'Past Due Amount 6(MASPA6): ' + CONVERT(VARCHAR(1000),(SELECT dbo.Custom_ConvertIBMSignedtoDecimal(SUBSTRING(@DATA, 41, 40))))
	                     WHEN 'MASPA7' THEN 'Past Due Amount 7(MASPA7): ' + CONVERT(VARCHAR(1000),(SELECT dbo.Custom_ConvertIBMSignedtoDecimal(SUBSTRING(@DATA, 41, 40))))
	                     WHEN 'MASPA8' THEN 'Past Due Amount 8(MASPA8): ' + CONVERT(VARCHAR(1000),(SELECT dbo.Custom_ConvertIBMSignedtoDecimal(SUBSTRING(@DATA, 41, 40))))
	                     WHEN 'MASPAC' THEN 'Payment Apply Code(MASPAC): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASPAM' THEN 'Payment Amount(MASPAM): ' + CONVERT(VARCHAR(1000),(SELECT dbo.Custom_ConvertIBMSignedtoDecimal(SUBSTRING(@DATA, 41, 40))))
	                     WHEN 'MASPCC' THEN 'Block Comment Code(MASPCC): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASPDA' THEN 'Past Due Amount(MASPDA): ' + CONVERT(VARCHAR(1000),(SELECT dbo.Custom_ConvertIBMSignedtoDecimal(SUBSTRING(@DATA, 41, 40))))
	                     WHEN 'MASPDD' THEN 'Payment Due Date(MASPDD): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASPFI' THEN 'Payment Frequency Indicator(MASPFI): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASPFQ' THEN 'Payment Frequency(MASPFQ): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASPIR' THEN 'Previous Interest Rate(MASPIR): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASPPY' THEN 'Partial Payment(MASPPY): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASPSD' THEN 'Not Late Until Date(MASPSD): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASRC1' THEN 'Previous Recoverer 1(MASRC1): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASRC2' THEN 'Previous Recoverer 2(MASRC2): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASRC3' THEN 'Previous Recoverer 3(MASRC3): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASRC4' THEN 'Previous Recoverer 4(MASRC4): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASRCS' THEN 'Recovered Costs(MASRCS): ' + CONVERT(VARCHAR(1000),(SELECT dbo.Custom_ConvertIBMSignedtoDecimal(SUBSTRING(@DATA, 41, 40))))
	                     WHEN 'MASRIN' THEN 'Recovered Interest(MASRIN): ' + CONVERT(VARCHAR(1000),(SELECT dbo.Custom_ConvertIBMSignedtoDecimal(SUBSTRING(@DATA, 41, 40))))
	                     WHEN 'MASRPR' THEN 'Recovered Principal(MASRPR): ' + CONVERT(VARCHAR(1000),(SELECT dbo.Custom_ConvertIBMSignedtoDecimal(SUBSTRING(@DATA, 41, 40))))
	                     WHEN 'MASRQT' THEN 'Reque Date(MASRQT): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASRQT' THEN 'Reque Time(MASRQT): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASRVC' THEN 'Judgement Recovered Costs(MASRVC): ' + CONVERT(VARCHAR(1000),(SELECT dbo.Custom_ConvertIBMSignedtoDecimal(SUBSTRING(@DATA, 41, 40))))
	                     WHEN 'MASRVI' THEN 'Judgement Recovered Interest(MASRVI): ' + CONVERT(VARCHAR(1000),(SELECT dbo.Custom_ConvertIBMSignedtoDecimal(SUBSTRING(@DATA, 41, 40))))
	                     WHEN 'MASSCR' THEN 'Credit Recover Score(MASSCR): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASSCS' THEN 'Suit Costs(MASSCS): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASSDT' THEN 'Suit Filed Date(MASSDT): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASSIN' THEN 'Suit Interest(MASSIN): ' + CONVERT(VARCHAR(1000),(SELECT dbo.Custom_ConvertIBMSignedtoDecimal(SUBSTRING(@DATA, 41, 40))))
	                     WHEN 'MASSPN' THEN 'Suit Principal(MASSPN): ' + CONVERT(VARCHAR(1000),(SELECT dbo.Custom_ConvertIBMSignedtoDecimal(SUBSTRING(@DATA, 41, 40))))
	                     WHEN 'MASSTC' THEN 'State(MASSTC): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASTAX' THEN 'New Social Security Number(MASTAX): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASTDU' THEN 'Total Due(MASTDU): ' + CONVERT(VARCHAR(1000),(SELECT dbo.Custom_ConvertIBMSignedtoDecimal(SUBSTRING(@DATA, 41, 40))))
	                     WHEN 'MASTTL' THEN 'CM Title(MASTTL): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASTYP' THEN 'Customer Type(MASTYP): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASU01' THEN 'External Status(MASU01): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASU02' THEN 'Internal Status(MASU02): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASU03' THEN 'Option Code(MASU03): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASU04' THEN 'Current Pool Number(MASU04): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASU05' THEN 'Terms Level Code(MASU05): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASU06' THEN 'Expiration Date(MASU06): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASU09' THEN 'Previous Pool Number(MASU09): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASU10' THEN 'RMS Code(MASU10): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASU11' THEN 'Previous Credit Bureau Indicator(MASU26): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASU12' THEN 'Statement Hold(MASU12): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASU13' THEN 'Last Monetary Date(MASU13): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASU14' THEN 'Times 1 Cycle(MASU14): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASU15' THEN 'Times 2 Cycle(MASU15): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASU16' THEN 'Times 3 Cycle(MASU16): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASU17' THEN 'Days Deliquent(MASU17): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASU18' THEN 'Cash Advance Amount(MASU18): ' + CONVERT(VARCHAR(1000),(SELECT dbo.Custom_ConvertIBMSignedtoDecimal(SUBSTRING(@DATA, 41, 40))))
	                     WHEN 'MASU19' THEN 'Last Monetary Indicator(MASU19): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASU20' THEN 'Credit Limit(MASU20): ' + CONVERT(VARCHAR(1000),(SELECT dbo.Custom_ConvertIBMSignedtoDecimal(SUBSTRING(@DATA, 41, 40))))
	                     WHEN 'MASU21' THEN 'Amount Now Due(MASU21): ' + CONVERT(VARCHAR(1000),(SELECT dbo.Custom_ConvertIBMSignedtoDecimal(SUBSTRING(@DATA, 41, 40))))
	                     WHEN 'MASU22' THEN 'Restrict Outside Placement(MASU22): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASU23' THEN 'Restrict Sale of Account(MASU23): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASU24' THEN 'Securitization Flag(MASU24): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASU25' THEN 'Current Credit Bureau Indicator(MASU26): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASU26' THEN 'Payment History Codes(MASU26): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASU27' THEN 'Account Transfer Flag(MASU27): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASU28' THEN 'Date of Sale(MASU28): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASU29' THEN 'IRS 1099C(MASU29): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASU30' THEN 'Credit Life Insurance Flag(MASU30): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASU31' THEN 'Deceased/POC Information(MASU31): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASU32' THEN 'Deceased/POC Information(MASU32): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASU33' THEN 'Deceased/POC Information(MASU33): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASU34' THEN 'Deceased/POC Information(MASU34): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASU35' THEN 'Deceased/POC Information(MASU35): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASU36' THEN 'Deceased/POC Information(MASU36): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASU37' THEN 'Block Statement/Letter Flags(MASU37): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASU38' THEN 'Block Statement/Letter Flags(MASU38): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASU39' THEN 'Collector Queue Code(MASU39): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'MASU41' THEN 'Last Payment Amount(MASU41): ' + CONVERT(VARCHAR(1000),(SELECT dbo.Custom_ConvertIBMSignedtoDecimal(SUBSTRING(@DATA, 41, 40))))
	                     WHEN 'MASUDC' THEN 'User Defined Costs(MASUDC): ' + CONVERT(VARCHAR(1000),(SELECT dbo.Custom_ConvertIBMSignedtoDecimal(SUBSTRING(@DATA, 41, 40))))
	                     WHEN 'MASUDR' THEN 'User Defined Recovered(MASUDR): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'NRCAD1' THEN 'Recoverer Address 1(NRCAD1): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'NRCAD2' THEN 'Recoverer Address 2(NRCAD2): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'NRCCNT' THEN 'Recoverer County(NRCCNT): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'NRCCON' THEN 'Recoverer Contact(NRCCON): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'NRCCTY' THEN 'Recoverer City(NRCCTY): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'NRCFAX' THEN 'Recoverer Fax Number(NRCFAX): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'NRCNAM' THEN 'Recoverer Name(NRCNAM): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'NRCOPH' THEN 'Recoverer Recoverer(NRCOPH): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'NRCSTC' THEN 'Recoverer State Code(NRCSTC): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'NRCTTL' THEN 'Recoverer Title(NRCTTL): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'NRCZIP' THEN 'Recoverer Zip Code(NRCZIP): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'PASRC5' THEN 'Previous Recoverer 5(PASRC5): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'TNNAD1' THEN 'Trustee Address 1(TNNAD1): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'TNNAD2' THEN 'Trustee Address 2(TNNAD2): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'TNNCTY' THEN 'Trustee City(TNNCTY): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'TNNNAM' THEN 'Trustee Name(TNNNAM): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'TNNOPH' THEN 'Trustee Phone(TNNOPH): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'TNNSTC' THEN 'Trustee State Code(TNNSTC): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'TNNZIP' THEN 'Trustee Zip Code(TNNZIP): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'VARAD1' THEN 'Variable Address 1(VARAD1): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'VARAD2' THEN 'Variable Address 2(VARAD2): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'VARCTY' THEN 'Variable City(VARCTY): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'VARNAM' THEN 'Variable Name(VARNAM): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'VARPHR' THEN 'Variable Phrase(VARPHR): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'VARSTC' THEN 'Variable State Code(VARSTC): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'VARZIP' THEN 'Variable Zip Code(VARZIP): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'WRKAMT' THEN 'Work Transaction Amount(WRKAMT): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'WRKBNM' THEN 'Work Bank Name(WRKBNM): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'WRKCNM' THEN 'Work Co-Maker Name(WRKCNM): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'WRKCTI' THEN 'Work Co-Maker Tax-ID(WRKCTI): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'WRKDDT' THEN 'Work Demand Date(WRKDDT): ' + SUBSTRING(@DATA, 41, 40)	
	                     WHEN 'WRKMTI' THEN 'Work Customer TaxID(WRKMTI): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'WRKNAM' THEN 'Work Customer Name(WRKNAM): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'WRKNCS' THEN 'Work Net Costs(WRKNCS): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'WRKNIN' THEN 'Work Net Interest(WRKNIN): ' + SUBSTRING(@DATA, 41, 40)
		  	     WHEN 'WRKORG' THEN 'Work Recoverer Organization(WRKORG): ' + SUBSTRING(@DATA, 41, 40)
		  	     WHEN 'WRKRNM' THEN 'Work Recoverer Name(WRKTWI): ' + SUBSTRING(@DATA, 41, 40)
		  	     WHEN 'WRKTNI' THEN 'Work Total without Interest(WRKTWI): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'WRKTWI' THEN 'Work Total with Interest(WRKTWI): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'WRKUPP' THEN 'Work Unpaid Principal(WRKUPP): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'WRKUPP' THEN 'Work Unpaid Principal(WRKUPP): ' + SUBSTRING(@DATA, 41, 40)
	                     WHEN 'XXXXXX' THEN 'Save Vehicle ID Information(XXXXXX): ' + SUBSTRING(@DATA, 41, 40)
	                     ELSE UPPER(SUBSTRING(@Data, 35, 6)) + ': ' + SUBSTRING(@DATA, 41, 40)
                    END)

      END

IF @Number > 0
     BEGIN

	 INSERT INTO NOTES(Number, CTL, Created, User0, [Action], Result, Comment)
	 VALUES(@Number, 'CTL', GetDate(), @User, 'DSCVR','RMSUPD', @Comment)

	 -- Reflect a note was entered.
         SELECT 1 as IResult
     END	
ELSE
   -- Reflect a note was note entered.
   SELECT 0 as IResult


SET NOCOUNT OFF




-- 	 INSERT INTO NOTES(Number, CTL, Created, User0, [Action], Result, Comment)
-- 	 VALUES(@Number, 'CTL', GetDate(), @User, 'DSCVR','RMSUPD',
--                 CASE UPPER(SUBSTRING(@Data, 35, 6))
--                      WHEN 'ANNAD1' THEN 'Defendant Attorney Address 1(ANNAD1): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'ANNAD2' THEN 'Defendant Attorney Address 2(ANNAD2): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'ANNNAM' THEN 'CM Attorney Name(ANNNAM): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'ANNOPH' THEN 'CM Attorney Phone(ANNOPH): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'ANNCTY' THEN 'CM Attorney City(ANNCTY): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'ANNSTC' THEN 'CM Attorney State Code(ANNSTC): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'ANNZIP' THEN 'CM Attorney Zip Code(ANNZIP): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'ANNAD1' THEN 'CM Attorney Address 1(ANNAD1): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'ANNAD2' THEN 'CM Attorney Address 2(ANNAD2): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'C01TAX' THEN 'Co-Maker Tax-ID(SSN)(C01TAX): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'C01LFB' THEN 'Co-Maker Liable Flag(C01LFB): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASSTC' THEN 'State(MASSTC): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASZIP' THEN 'Zip Code(MASZIP): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASDCO' THEN 'Date Charged Off(MASDCO): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'CORDES' THEN 'Charge Off Description(MASZIP): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'CRTAD1' THEN 'Court Address Line 1(MASZIP): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'CRTAD2' THEN 'Court Address Line 2(MASZIP): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'CRTCDD' THEN 'Court Code(MASZIP): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'CRTCTY' THEN 'Court City(MASZIP): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'CRTNAM' THEN 'Court Name(MASZIP): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'CRTOPH' THEN 'Court Office Phone(MASZIP): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'CRTSTC' THEN 'Court State Code(MASZIP): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'CRTZIP' THEN 'Court Zip Code(MASZIP): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'DLRDES' THEN 'Dealer Description(MASAD1): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'LTPDES' THEN 'Load Type Description(MASAD1): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MAS2FN' THEN 'Cosignor First Name(MASAD1): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MAS2LN' THEN 'Cosignor Last Name(MASAD1): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASACS' THEN 'Associated Costs(MASAD1): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASACT' THEN 'Account Number(MASAD1): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASAD1' THEN 'Debtor Address Line 1(MASAD1): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASAD2' THEN 'Debtor Address Line 2(MASAD2): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASAD3' THEN 'Debtor Address Line 3(MASAD3): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASAD4' THEN 'Debtor Address Line 4(MASAD4): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASADF' THEN 'Address Flag(MASADF): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASAIN' THEN 'Accrued Interest(MASCTY): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASATT' THEN 'Attorney Code(MASCTY): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASBAM' THEN 'Previous Bill Amount(MASCTY): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASBDT' THEN 'Previous Bill Date(MASCTY): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASBDY' THEN 'Debtor Birthday(MASCTY): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASBIA' THEN 'Prev Bill Init Amt(MASCTY): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASBID' THEN 'Prev Bill Init Date(MASCTY): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASBPC' THEN 'Block Payment Code(MASCTY): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASBPD' THEN 'Previous Bill Past Due(MASCTY): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASCCC' THEN 'Comp Call Code(MASCTY): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASCDT' THEN 'Contract Date(MASCTY): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASCFI' THEN 'Contract Frequency Indicator(MASCTY): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASCFQ' THEN 'Contract Frequency(MASCTY): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASCKF' THEN 'Comaker Flag(MASCTY): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASCNM' THEN 'Debtor Corp. Name(MASCTY): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASCNT' THEN 'Debtor County(MASCTY): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASCOA' THEN 'Charge Off Amount(MASCTY): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASCOM' THEN 'Commission(MASCTY): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASCOR' THEN 'Charge Off Reason(MASCTY): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASCRT' THEN 'Court Code(MASCTY): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASCTY' THEN 'City(MASCTY): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASCYC' THEN 'Cycle(MASFNM): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASDAS' THEN 'Date Assigned(MASFNM): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASDBC' THEN 'Database Code(MASFNM): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASDCO' THEN 'Date Charge Off(MASFNM): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASDDT' THEN 'Date Dead(MASFNM): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASDLR' THEN 'Dealer Code(MASFNM): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASEAD' THEN 'Debtor Employer Address(MASFNM): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASENM' THEN 'New Employer Name(MASFNM): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASFCV' THEN 'Recoverer Code(MASFNM): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASFNM' THEN 'First Name(MASFNM): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASFRC' THEN 'Financial Recoverer(MASHPH): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASFRD' THEN 'Date Received(MASHPH): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASHC1' THEN 'Last Comment 1(MASHPH): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASHC2' THEN 'Last Comment 2(MASHPH): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASHC3' THEN 'Last Comment 3(MASHPH): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASHPF' THEN 'Home Phone Flag(MASTTL): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASHPH' THEN 'Home Phone# (MASHPH): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASIOD' THEN 'Prev Bill Init PST Due(MASTTL): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASIPA' THEN 'Initial Payment Amount(MASTTL): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASIPD' THEN 'Initial Payment Date(MASTTL): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASIRC' THEN 'Interest Rate(MASTTL): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASJCF' THEN 'Judgement Charge Off(MASTTL): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASJCS' THEN 'Judgement Costs(MASTTL): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASJDT' THEN 'Judgement Date(MASTTL): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASJEK' THEN 'Book(MASTTL): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASJEX' THEN 'Judgement Excess(MASTTL): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASJIN' THEN 'Judgement Interests(MASTTL): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASJON' THEN 'Judgement On(MASTTL): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASJPG' THEN 'Page(MASTTL): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASJRC' THEN 'Judgement Recorded(MASTTL): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASJRV' THEN 'Judgement Recovered(MASTTL): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASJXD' THEN 'Judgement Expire Date(MASTTL): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASLBD' THEN 'Last Bill Date(MASTTL): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASLCC' THEN 'Court Description(MASTTL): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASLCD' THEN 'Last Contract Date(MASTTL): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASLCN' THEN 'Case Number(MASTTL): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASLCT' THEN 'Court Time(MASTTL): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASLDT' THEN 'Court Date(MASTTL): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASLID' THEN 'Last Interest Date(MASTTL): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASLIR' THEN 'Lending Income Rate(MASTTL): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASLLV' THEN 'Lending Levels(MASTTL): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASLMD' THEN 'Last Comment Date(MASLNM): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASLNM' THEN 'Last Name(MASLNM): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASLOC' THEN 'File Location(MASADF): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASLPD' THEN 'Last Payment Date(MASADF): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASLTR' THEN 'Letter Name(MASADF): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASMEX' THEN 'Debtor Monthly Expense(MASADF): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASMIN' THEN 'Debtor Monthly Income(MASADF): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASOEX' THEN 'Debtor Other Expense(MASOPH): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASNCD' THEN 'Next Contact Date(MASNCD): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASOEX' THEN 'Debtor Other Expense(MASOPH): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASOFF' THEN 'Officer Code(MASOPH): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASOIN' THEN 'Debtor Other Incomce(MASOPH): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASON' THEN 'Debtor Own/Rent Code(MASOPH): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASOPE' THEN 'Office Phone Flag(MASOPE): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASOPH' THEN 'Office Phone# (MASOPH): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASPA1' THEN 'Past Due Amount 1(PASRC5): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASPA2' THEN 'Past Due Amount 2(PASRC5): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASPA3' THEN 'Past Due Amount 3(PASRC5): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASPA4' THEN 'Past Due Amount 4(PASRC5): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASPA5' THEN 'Past Due Amount 5(PASRC5): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASPA6' THEN 'Past Due Amount 6(PASRC5): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASPA7' THEN 'Past Due Amount 7(PASRC5): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASPA8' THEN 'Past Due Amount 8(PASRC5): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASPAC' THEN 'Payment Apply Code(PASRC5): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASPAM' THEN 'Payment Amount(MASPAM): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASPCC' THEN 'Block Comment Code(PASRC5): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASPDA' THEN 'Past Due Amount(PASRC5): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASPDD' THEN 'Payment Due Date(PASRC5): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASPFI' THEN 'Payment Frequency Indicator(MASPFI): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASPFQ' THEN 'Payment Frequency(MASPFQ): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASPIR' THEN 'Previous Interest Rate(PASRC5): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASPPY' THEN 'Partial Payment(PASRC5): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASPSD' THEN 'Not Late Until Date(PASRC5): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASRC1' THEN 'Previous Recoverer 1(PASRC5): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASRC2' THEN 'Previous Recoverer 2(PASRC5): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASRC3' THEN 'Previous Recoverer 3(PASRC5): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASRC4' THEN 'Previous Recoverer 4(PASRC5): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASRCS' THEN 'Recovered Costs(MASU01): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASRIN' THEN 'Recovered Interest(MASU01): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASRPR' THEN 'Recovered Principal(MASU01): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASRQT' THEN 'Reque Date(MASU01): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASRQT' THEN 'Reque Time(MASU01): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASRVC' THEN 'Judgement Recovered Costs(MASU01): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASRVI' THEN 'Judgement Recovered Interest(MASU01): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASSCR' THEN 'Credit Recover Score(MASU01): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASSCS' THEN 'Suit Costs(MASU01): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASSDT' THEN 'Suit Filed Date(MASU01): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASSIN' THEN 'Suit Interest(MASU01): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASSPN' THEN 'Suit Principal(MASU01): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASSTC' THEN 'State(MASU01): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASTAX' THEN 'New Social Security Number(MASU01): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASTDU' THEN 'Total Due(MASU01): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASTTL' THEN 'CM Title(MASTTL): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASTYP' THEN 'Customer Type(MASU01): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASU01' THEN 'External Status(MASU01): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASU02' THEN 'Internal Status(MASU02): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASU03' THEN 'Option Code(MASU03): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASU04' THEN 'Current Pool Number(MASU04): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASU05' THEN 'Terms Level Code(MASU05): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASU06' THEN 'Expiration Date(MASU06): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASU09' THEN 'Previous Pool Number(MASU09): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASU10' THEN 'RMS Code(MASU10): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASU11' THEN 'Previous Credit Bureau Indicator(MASU26): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASU12' THEN 'Statement Hold(MASU12): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASU13' THEN 'Last Monetary Date(MASU13): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASU14' THEN 'Times 1 Cycle(MASU14): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASU15' THEN 'Times 2 Cycle(MASU15): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASU16' THEN 'Times 3 Cycle(MASU16): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASU17' THEN 'Days Deliquent(MASU17): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASU18' THEN 'Cash Advance Amount(MASU18): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASU19' THEN 'Last Monetary Indicator(MASU19): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASU20' THEN 'Credit Limit(MASU20): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASU21' THEN 'Amount Now Due(MASU21): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASU22' THEN 'Restrict Outside Placement(MASU22): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASU23' THEN 'Restrict Sale of Account(MASU23): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASU24' THEN 'Securitization Flag(MASU24): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASU25' THEN 'Current Credit Bureau Indicator(MASU26): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASU26' THEN 'Payment History Codes(MASU26): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASU27' THEN 'Account Transfer Flag(MASU27): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASU28' THEN 'Date of Sale(MASU28): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASU29' THEN 'IRS 1099C(MASU29): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASU30' THEN 'Credit Life Insurance Flag(MASU37): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASU31' THEN 'Deceased/POC Information(MASU37): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASU32' THEN 'Deceased/POC Information(MASU37): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASU33' THEN 'Deceased/POC Information(MASU37): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASU34' THEN 'Deceased/POC Information(MASU37): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASU35' THEN 'Deceased/POC Information(MASU37): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASU36' THEN 'Deceased/POC Information(MASU36): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASU37' THEN 'Block Statement/Letter Flags(MASU37): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASU38' THEN 'Block Statement/Letter Flags(MASU38): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASU39' THEN 'Collector Queue Code(MASU39): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASU41' THEN 'Last Payment Amount(MASU41): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASUDC' THEN 'User Defined Costs(MASUDC): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'MASUDR' THEN 'User Defined Recovered(MASUDR): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'NRCAD1' THEN 'Recoverer Address 1(NRCZIP): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'NRCAD2' THEN 'Recoverer Address 2(NRCZIP): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'NRCCNT' THEN 'Recoverer County(NRCZIP): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'NRCCON' THEN 'Recoverer Contact(NRCCON): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'NRCCTY' THEN 'Recoverer City(NRCCTY): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'NRCFAX' THEN 'Recoverer Fax Number(NRCZIP): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'NRCNAM' THEN 'Recoverer Name(NRCNAM): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'NRCOPH' THEN 'Recoverer Recoverer(NRCOPH): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'NRCSTC' THEN 'Recoverer State Code(NRCSTC): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'NRCTTL' THEN 'Recoverer Title(NRCTTL): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'NRCZIP' THEN 'Recoverer Zip Code(NRCZIP): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'PASRC5' THEN 'Previous Recoverer 5(PASRC5): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'TNNAD1' THEN 'Trustee Address 1(TNNAD1): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'TNNAD2' THEN 'Trustee Address 2(TNNAD2): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'TNNCTY' THEN 'Trustee City(TNNCTY): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'TNNNAM' THEN 'Trustee Name(TNNNAM): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'TNNOPH' THEN 'Trustee Phone(TNNOPH): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'TNNSTC' THEN 'Trustee State Code(TNNSTC): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'TNNZIP' THEN 'Trustee Zip Code(TNNZIP): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'VARAD1' THEN 'Variable Address 1(VARAD1): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'VARAD2' THEN 'Variable Address 2(VARAD2): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'VARCTY' THEN 'Variable City(VARCTY): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'VARNAM' THEN 'Variable Name(VARNAM): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'VARPHR' THEN 'Variable Phrase(VARPHR): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'VARSTC' THEN 'Variable State Code(VARSTC): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'VARZIP' THEN 'Variable Zip Code(VARZIP): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'WRKAMT' THEN 'Work Transaction Amount(WRKAMT): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'WRKBNM' THEN 'Work Bank Name(WRKBNM): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'WRKCNM' THEN 'Work Co-Maker Name(WRKCNM): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'WRKCTI' THEN 'Work Co-Maker Tax-ID(WRKCTI): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'WRKDDT' THEN 'Work Demand Date(WRKDDT): ' + SUBSTRING(@DATA, 41, 40)	
--                      WHEN 'WRKMTI' THEN 'Work Customer TaxID(WRKMTI): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'WRKNAM' THEN 'Work Customer Name(WRKNAM): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'WRKNCS' THEN 'Work Net Costs(WRKNCS): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'WRKNIN' THEN 'Work Net Interest(WRKNIN): ' + SUBSTRING(@DATA, 41, 40)
-- 	  	     WHEN 'WRKORG' THEN 'Work Recoverer Organization(WRKORG): ' + SUBSTRING(@DATA, 41, 40)
-- 	  	     WHEN 'WRKRNM' THEN 'Work Recoverer Name(WRKTWI): ' + SUBSTRING(@DATA, 41, 40)
-- 	  	     WHEN 'WRKTNI' THEN 'Work Total without Interest(WRKTWI): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'WRKTWI' THEN 'Work Total with Interest(WRKTWI): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'WRKUPP' THEN 'Work Unpaid Principal(WRKUPP): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'WRKUPP' THEN 'Work Unpaid Principal(WRKUPP): ' + SUBSTRING(@DATA, 41, 40)
--                      WHEN 'XXXXXX' THEN 'Save Vehicle ID Information(XXXXXX): ' + SUBSTRING(@DATA, 41, 40)
--                      ELSE UPPER(SUBSTRING(@Data, 35, 6)) + ': ' + SUBSTRING(@DATA, 41, 40)
--                 END  
--                )


GO
