SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
/*dbo.sp_Customer_Insert*/
CREATE      PROCEDURE [dbo].[sp_Customer_Insert]
(
	@CustomerID int OUTPUT,
	@Code varchar(7),
	@Status varchar(8),
	@CustomerName varchar(100),
	@Street1 varchar(30),
	@Street2 varchar(30),
	@City varchar(20),
	@State varchar(3),
	@ZipCode varchar(10),
	@Contact varchar(30),
	@Phone varchar(20),
	@LetterCode  varchar(75),
	@BadCheck money,
	@BankCode varchar(100),
	@BankId int,
	@SalesmanCode varchar(30),
	@SifInfo text,
	@WorkInfo text,
	@MiscInfo text,
	@InvoiceType varchar(20),
	@InvoiceFreq varchar(20),
	@InvoiceSort varchar(20),
	@InvoiceMethod varchar(20),
	@FaxNumber varchar(30),
	@AmtDueClient smallint,
	@COB varchar(50),
	@RemitMethod varchar(5),
	@CustGroup varchar(7),
	@CheckHoldDays smallint,
	@InvShowRcvd bit,
	@InvShowBal bit,
	@CCostPct real,
	@CCostBucket tinyint,
	@FeeSchedule varchar(5),
	@LegalFeeSchedule varchar(5),
	@IsPodCust bit,
	@Email varchar(100),
	@ShowReverseOfDate bit,
	@AlphaCode varchar(50),
	@Sweep bit,
	@SweepDays int,
	@SweepDaysPaid int,
	@SweepMinBalance money,
	@SweepDesk varchar(10),
	@DefaultDesk varchar(10),
	@CustomDate1 datetime,
	@CustomDate2 datetime,
	@CustomDate3 datetime,
	@CustomDate4 datetime,
	@CustomDate5 datetime,
	@CustomDate6 datetime,
	@CustomDate7 datetime,
	@CustomDate8 datetime,
	@CustomDate9 datetime,
	@CustomOption1 bit,
	@CustomOption2 bit,
	@CustomOption3 bit,
	@CustomOption4 bit,
	@CustomOption5 bit,
	@CustomOption6 bit,
	@CustomOption7 bit,
	@CustomOption8 bit,
	@CustomOption9 bit,
	@CustomValue1 int,
	@CustomValue2 int,
	@CustomValue3 int,
	@CustomValue4 int,
	@CustomValue5 int,
	@CustomValue6 int,
	@CustomValue7 int,
	@CustomValue8 int,
	@CustomValue9 int,
	@CustomText1 varchar(500),
	@CustomText2 varchar(500),
	@CustomText3 varchar(500),
	@CustomText4 varchar(500),
	@CustomText5 varchar(500),
	@BlanketSif float,
	@LetterDeliveryMethod int,
	@IsPrincipleCust bit,
	@InvShowOther bit,
	@AcknowledgeNewBiz bit,
	@DefaultInterest real,
	@CollectorFeeSchedule varchar(5),
	@CbrAccountType char(2),
	@CbrCreditorClass char(2),
	@CbrOriginalCreditor varchar(30),
	@FreeDemandDays tinyint,
	@FreeDemandBatchTypes tinyint,
	@FeeCapAmount money,
	@FeeCapPercent real,
	@InvoiceReport varchar(120),
	@Priority tinyint = 5,
	@LatitudeUser varchar(256),
	@PermitSurcharge bit
)
AS
-- Name:		sp_Customer_Insert
-- Function:		This procedure will insert a new customer in Customer table
-- 			using input parameters.
-- Creation:		6/17/2002 jc
--			Used by class CCustomerFactory. 
-- Change History:
--			6/18/2002 jc added field alphacode to database revised sp
--			10/22/2002 jc added field DefaultDesk to database revised sp
--			1/6/2003 jc resized @LetterCode from varchar(30) to varchar(75)
--			2/24/2003 jc added field CbrAcctRtnSendDel
--			2/24/2003 jc added custom fields CustomDate1-9, CustomOption1-9, CustomValue1-9
--			5/15/2003 jc added field LegalFeeSchedule
--			9/5/2003 jc added field BlanketSif
--			9/19/2003 jc added field LetterDeliveryMethod
--			11/17/2003 jc increased parm @Email from varchar(30) to varchar(100)
--			12/4/2003 jc added field IsPrincipleCust
--			01/16/2004 jc increased parm @@BankCode from varchar(30) to varchar(100)
--			01/23/2004 jc added custom fields CustomText1-5
--			3/29/2004 jc added output parameter @CustomerID to return identity value of field CCustomerId
--			5/28/2004 jc added field bankid
--			7/1/2004 jc added fields InvShowOther, AcknowledgeNewBiz, DefaultInterest
--			10/29/2004 jc added field CollectorFeeSchedule
--			7/8/2005 jc removed parms @CbrRptType varchar(50), @CbrClass varchar(40), @CbrMinBal money, @CbrWaitDays int, 
--			@CbrAcctRtnSendDel bit, @UseEquifax bit, @UseTransUnion bit, @UseExperian bit, @UseInnovis bit
--			added new parms @CbrAccountType char(2), @CbrCreditorClass char(2), @CbrOriginalCreditor varchar(30)
--			4/20/06 MDD - Added @FreeDemandDays, @FeeCapAmount money, @FeeCapPercent, @InvoiceReport, @LatitudeUser
--			7/11/08 JBS - Added @Priority
    BEGIN TRAN
	IF ISNULL(@LatitudeUser, suser_sname()) = '' 
		Select @LatitudeUser = suser_sname()
	ELSE
		Select @LatitudeUser = @LatitudeUser
	
	INSERT INTO Customer 
		(customer,
		status,
		Name,
		Street1,
		Street2,
		City,
		State,
		Zipcode,
		Contact,
		phone,
		lettercode,
		badcheck,
		bankcode,
		bankid,
		salesmancode,
		sifinfo,
		workinfo,
		miscinfo,
		invoicetype,
		invoicefreq,
		invoicesort,
		invoicemethod,
		FaxNumber,
		AmtDueClient,
		cob,
		RemitMethod,
		CustGroup,
		CheckHoldDays,
		InvShowRcvd,
		InvShowBal,
		CCostPct,
		CCostBucket,
		FeeSchedule,
		LegalFeeSchedule,
		IsPODCust,
		eMail,
		ShowReverseofDate,
		AlphaCode,
		Sweep,
		SweepDays,
		SweepDaysPaid,
		SweepMinBalance,
		SweepDesk,
		DefaultDesk,
		CustomDate1,
		CustomDate2,
		CustomDate3,
		CustomDate4,
		CustomDate5,
		CustomDate6,
		CustomDate7,
		CustomDate8,
		CustomDate9,
		CustomOption1,
		CustomOption2,
		CustomOption3,
		CustomOption4,
		CustomOption5,
		CustomOption6,
		CustomOption7,
		CustomOption8,
		CustomOption9,
		CustomValue1,
		CustomValue2,
		CustomValue3,
		CustomValue4,
		CustomValue5,
		CustomValue6,
		CustomValue7,
		CustomValue8,
		CustomValue9,
		CustomText1,
		CustomText2,
		CustomText3,
		CustomText4,
		CustomText5,
		BlanketSif,
		LetterDeliveryMethod,
		IsPrincipleCust,
		InvShowOther,
		AcknowledgeNewBiz,
		DefaultInterest,
		CollectorFeeSchedule,
		CbrAccountType,
		CbrCreditorClass,
		CbrOriginalCreditor,
		FreeDemandDays,
		FreeDemandBatchTypes,
		FeeCapAmount,
		FeeCapPercent,
		InvoiceReport,
		PermitSurcharges,
		Priority,
		UpdatedBy)
	VALUES(
		@Code,
		@Status,
		@CustomerName,
		@Street1,
		@Street2,
		@City,
		@State,
		@ZipCode,
		@Contact,
		@Phone,
		@LetterCode,
		@BadCheck,
		@BankCode,
		@BankId,
		@SalesmanCode,
		@SifInfo,
		@WorkInfo,
		@MiscInfo,
		@InvoiceType,
		@InvoiceFreq,
		@InvoiceSort,
		@InvoiceMethod,
		@FaxNumber,
		@AmtDueClient,
		@COB,
		@RemitMethod,
		@CustGroup,
		@CheckHoldDays,
		@InvShowRcvd,
		@InvShowBal,
		@CCostPct,
		@CCostBucket,
		@FeeSchedule,
		@LegalFeeSchedule,
		@IsPodCust,
		@Email,
		@ShowReverseOfDate,
		@AlphaCode,
		@Sweep,
		@SweepDays,
		@SweepDaysPaid,
		@SweepMinBalance,
		@SweepDesk,
		@DefaultDesk,
		@CustomDate1,
		@CustomDate2,
		@CustomDate3,
		@CustomDate4,
		@CustomDate5,
		@CustomDate6,
		@CustomDate7,
		@CustomDate8,
		@CustomDate9,
		@CustomOption1,
		@CustomOption2,
		@CustomOption3,
		@CustomOption4,
		@CustomOption5,
		@CustomOption6,
		@CustomOption7,
		@CustomOption8,
		@CustomOption9,
		@CustomValue1,
		@CustomValue2,
		@CustomValue3,
		@CustomValue4,
		@CustomValue5,
		@CustomValue6,
		@CustomValue7,
		@CustomValue8,
		@CustomValue9,
		@CustomText1,
		@CustomText2,
		@CustomText3,
		@CustomText4,
		@CustomText5,
		@BlanketSif,
		@LetterDeliveryMethod,
		@IsPrincipleCust,
		@InvShowOther,
		@AcknowledgeNewBiz,
		@DefaultInterest,
		@CollectorFeeSchedule,
		@CbrAccountType,
		@CbrCreditorClass,
		@CbrOriginalCreditor,
		@FreeDemandDays,
		@FreeDemandBatchTypes,
		@FeeCapAmount,
		@FeeCapPercent,
		@InvoiceReport,
		@PermitSurcharge,
		@Priority,
		@LatitudeUser)

	SET @CustomerID = SCOPE_IDENTITY()

    IF (@@error!=0)
    BEGIN
        RAISERROR  ('20001',16,1,'sp_Customer_Insert: Cannot insert into Customer table ')
        ROLLBACK TRAN
        RETURN(1)
    END
    COMMIT TRAN
GO
