SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
/******************************************************************************************
*	Change History:
*		08/06/2009-	KAR Modified @CITY param to be varchar(30) to match schema change.
*		01/12/2010- KAR Modified such that ShouldQueue is NOT updated.
*******************************************************************************************/
CREATE   procedure [dbo].[Lib_Update_master]
(
      @NUMBER   int,
      @LINK   int,
      @DESK   varchar (10),
      @NAME   varchar (60),
      @STREET1   varchar (30),
      @STREET2   varchar (30),
      @CITY   varchar (30),
      @STATE   varchar (3),
      @ZIPCODE   varchar (10),
      @CTL   varchar (3),
      @OTHER   varchar (30),
      @MR   varchar (1),
      @ACCOUNT   varchar (30),
      @HOMEPHONE   varchar (30),
      @WORKPHONE   varchar (30),
      @SPECIALNOTE   varchar (75),
      @RECEIVED   datetime,
      @CLOSED   datetime,
      @RETURNED   datetime,
      @LASTPAID   datetime,
      @LASTPAIDAMT   money,
      @LASTINTEREST   datetime,
      @INTERESTRATE   money,
      @WORKED   datetime,
      @USERDATE1   datetime,
      @USERDATE2   datetime,
      @USERDATE3   datetime,
      @CONTACTED   datetime,
      @STATUS   varchar (5),
      @CUSTOMER   varchar (7),
      @SSN   varchar (15),
      @ORIGINAL   money,
      @ORIGINAL1   money,
      @ORIGINAL2   money,
      @ORIGINAL3   money,
      @ORIGINAL4   money,
      @ORIGINAL5   money,
      @ORIGINAL6   money,
      @ORIGINAL7   money,
      @ORIGINAL8   money,
      @ORIGINAL9   money,
      @ORIGINAL10   money,
      @ACCRUED2   money,
      @ACCRUED10   money,
      @PAID   money,
      @PAID1   money,
      @PAID2   money,
      @PAID3   money,
      @PAID4   money,
      @PAID5   money,
      @PAID6   money,
      @PAID7   money,
      @PAID8   money,
      @PAID9   money,
      @PAID10   money,
      @CURRENT0   money,
      @CURRENT1   money,
      @CURRENT2   money,
      @CURRENT3   money,
      @CURRENT4   money,
      @CURRENT5   money,
      @CURRENT6   money,
      @CURRENT7   money,
      @CURRENT8   money,
      @CURRENT9   money,
      @CURRENT10   money,
      @ATTORNEY   varchar (5),
      @ASSIGNEDATTORNEY   datetime,
      @PROMAMT   money,
      @PROMDUE   datetime,
      @SIFPCT   money,
      @QUEUE   varchar (26),
      @QFLAG   varchar (1),
      @QDATE   varchar (8),
      @QLEVEL   varchar (3),
      @QTIME   varchar (4),
      @EXTRACODES   varchar (40),
      @SALARY   money,
      @FEECODE   varchar (30),
      @CLIDLC   datetime,
      @CLIDLP   datetime,
      @SEQ   int,
      @PSEQ   int,
      @BRANCH   varchar (5),
      @FINDERS   datetime,
      @COMPLETE1   datetime,
      @COMPLETE2   datetime,
      @DESK1   varchar (10),
      @DESK2   varchar (10),
      @FULL0   datetime,
      @TOTALVIEWED   int,
      @TOTALWORKED   int,
      @TOTALCONTACTED   int,
      @NSF   varchar (1),
      @HASBIGNOTE   varchar (1),
      @FIRSTDESK   varchar (10),
      @FIRSTRECEIVED   datetime,
      @AGENCYFLAG   int,
      @AGENCYCODE   varchar (5),
      @FEESCHEDULE   varchar (5),
      @CUSTDIVISION   varchar (15),
      @CUSTDISTRICT   varchar (15),
      @CUSTBRANCH   varchar (15),
      @DELINQUENCYDATE   datetime,
      @CURRENCYTYPE   varchar (20),
      @DOB   datetime,
      @SYSMONTH   int,
      @SYSYEAR   int,
      @DMDATESTAMP   varchar (10),
      @ID1   varchar (40),
      @ID2   varchar (40),
      @PURCHASEDPORTFOLIO   varchar (50),
      @SOLDPORTFOLIO   varchar (50),
      @ORIGINALCREDITOR   varchar (50),
      @ATTORNEYID   int,
      @BPDATE   datetime,
      @NSFDATE   datetime,
      @CONTRACTDATE   datetime,
      @CHARGEOFFDATE   datetime,
      @SHOULDQUEUE   bit,
      @RESTRICTEDACCESS   bit,
      @LINKDRIVER   bit,
      @SCORE   int,
      @SALESMAN1ID   int,
      @SALESMAN2ID   int,
      @SALESMAN3ID   int,
      @AIMAGENCY   int,
      @AIMASSIGNED   datetime,
	  @CBREXTENDDAYS int,
	  @CBRPREVENT bit,
   	  @CBROVERRIDE bit,
	  @CBREXCEPTION smallint,
	  @CLIALC money,
	  @CLIALP money,
	  @VIEWED   datetime = NULL,
      @QUEUEHOLD   datetime = NULL,
      @SECURED   bit = NULL,
      @PREVIOUSCREDITOR   varchar (50) = NULL,
      @STATUTEDATE   datetime = NULL,
      @ATTORNEYLAWLIST   varchar (5) = NULL,
      @ATTORNEYSTATUS   varchar (15) = NULL,
      @CLASSOFBUSINESS   varchar (5) = NULL,
      @CLAIMTYPE   varchar (5) = NULL,
      @ATTORNEYACCOUNTID   varchar (30) = NULL,
      @INTERESTBUCKETS   int = NULL,
      @BLANKETSIFOVERRIDE   float = NULL,
      @ARCHIVED   datetime  = NULL,
	  @EXCHANGEBATCHID int = NULL
      
)
as
begin


update dbo.master set
      LINK = @LINK,
      DESK = @DESK,
      NAME = @NAME,
      STREET1 = @STREET1,
      STREET2 = @STREET2,
      CITY = @CITY,
      STATE = @STATE,
      ZIPCODE = @ZIPCODE,
      CTL = @CTL,
      OTHER = @OTHER,
      MR = @MR,
      ACCOUNT = @ACCOUNT,
      HOMEPHONE = dbo.stripnondigits(@HOMEPHONE),
      WORKPHONE = dbo.stripnondigits(@WORKPHONE),
      SPECIALNOTE = @SPECIALNOTE,
      RECEIVED = @RECEIVED,
      CLOSED = @CLOSED,
      RETURNED = @RETURNED,
      LASTPAID = @LASTPAID,
      LASTPAIDAMT = @LASTPAIDAMT,
      LASTINTEREST = @LASTINTEREST,
      INTERESTRATE = @INTERESTRATE,
      WORKED = @WORKED,
      USERDATE1 = @USERDATE1,
      USERDATE2 = @USERDATE2,
      USERDATE3 = @USERDATE3,
      CONTACTED = @CONTACTED,
      STATUS = @STATUS,
      CUSTOMER = @CUSTOMER,
      SSN = @SSN,
      ORIGINAL = @ORIGINAL,
      ORIGINAL1 = @ORIGINAL1,
      ORIGINAL2 = @ORIGINAL2,
      ORIGINAL3 = @ORIGINAL3,
      ORIGINAL4 = @ORIGINAL4,
      ORIGINAL5 = @ORIGINAL5,
      ORIGINAL6 = @ORIGINAL6,
      ORIGINAL7 = @ORIGINAL7,
      ORIGINAL8 = @ORIGINAL8,
      ORIGINAL9 = @ORIGINAL9,
      ORIGINAL10 = @ORIGINAL10,
      ACCRUED2 = @ACCRUED2,
      ACCRUED10 = @ACCRUED10,
      PAID = @PAID,
      PAID1 = @PAID1,
      PAID2 = @PAID2,
      PAID3 = @PAID3,
      PAID4 = @PAID4,
      PAID5 = @PAID5,
      PAID6 = @PAID6,
      PAID7 = @PAID7,
      PAID8 = @PAID8,
      PAID9 = @PAID9,
      PAID10 = @PAID10,
      CURRENT0 = @CURRENT0,
      CURRENT1 = @CURRENT1,
      CURRENT2 = @CURRENT2,
      CURRENT3 = @CURRENT3,
      CURRENT4 = @CURRENT4,
      CURRENT5 = @CURRENT5,
      CURRENT6 = @CURRENT6,
      CURRENT7 = @CURRENT7,
      CURRENT8 = @CURRENT8,
      CURRENT9 = @CURRENT9,
      CURRENT10 = @CURRENT10,
      ATTORNEY = @ATTORNEY,
      ASSIGNEDATTORNEY = @ASSIGNEDATTORNEY,
      PROMAMT = @PROMAMT,
      PROMDUE = @PROMDUE,
      SIFPCT = @SIFPCT,
      QUEUE = @QUEUE,
      QFLAG = @QFLAG,
      QDATE = @QDATE,
      QLEVEL = @QLEVEL,
      QTIME = @QTIME,
      EXTRACODES = @EXTRACODES,
      SALARY = @SALARY,
      FEECODE = @FEECODE,
      CLIDLC = @CLIDLC,
      CLIDLP = @CLIDLP,
      SEQ = @SEQ,
      PSEQ = @PSEQ,
      BRANCH = @BRANCH,
      FINDERS = @FINDERS,
      COMPLETE1 = @COMPLETE1,
      COMPLETE2 = @COMPLETE2,
      DESK1 = @DESK1,
      DESK2 = @DESK2,
      FULL0 = @FULL0,
      TOTALVIEWED = @TOTALVIEWED,
      TOTALWORKED = @TOTALWORKED,
      TOTALCONTACTED = @TOTALCONTACTED,
      NSF = @NSF,
      HASBIGNOTE = @HASBIGNOTE,
      FIRSTDESK = @FIRSTDESK,
      FIRSTRECEIVED = @FIRSTRECEIVED,
      AGENCYFLAG = @AGENCYFLAG,
      AGENCYCODE = @AGENCYCODE,
      FEESCHEDULE = @FEESCHEDULE,
      CUSTDIVISION = @CUSTDIVISION,
      CUSTDISTRICT = @CUSTDISTRICT,
      CUSTBRANCH = @CUSTBRANCH,
      DELINQUENCYDATE = @DELINQUENCYDATE,
      CURRENCYTYPE = @CURRENCYTYPE,
      DOB = @DOB,
      SYSMONTH = @SYSMONTH,
      SYSYEAR = @SYSYEAR,
      DMDATESTAMP = @DMDATESTAMP,
      ID1 = @ID1,
      ID2 = @ID2,
      PURCHASEDPORTFOLIO = @PURCHASEDPORTFOLIO,
      SOLDPORTFOLIO = @SOLDPORTFOLIO,
      ORIGINALCREDITOR = @ORIGINALCREDITOR,
      ATTORNEYID = @ATTORNEYID,
      BPDATE = @BPDATE,
      NSFDATE = @NSFDATE,
      CONTRACTDATE = @CONTRACTDATE,
      CHARGEOFFDATE = @CHARGEOFFDATE,
      --SHOULDQUEUE = @SHOULDQUEUE,
	  --SHOULDQUEUE = 1,
      RESTRICTEDACCESS = @RESTRICTEDACCESS,
      LINKDRIVER = @LINKDRIVER,
      SCORE = @SCORE ,
	  CBREXTENDDAYS = @CBREXTENDDAYS ,
	  CBRPREVENT = @CBRPREVENT ,
	  CBROVERRIDE = @CBROVERRIDE ,
	  CBREXCEPTION = @CBREXCEPTION ,
      CLIALC = @CLIALC ,
  	  CLIALP = @CLIALP ,
	  VIEWED = ISNULL(@VIEWED,VIEWED),
      QUEUEHOLD = ISNULL(@QUEUEHOLD,QUEUEHOLD),
      SECURED = ISNULL(@SECURED,SECURED),
      PREVIOUSCREDITOR = ISNULL(@PREVIOUSCREDITOR,     PREVIOUSCREDITOR),
      STATUTEDATE = ISNULL(@STATUTEDATE,			   STATUTEDATE),
      ATTORNEYLAWLIST = ISNULL(@ATTORNEYLAWLIST,	   ATTORNEYLAWLIST),
      ATTORNEYSTATUS = ISNULL(@ATTORNEYSTATUS,		   ATTORNEYSTATUS ),
      CLASSOFBUSINESS = ISNULL(@CLASSOFBUSINESS,	   CLASSOFBUSINESS ),
      CLAIMTYPE = ISNULL(@CLAIMTYPE,				   CLAIMTYPE ),
      ATTORNEYACCOUNTID = ISNULL(@ATTORNEYACCOUNTID,   ATTORNEYACCOUNTID), 
      INTERESTBUCKETS = ISNULL(@INTERESTBUCKETS,	   INTERESTBUCKETS ), 
      BLANKETSIFOVERRIDE = ISNULL(@BLANKETSIFOVERRIDE,   BLANKETSIFOVERRIDE),
      ARCHIVED = ISNULL(@ARCHIVED,					   ARCHIVED),
	  EXCHANGEBATCHID = @EXCHANGEBATCHID

where NUMBER = @NUMBER

end
GO
