SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- =============================================
-- Author:		Brian G Meehan
-- Create date: 11/04/2021
-- Description:	Create new Placement file with acct id in all records
-- =============================================
CREATE PROCEDURE [dbo].[Custom_Sallie_Mae_Post_Export_Placements] 
	-- Add the parameters for the stored procedure here
	
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

    -- Insert statements for procedure here
	--Get 100 Record
SELECT csmpai.RecordID, csmpai.ARACID, csmpai.ARACCLACCT, csmpai.ARACVENDID, csmpai.REQUIREACK, csmpai.PLACEMENTSTRATEGYNAME, csmpai.ARRELPHASE, csmpai.ARACSRVDTE, csmpai.ARACCHGOFFDTE, csmpai.ARLOANORIGAMT, 
CASE WHEN csmpai.AFACBCURBALPRIN = '' THEN '0.00' ELSE csmpai.AFACBCURBALPRIN  END AS AFACBCURBALPRIN, 
CASE WHEN csmpai.AFACBCURBALINT = '' THEN '0.00'  ELSE csmpai.AFACBCURBALINT END AS AFACBCURBALINT,
CASE WHEN csmpai.AFACBCURBALAIN = '' THEN '0.00' ELSE csmpai.AFACBCURBALAIN END AS AFACBCURBALAIN,
CASE WHEN csmpai.AFACBCURBALPJI = '' THEN '0.00' ELSE csmpai.AFACBCURBALPJI END AS AFACBCURBALPJI,
CASE WHEN csmpai.AFACBCURBALOTHR = '' THEN '0.00' ELSE csmpai.AFACBCURBALOTHR END AS AFACBCURBALOTHR,
CASE WHEN csmpai.AFACBCURBALPNLTY = '' THEN '0.00' ELSE csmpai.AFACBCURBALPNLTY END AS AFACBCURBALPNLTY,
CASE WHEN csmpai.AFACBCURBALCCAGY = '' THEN '0.00' ELSE csmpai.AFACBCURBALCCAGY END AS AFACBCURBALCCAGY,
CASE WHEN csmpai.AFACBCURBALCOLL = '' THEN '0.00' ELSE csmpai.AFACBCURBALCOLL END AS AFACBCURBALCOLL,
CASE WHEN csmpai.AFACBCURBALFBFEE = '' THEN '0.00' ELSE csmpai.AFACBCURBALFBFEE END AS AFACBCURBALFBFEE,
CASE WHEN csmpai.AFACBCURBALMS1 = '' THEN '0.00' ELSE csmpai.AFACBCURBALMS1 END AS AFACBCURBALMS1,
csmpai.AFACINTRATE, 
csmpai.AFACINTHRUDT, csmpai.ALACCLCRID_ALCRNAME, csmpai.ZZACPGMCODE, csmpai.ZZACPGMPRODCODE, csmpai.ZZACSUBPGMCODE, csmpai.ARACCLCRLPYAMT, csmpai.ARACCLCRLPYDTE, csmpai.ARLOANSCHLID, csmpai.ARLOANSCHOOLNAME, csmpai.ARLOTIREGIONCODE, 
csmpai.FSACLNTERM, csmpai.FSACNBRCTDNSF, csmpai.FSACNBRNSF, csmpai.ZZAC1098EFL, csmpai.ZZACAUTODEBIT, csmpai.ZZACAUTODEBITST, csmpai.ZZACAUTOPAYACT, csmpai.ZZACAUTOPAYDESG, csmpai.ZZACBNKOWNIND, csmpai.ZZACDRAWALAMT, csmpai.ZZACDRAWALDTE, 
csmpai.ZZACENROLLSTAT, csmpai.ZZACFDRCPPORM, csmpai.ZZACFORBMONTHS, csmpai.ZZACINTRATEDESC, csmpai.ZZACLASTNSFDTE, csmpai.ZZACLOMODFLAG, csmpai.ZZACORGLENDID, csmpai.ZZACOVRRBEGDTE, csmpai.ZZACOVRRENDDTE, csmpai.ZZACREAGEMODDTE, 
csmpai.ZZACRPYBEGDTE, csmpai.ZZACTITLE4CODE, csmpai.ZZACWRKOUTENDDTE, csmpai.ZZACWRKOUTFL, csmpai.ZZLO1STPMTDUEDTE, csmpai.ZZLOAPPRVDAMT, csmpai.ZZLOENROLLBEGIN, csmpai.ZZLOENROLLEND, csmpai.ZZLOGRADE, csmpai.ZZLOINTRMPMTAMT, 
csmpai.ZZLOINTRMPMTUPDDTE, csmpai.ZZLOPLDEPENDIND, csmpai.ZZLOPMTIND, csmpai.ZZLORPMTBEGDTE, csmpai.ZZLOSTEPUPTYPE, csmpai.ZZLOSTUDENTCIN, csmpai.ZZLOSTUDENTDEC, csmpai.ZZLOSTUDENTDIS, csmpai.ZZLOSTUDENTSSN, csmpai.ZZLOSTUDYCODE
FROM Custom_Sallie_Mae_Post_Account_Import csmpai WITH (NOLOCK)

--Get 110 Record
SELECT csmpai.RecordID, csmpai.ARACID, csmpai.ZZENCIN, csmpai.ARENSSN, csmpai.ARRELTYPID, csmpai.ARENLNM, csmpai.ARENFNM, csmpai.ARENMNM, csmpai.ARENBTHDTE, csmpai.ARENADR, csmpai.ARENUNT, csmpai.ARENCTY, csmpai.ARENST, 
csmpai.ARENZIP, csmpai.ARENCNTRY, csmpai.ZZENADR3, csmpai.ZZENADR4, csmpai.ZZENADRFLAG, csmpai.ZRENEMAIL, csmpai.ZZENEMFL, csmpai.ARENNUMDEBTS, csmpai.ZZENCITIENCD, csmpai.ZZENSEPDTE, csmpai.ZZENENTERMBEGIN, csmpai.ZZENENTERMEND, 
csmpai.ARENBNKRPT, csmpai.ARENLANG, csmpai.ARRELCONLVL, csmpai.ARRELLASTCTCDTE, csmpai.ARENDECEASED, csmpai.ZZENDISABLED, csmpai.ARENSCRAIDARSCRAACTIVE, csmpai.ARENSCRAIDARSCRAENDDTE, csmpai.ARENSCRAIDARSCRASTARTDTE, csmpai.ARATFIRM, 
csmpai.ARATFNM, csmpai.ARATLNM, csmpai.ARATSPEC, csmpai.ARATADR, csmpai.ARATADR2, csmpai.ARATCTY, csmpai.ARATST, csmpai.ARATZIP, csmpai.ARATPH, csmpai.ARATEMAIL, csmpai.ARATCONFNM, csmpai.ARATCONLNM
FROM Custom_Sallie_Mae_Post_Debtor_Import csmpai WITH (NOLOCK)

--Get 120 Record and add Account do the record from Debtor Table
SELECT DISTINCT ph.RecordID, deb.ARACID, ph.ZZENCIN, ph.ARRELTYPID, ph.ARPHPHONE, ph.ARPHTYPE, ph.ARPHMAPKEY, ph.ARPHWRONG, ph.ARPHBAD, ph.ARPHCEASE, deb.ARENSSN
FROM Custom_Sallie_Mae_Post_Phones_Import ph WITH (NOLOCK)
	 INNER JOIN Custom_Sallie_Mae_Post_Debtor_Import deb WITH (NOLOCK) ON ph.ZZENCIN = deb.ZZENCIN 

--Get 130 Record and add Account to the record from the Debtor Table
SELECT csmppi.RecordID, deb.ARACID, csmppi.ZZENCIN, csmppi.ARRELTYPID, csmppi.ARPOENAME, csmppi.ARPOEADR1, csmppi.ARPOEADR2, csmppi.ARPOECITY, csmppi.ARPOEST, csmppi.ARPOEZIP, csmppi.ARPOEACTIVE, csmppi.ARPOEBEST, 
csmppi.ARPHPHONEWRK, csmppi.ARPHPHONEBUS, csmppi.ARPOETYPE, csmppi.ARPOETITLE, csmppi.ARPOEHIREDATE, csmppi.ARPOETERMDATE, deb.ARENSSN
FROM Custom_Sallie_Mae_Post_POE_Import csmppi WITH (NOLOCK)
	INNER JOIN Custom_Sallie_Mae_Post_Debtor_Import deb WITH (NOLOCK) ON csmppi.ZZENCIN = deb.ZZENCIN

END
GO
