SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE procedure [dbo].[Lib_Insert_Insurance]
(
      @InsuranceId   int output,
      @NUMBER   int,
      @INSUREDNAME   varchar (50),
      @INSUREDSTREET1   varchar (50),
      @INSUREDSTREET2   varchar (50),
      @INSUREDCITY   varchar (50),
      @INSUREDSTATE   char (3),
      @INSUREDZIP   char (10),
      @INSUREDPHONE   char (20),
      @INSUREDBIRTHDAY   datetime,
      @INSUREDSEX   char (1),
      @INSUREDEMPLOYER   varchar (50),
      @AUTHPMTTOPROVIDOR   bit,
      @ACCEPTASSIGNMENT   bit,
      @EMPLOYERHEALTHPLAN   varchar (50),
      @POLICYNUMBER   varchar (50),
      @PATIENTRELATIONTOINSURED   varchar (50),
      @PROGRAM   varchar (50),
      @GROUPNUMBER   varchar (50),
      @GROUPNAME   varchar (50),
      @CARRIERNAME   varchar (100),
      @CARRIERSTREET1   varchar (50),
      @CARRIERSTREET2   varchar (50),
      @CARRIERCITY   varchar (50),
      @CARRIERSTATE   char (3),
      @CARRIERZIP   char (10),
      @CARRIERDOCPROVIDERNUMBER   varchar (30),
      @CARRIERREFDOCPROVIDERNUMBER   varchar (30),
      @ADDITIONALINFO   varchar (5000),
      @DATECREATED   datetime,
      @DATEUPDATED   datetime,
      @UPDATECHECKSUM   varchar (10),
      @UPDATEDBY   int,
      @COORDINATIONNUMBER VARCHAR(50) = NULL,
      @INSUREDSSN VARCHAR(20) = NULL,
      @INSUREDWORKPHONE VARCHAR(15) = NULL
)
as
begin


	if  exists(select * from sysobjects o join syscolumns c on c.id = o.id where o.name = 'Insurance' and o.xtype = 'U' and c.name = 'INSUREDWORKPHONE')
	BEGIN
		insert into dbo.Insurance
		(
			  
			  [NUMBER],
			  [INSUREDNAME],
			  [INSUREDSTREET1],
			  [INSUREDSTREET2],
			  [INSUREDCITY],
			  [INSUREDSTATE],
			  [INSUREDZIP],
			  [INSUREDPHONE],
			  [INSUREDBIRTHDAY],
			  [INSUREDSEX],
			  [INSUREDEMPLOYER],
			  [AUTHPMTTOPROVIDOR],
			  [ACCEPTASSIGNMENT],
			  [EMPLOYERHEALTHPLAN],
			  [POLICYNUMBER],
			  [PATIENTRELATIONTOINSURED],
			  [PROGRAM],
			  [GROUPNUMBER],
			  [GROUPNAME],
			  [CARRIERNAME],
			  [CARRIERSTREET1],
			  [CARRIERSTREET2],
			  [CARRIERCITY],
			  [CARRIERSTATE],
			  [CARRIERZIP],
			  [CARRIERDOCPROVIDERNUMBER],
			  [CARRIERREFDOCPROVIDERNUMBER],
			  [ADDITIONALINFO],
			  [DATECREATED],
			  [DATEUPDATED],
			  [UPDATECHECKSUM],
			  [UPDATEDBY],
			  [COORDINATIONNUMBER],
			  [INSUREDSSN],
			  [INSUREDWORKPHONE]
		)
		values
		(
			  @NUMBER,
			  @INSUREDNAME,
			  @INSUREDSTREET1,
			  @INSUREDSTREET2,
			  @INSUREDCITY,
			  @INSUREDSTATE,
			  @INSUREDZIP,
			  @INSUREDPHONE,
			  @INSUREDBIRTHDAY,
			  @INSUREDSEX,
			  @INSUREDEMPLOYER,
			  @AUTHPMTTOPROVIDOR,
			  @ACCEPTASSIGNMENT,
			  @EMPLOYERHEALTHPLAN,
			  @POLICYNUMBER,
			  @PATIENTRELATIONTOINSURED,
			  @PROGRAM,
			  @GROUPNUMBER,
			  @GROUPNAME,
			  @CARRIERNAME,
			  @CARRIERSTREET1,
			  @CARRIERSTREET2,
			  @CARRIERCITY,
			  @CARRIERSTATE,
			  @CARRIERZIP,
			  @CARRIERDOCPROVIDERNUMBER,
			  @CARRIERREFDOCPROVIDERNUMBER,
			  @ADDITIONALINFO,
			  @DATECREATED,
			  @DATEUPDATED,
			  CHECKSUM(GETDATE()),
			  @UPDATEDBY,
			  @COORDINATIONNUMBER,
			  @INSUREDSSN,
			  @INSUREDWORKPHONE
		)

		select @InsuranceId = SCOPE_IDENTITY()
	END
	ELSE
	BEGIN
		insert into dbo.Insurance
		(
			  
			  [NUMBER],
			  [INSUREDNAME],
			  [INSUREDSTREET1],
			  [INSUREDSTREET2],
			  [INSUREDCITY],
			  [INSUREDSTATE],
			  [INSUREDZIP],
			  [INSUREDPHONE],
			  [INSUREDBIRTHDAY],
			  [INSUREDSEX],
			  [INSUREDEMPLOYER],
			  [AUTHPMTTOPROVIDOR],
			  [ACCEPTASSIGNMENT],
			  [EMPLOYERHEALTHPLAN],
			  [POLICYNUMBER],
			  [PATIENTRELATIONTOINSURED],
			  [PROGRAM],
			  [GROUPNUMBER],
			  [GROUPNAME],
			  [CARRIERNAME],
			  [CARRIERSTREET1],
			  [CARRIERSTREET2],
			  [CARRIERCITY],
			  [CARRIERSTATE],
			  [CARRIERZIP],
			  [CARRIERDOCPROVIDERNUMBER],
			  [CARRIERREFDOCPROVIDERNUMBER],
			  [ADDITIONALINFO],
			  [DATECREATED],
			  [DATEUPDATED],
			  [UPDATECHECKSUM],
			  [UPDATEDBY]
		)
		values
		(
			  @NUMBER,
			  @INSUREDNAME,
			  @INSUREDSTREET1,
			  @INSUREDSTREET2,
			  @INSUREDCITY,
			  @INSUREDSTATE,
			  @INSUREDZIP,
			  @INSUREDPHONE,
			  @INSUREDBIRTHDAY,
			  @INSUREDSEX,
			  @INSUREDEMPLOYER,
			  @AUTHPMTTOPROVIDOR,
			  @ACCEPTASSIGNMENT,
			  @EMPLOYERHEALTHPLAN,
			  @POLICYNUMBER,
			  @PATIENTRELATIONTOINSURED,
			  @PROGRAM,
			  @GROUPNUMBER,
			  @GROUPNAME,
			  @CARRIERNAME,
			  @CARRIERSTREET1,
			  @CARRIERSTREET2,
			  @CARRIERCITY,
			  @CARRIERSTATE,
			  @CARRIERZIP,
			  @CARRIERDOCPROVIDERNUMBER,
			  @CARRIERREFDOCPROVIDERNUMBER,
			  @ADDITIONALINFO,
			  @DATECREATED,
			  @DATEUPDATED,
			  CHECKSUM(GETDATE()),
			  @UPDATEDBY
		)
		select @InsuranceId = SCOPE_IDENTITY()	
	END
end

GO
