SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
/****** Object:  Stored Procedure dbo.Lib_Insert_master    Script Date: 9/21/2005 5:13:33 PM ******/
/******************************************************************************************
*	Change History:
*		08/06/2009-	KAR Modified @CITY param to be varchar(30) to match schema change.
*******************************************************************************************/
CREATE          procedure [dbo].[Lib_Insert_master]
(
      @NUMBER   int,
      @LINK   int,
      @DESK   varchar (10),
      @NAME   varchar (60),
      @STREET1   varchar (30),
      @STREET2   varchar (30),
      @CITY   varchar (30),
      @STATE   varchar (3),
      @ZIPCODE   varchar (10),
      @CTL   varchar (3),
      @OTHER   varchar (30),
      @MR   varchar (1),
      @ACCOUNT   varchar (30),
      @HOMEPHONE   varchar (30),
      @WORKPHONE   varchar (30),
      @SPECIALNOTE   varchar (75),
      @RECEIVED   datetime,
      @CLOSED   datetime,
      @RETURNED   datetime,
      @LASTPAID   datetime,
      @LASTPAIDAMT   money,
      @LASTINTEREST   datetime,
      @INTERESTRATE   money,
      @WORKED   datetime,
      @USERDATE1   datetime,
      @USERDATE2   datetime,
      @USERDATE3   datetime,
      @CONTACTED   datetime,
      @STATUS   varchar (5),
      @CUSTOMER   varchar (7),
      @SSN   varchar (15),
      @ORIGINAL   money,
      @ORIGINAL1   money,
      @ORIGINAL2   money,
      @ORIGINAL3   money,
      @ORIGINAL4   money,
      @ORIGINAL5   money,
      @ORIGINAL6   money,
      @ORIGINAL7   money,
      @ORIGINAL8   money,
      @ORIGINAL9   money,
      @ORIGINAL10   money,
      @ACCRUED2   money,
      @ACCRUED10   money,
      @PAID   money,
      @PAID1   money,
      @PAID2   money,
      @PAID3   money,
      @PAID4   money,
      @PAID5   money,
      @PAID6   money,
      @PAID7   money,
      @PAID8   money,
      @PAID9   money,
      @PAID10   money,
      @CURRENT0   money,
      @CURRENT1   money,
      @CURRENT2   money,
      @CURRENT3   money,
      @CURRENT4   money,
      @CURRENT5   money,
      @CURRENT6   money,
      @CURRENT7   money,
      @CURRENT8   money,
      @CURRENT9   money,
      @CURRENT10   money,
      @ATTORNEY   varchar (5),
      @ASSIGNEDATTORNEY   datetime,
      @PROMAMT   money,
      @PROMDUE   datetime,
      @SIFPCT   money,
      @QUEUE   varchar (26),
      @QFLAG   varchar (1),
      @QDATE   varchar (8),
      @QLEVEL   varchar (3),
      @QTIME   varchar (4),
      @EXTRACODES   varchar (40),
      @SALARY   money,
      @FEECODE   varchar (30),
      @CLIDLC   datetime,
      @CLIDLP   datetime,
      @SEQ   int,
      @PSEQ   int,
      @BRANCH   varchar (5),
      @FINDERS   datetime,
      @COMPLETE1   datetime,
      @COMPLETE2   datetime,
      @DESK1   varchar (10),
      @DESK2   varchar (10),
      @FULL0   datetime,
      @TOTALVIEWED   int,
      @TOTALWORKED   int,
      @TOTALCONTACTED   int,
      @NSF   varchar (1),
      @HASBIGNOTE   varchar (1),
      @FIRSTDESK   varchar (10),
      @FIRSTRECEIVED   datetime,
      @AGENCYFLAG   int,
      @AGENCYCODE   varchar (5),
      @FEESCHEDULE   varchar (5),
      @CUSTDIVISION   varchar (15),
      @CUSTDISTRICT   varchar (15),
      @CUSTBRANCH   varchar (15),
      @DELINQUENCYDATE   datetime,
      @CURRENCYTYPE   varchar (20),
      @DOB   datetime,
      @SYSMONTH   int,
      @SYSYEAR   int,
      @DMDATESTAMP   varchar (10),
      @ID1   varchar (40),
      @ID2   varchar (40),
      @PURCHASEDPORTFOLIO   varchar (50),
      @SOLDPORTFOLIO   varchar (50),
      @ORIGINALCREDITOR   varchar (50),
      @ATTORNEYID   int,
      @BPDATE   datetime,
      @NSFDATE   datetime,
      @CONTRACTDATE   datetime,
      @CHARGEOFFDATE   datetime,
      @SHOULDQUEUE   bit,
      @RESTRICTEDACCESS   bit,
      @LINKDRIVER   bit,
      @SCORE   int,
      @SALESMAN1ID   int,
      @SALESMAN2ID   int,
      @SALESMAN3ID   int,
      @AIMAGENCY   int,
      @AIMASSIGNED   datetime,
	  @CBREXTENDDAYS int,
	  @CBRPREVENT bit,
	  @CBROVERRIDE bit,
	  @CBREXCEPTION smallint,
	  @CLIALC money,
	  @CLIALP money,
	  @VIEWED   datetime,
      @QUEUEHOLD   datetime,
      @SECURED   bit,
      @PREVIOUSCREDITOR   varchar (50),
      @STATUTEDATE   datetime,
      @ATTORNEYLAWLIST   varchar (5),
      @ATTORNEYSTATUS   varchar (15),
      @CLASSOFBUSINESS   varchar (5),
      @CLAIMTYPE   varchar (5),
      @ATTORNEYACCOUNTID   varchar (30),
      @INTERESTBUCKETS   int,
      @BLANKETSIFOVERRIDE   float,
      @ARCHIVED   datetime,
	  @EXCHANGEBATCHID int = NULL
)
as
begin

declare @sysmonth1 int, @sysyear1 int,@qmonth varchar(2),@qday varchar(2)
select @sysmonth1 = currentmonth, @sysyear1 = currentyear from controlfile
declare @currentqTime varchar(4), @currentqdate varchar(8)
select @currentqTime = cast(datepart(hh,getdate()) as char(2))+cast(datepart(mi,getdate()) as char(2))

select @currentqdate = dbo.makeqdate(getdate())

declare @defaultBranch varchar(30)
select @defaultbranch = branch from desk where code = @desk


if @INTERESTRATE is null or @interestrate = 0
	select @INTERESTRATE = defaultinterest from customer where customer = @customer

insert into dbo.master
(
      NUMBER,
      LINK,
      DESK,
      NAME,
      STREET1,
      STREET2,
      CITY,
      STATE,
      ZIPCODE,
      CTL,
      OTHER,
      MR,
      ACCOUNT,
      HOMEPHONE,
      WORKPHONE,
      SPECIALNOTE,
      RECEIVED,
      CLOSED,
      RETURNED,
      LASTPAID,
      LASTPAIDAMT,
      LASTINTEREST,
      INTERESTRATE,
      WORKED,
      USERDATE1,
      USERDATE2,
      USERDATE3,
      CONTACTED,
      STATUS,
      CUSTOMER,
      SSN,
      ORIGINAL,
      ORIGINAL1,
      ORIGINAL2,
      ORIGINAL3,
      ORIGINAL4,
      ORIGINAL5,
      ORIGINAL6,
      ORIGINAL7,
      ORIGINAL8,
      ORIGINAL9,
      ORIGINAL10,
      ACCRUED2,
      ACCRUED10,
      PAID,
      PAID1,
      PAID2,
      PAID3,
      PAID4,
      PAID5,
      PAID6,
      PAID7,
      PAID8,
      PAID9,
      PAID10,
      CURRENT0,
      CURRENT1,
      CURRENT2,
      CURRENT3,
      CURRENT4,
      CURRENT5,
      CURRENT6,
      CURRENT7,
      CURRENT8,
      CURRENT9,
      CURRENT10,
      ATTORNEY,
      ASSIGNEDATTORNEY,
      PROMAMT,
      PROMDUE,
      SIFPCT,
      QUEUE,
      QFLAG,
      QDATE,
      QLEVEL,
      QTIME,
      EXTRACODES,
      SALARY,
      FEECODE,
      CLIDLC,
      CLIDLP,
      SEQ,
      PSEQ,
      BRANCH,
      FINDERS,
      COMPLETE1,
      COMPLETE2,
      DESK1,
      DESK2,
      FULL0,
      TOTALVIEWED,
      TOTALWORKED,
      TOTALCONTACTED,
      NSF,
      HASBIGNOTE,
      FIRSTDESK,
      FIRSTRECEIVED,
      AGENCYFLAG,
      AGENCYCODE,
      FEESCHEDULE,
      CUSTDIVISION,
      CUSTDISTRICT,
      CUSTBRANCH,
      DELINQUENCYDATE,
      CURRENCYTYPE,
      DOB,
      SYSMONTH,
      SYSYEAR,
      DMDATESTAMP,
      ID1,
      ID2,
      PURCHASEDPORTFOLIO,
      SOLDPORTFOLIO,
      ORIGINALCREDITOR,
      ATTORNEYID,
      BPDATE,
      NSFDATE,
      CONTRACTDATE,
      CHARGEOFFDATE,
      SHOULDQUEUE,
      RESTRICTEDACCESS,
      LINKDRIVER,
      SCORE,
      SALESMAN1ID,
      SALESMAN2ID,
      SALESMAN3ID,
      AIMAGENCY,
      AIMASSIGNED,
	  CBREXTENDDAYS ,
	  CBRPREVENT ,
	  CBROVERRIDE ,
	  CBREXCEPTION ,
	  CLIALC ,
	  CLIALP ,
	  VIEWED,
      QUEUEHOLD,
      SECURED,
      PREVIOUSCREDITOR,
      STATUTEDATE,
      ATTORNEYLAWLIST,
      ATTORNEYSTATUS,
      CLASSOFBUSINESS,
      CLAIMTYPE,
      ATTORNEYACCOUNTID,
      INTERESTBUCKETS,
      BLANKETSIFOVERRIDE,
      ARCHIVED,
	  EXCHANGEBATCHID
)
values
(
      @NUMBER,
      @LINK,
      @DESK,
      ltrim(rtrim(left(@NAME,30))),
      @STREET1,
      @STREET2,
      @CITY,
      @STATE,
      @ZIPCODE,
      isnull(@CTL,'EXG'),
      isnull(@OTHER,''),
      isnull(@MR,'N'),
      @ACCOUNT,
      dbo.stripnondigits(@HOMEPHONE),
      dbo.stripnondigits(@WORKPHONE),
      @SPECIALNOTE,
      isnull(@RECEIVED,getdate()),
      @CLOSED,
      @RETURNED,
      @LASTPAID,
      isnull(@LASTPAIDAMT,0),
      @LASTINTEREST,
      isnull(@INTERESTRATE,0),
      @WORKED,
      @USERDATE1,
      @USERDATE2,
      @USERDATE3,
      @CONTACTED,
      isnull(@STATUS,'NEW'),
      @CUSTOMER,
      @SSN,
      isnull(@ORIGINAL,0),
      isnull(@ORIGINAL1,0),
      isnull(@ORIGINAL2,0),
      isnull(@ORIGINAL3,0),
      isnull(@ORIGINAL4,0),
      isnull(@ORIGINAL5,0),
      isnull(@ORIGINAL6,0),
      isnull(@ORIGINAL7,0),
      isnull(@ORIGINAL8,0),
      isnull(@ORIGINAL9,0),
      isnull(@ORIGINAL10,0),
      isnull(@ACCRUED2,0),
      isnull(@ACCRUED10,0),
      isnull(@PAID,0),
      isnull(@PAID1,0),
      isnull(@PAID2,0),
      isnull(@PAID3,0),
      isnull(@PAID4,0),
      isnull(@PAID5,0),
      isnull(@PAID6,0),
      isnull(@PAID7,0),
      isnull(@PAID8,0),
      isnull(@PAID9,0),
      isnull(@PAID10,0),
      isnull(@CURRENT0,0),
      isnull(@CURRENT1,0),
      isnull(@CURRENT2,0),
      isnull(@CURRENT3,0),
      isnull(@CURRENT4,0),
      isnull(@CURRENT5,0),
      isnull(@CURRENT6,0),
      isnull(@CURRENT7,0),
      isnull(@CURRENT8,0),
      isnull(@CURRENT9,0),
      isnull(@CURRENT10,0),
      @ATTORNEY,
      @ASSIGNEDATTORNEY,
      @PROMAMT,
      @PROMDUE,
      @SIFPCT,
      @QUEUE,
      isnull(@QFLAG,'1'),
      isnull(@QDATE,@currentqdate),
      isnull(@QLEVEL,'015'),
      isnull(@QTIME,'0000'),
      @EXTRACODES,
      @SALARY,
      @FEECODE,
      @CLIDLC,
      @CLIDLP,
      @SEQ,
      @PSEQ,
      isnull(@BRANCH,@defaultbranch),
      @FINDERS,
      @COMPLETE1,
      @COMPLETE2,
      @DESK1,
      @DESK2,
      @FULL0,
      @TOTALVIEWED,
      @TOTALWORKED,
      @TOTALCONTACTED,
      @NSF,
      @HASBIGNOTE,
      @FIRSTDESK,
      @FIRSTRECEIVED,
      @AGENCYFLAG,
      @AGENCYCODE,
      @FEESCHEDULE,
      @CUSTDIVISION,
      @CUSTDISTRICT,
      @CUSTBRANCH,
      @DELINQUENCYDATE,
      @CURRENCYTYPE,
      @DOB,
      isnull(@SYSMONTH,@sysmonth1),
      isnull(@SYSYEAR,@sysyear1),
      @DMDATESTAMP,
      @ID1,
      @ID2,
      CASE @PURCHASEDPORTFOLIO WHEN '0' THEN null ELSE @PURCHASEDPORTFOLIO END,
      CASE @SOLDPORTFOLIO WHEN '0' THEN null ELSE @SOLDPORTFOLIO END,
      @ORIGINALCREDITOR,
      @ATTORNEYID,
      @BPDATE,
      @NSFDATE,
      @CONTRACTDATE,
      @CHARGEOFFDATE,
      --isnull(@SHOULDQUEUE,1),
	  1,
      isnull(@RESTRICTEDACCESS,0),
      @LINKDRIVER,
      @SCORE,
      @SALESMAN1ID,
      @SALESMAN2ID,
      @SALESMAN3ID,
      @AIMAGENCY,
      @AIMASSIGNED,
	  @CBREXTENDDAYS ,
	  @CBRPREVENT ,
	  @CBROVERRIDE ,
	  @CBREXCEPTION ,
	  @CLIALC ,
	  @CLIALP ,
      @VIEWED,
      @QUEUEHOLD,
      @SECURED,
      @PREVIOUSCREDITOR,
      @STATUTEDATE,
      @ATTORNEYLAWLIST,
      @ATTORNEYSTATUS,
      @CLASSOFBUSINESS,
      @CLAIMTYPE,
      @ATTORNEYACCOUNTID,
      @INTERESTBUCKETS,
      @BLANKETSIFOVERRIDE,
      @ARCHIVED,
	  @EXCHANGEBATCHID
)

end
GO
