SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO




/*sp_CCustomer_Add */
CREATE  Procedure [dbo].[sp_CCustomer_Add]
@CCustomerID int OUTPUT,
@Customer varchar(7),
@Status varchar(8),
@SelectedFlag varchar(1),
@Name varchar(50),
@Street1 varchar(30),
@Street2 varchar(30),
@City varchar(20),
@State varchar(3),
@Zipcode varchar(10),
@Contact varchar(30),
@Phone varchar(20),
@Lettercode varchar(50),
@Penalty money,
@Badcheck money,
@Ctl varchar(3),
@Fees money,
@Collections money,
@Mtdnumberplaced float,
@Mtddollarsplaced money,
@Ytdnumberplaced float,
@Ytddollarsplaced money,
@Mtdpdcfees money,
@Mtdpdccollections money,
@Mtdfees money,
@Mtdcollections money,
@Ytdfees money,
@Ytdcollections money,
@Bankcode varchar(30),
@Attorneycode varchar(30),
@Salesmancode varchar(30),
@Sifinfo text,
@Workinfo text,
@Miscinfo text,
@Invoicetype varchar(20),
@Invoicefreq varchar(20),
@Invoicesort varchar(20),
@Invoicemethod varchar(20),
@Options varchar(50),
@Option1 varchar(50),
@Fax varchar(15),
@Half money,
@Close_ money,
@FaxNumber varchar(30),
@AutoRecallStatus varchar(60),
@AutoRecallDays int,
@AutoRecallFlag varchar(1),
@Locate money,
@SpecialCode varchar(20),
@CustomerGroup varchar(10),
@Full0 money,
@AmtDueClient smallint,
@Feecode2 varchar(30),
@Feedays int,
@Cob varchar(50),
@Company varchar(40),
@LastInvoiceAttempt datetime,
@RemitMethod varchar(5),
@ABARoutingNum varchar(9),
@BankAcctNum varchar(20),
@CustGroup varchar(7),
@CheckHoldDays smallint,
@InvShowRcvd bit,
@InvShowBal bit,
@CCostPct real,
@CCostBucket tinyint,
@FeeSchedule varchar(5),
@IsPODCust bit,
@CBRRptType varchar(50),
@CBRMinBal money,
@CBRWaitDays int,
@UseEquifax bit,
@UseTransUnion bit,
@UseExperian bit,
@UseInnovis bit,
@EMail varchar(30),
@CBRClass varchar(40),
@ShowReverseOfDate bit,
@OnlineCheckFee money,
@AlphaCode varchar(50),
@Sweep bit,
@SweepDays int,
@SweepDaysPaid int,
@SweepMinBalance money,
@SweepDesk varchar(10),
@DefaultDesk varchar(10),
@FaxID varchar(50),
@LetterDeliveryMethod int
AS

INSERT INTO Customer
(
customer,
status,
SelectedFlag,
Name,
Street1,
Street2,
City,
State,
Zipcode,
Contact,
phone,
lettercode,
penalty,
badcheck,
ctl,
fees,
collections,
mtdnumberplaced,
mtddollarsplaced,
ytdnumberplaced,
ytddollarsplaced,
mtdpdcfees,
mtdpdccollections,
mtdfees,
mtdcollections,
ytdfees,
ytdcollections,
bankcode,
attorneycode,
salesmancode,
sifinfo,
workinfo,
miscinfo,
invoicetype,
invoicefreq,
invoicesort,
invoicemethod,
options,
option1,
fax,
Half,
Close_,
FaxNumber,
AutoRecallStatus,
AutoRecallDays,
AutoRecallFlag,
locate,
SpecialCode,
CustomerGroup,
Full0,
AmtDueClient,
feecode2,
feedays,
cob,
company,
LastInvoiceAttempt,
RemitMethod,
ABARoutingNum,
BankAcctNum,
CustGroup,
CheckHoldDays,
InvShowRcvd,
InvShowBal,
CCostPct,
CCostBucket,
FeeSchedule,
IsPODCust,
CBRRptType,
CBRMinBal,
CBRWaitDays,
UseEquifax,
UseTransUnion,
UseExperian,
UseInnovis,
eMail,
CBRClass,
ShowReverseOfDate,
OnlineCheckFee,
AlphaCode,
Sweep,
SweepDays,
SweepDaysPaid,
SweepMinBalance,
SweepDesk,
DefaultDesk,
FaxID,
LetterDeliveryMethod
)
VALUES
(
@Customer,
@Status,
@SelectedFlag,
@Name,
@Street1,
@Street2,
@City,
@State,
@Zipcode,
@Contact,
@Phone,
@Lettercode,
@Penalty,
@Badcheck,
@Ctl,
@Fees,
@Collections,
@Mtdnumberplaced,
@Mtddollarsplaced,
@Ytdnumberplaced,
@Ytddollarsplaced,
@Mtdpdcfees,
@Mtdpdccollections,
@Mtdfees,
@Mtdcollections,
@Ytdfees,
@Ytdcollections,
@Bankcode,
@Attorneycode,
@Salesmancode,
@Sifinfo,
@Workinfo,
@Miscinfo,
@Invoicetype,
@Invoicefreq,
@Invoicesort,
@Invoicemethod,
@Options,
@Option1,
@Fax,
@Half,
@Close_,
@FaxNumber,
@AutoRecallStatus,
@AutoRecallDays,
@AutoRecallFlag,
@Locate,
@SpecialCode,
@CustomerGroup,
@Full0,
@AmtDueClient,
@Feecode2,
@Feedays,
@Cob,
@Company,
@LastInvoiceAttempt,
@RemitMethod,
@ABARoutingNum,
@BankAcctNum,
@CustGroup,

@CheckHoldDays,
@InvShowRcvd,
@InvShowBal,
@CCostPct,
@CCostBucket,
@FeeSchedule,
@IsPODCust,
@CBRRptType,
@CBRMinBal,
@CBRWaitDays,
@UseEquifax,
@UseTransUnion,
@UseExperian,
@UseInnovis,
@EMail,
@CBRClass,
@ShowReverseOfDate,
@OnlineCheckFee,
@AlphaCode,
@Sweep,
@SweepDays,
@SweepDaysPaid,
@SweepMinBalance,
@SweepDesk,
@DefaultDesk,
@FaxID,
@LetterDeliveryMethod
)

SET @CCustomerID = SCOPE_IDENTITY()



GO
