SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[fusion_FixServicesCPETable]
AS
BEGIN
	if exists( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME='AddressDateReported' and TABLE_NAME='Services_CPE' AND DATA_TYPE='varchar')
		ALTER TABLE Services_CPE ALTER COLUMN AddressDateReported datetime
	if exists( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME='PreviousAddressDateReported' and TABLE_NAME='Services_CPE' AND DATA_TYPE='varchar')
		ALTER TABLE Services_CPE ALTER COLUMN PreviousAddressDateReported datetime
	if exists( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME='DateOfBirth' and TABLE_NAME='Services_CPE' AND DATA_TYPE='varchar')
		ALTER TABLE Services_CPE ALTER COLUMN DateOfBirth datetime
	if exists(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME='City' and TABLE_NAME='Services_CPE' AND DATA_TYPE='varchar' AND CHARACTER_MAXIMUM_LENGTH < 50 )
		ALTER TABLE Services_CPE ALTER COLUMN City varchar(50)
	if exists (Select * from INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME='LastName' and TABLE_NAME='Services_CPE' and CHARACTER_MAXIMUM_LENGTH<50)
		ALTER TABLE Services_CPE ALTER COLUMN LastName varchar(50)
	if exists (Select * from INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME='MiddleName' and TABLE_NAME='Services_CPE' and CHARACTER_MAXIMUM_LENGTH<50)
		ALTER TABLE Services_CPE ALTER COLUMN MiddleName varchar(50)
	if exists (Select * from INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME='Firstname' and TABLE_NAME='Services_CPE' and CHARACTER_MAXIMUM_LENGTH<50)
		ALTER TABLE Services_CPE ALTER COLUMN FirstName varchar(50)
	if exists (Select * from INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME='MaternalName' and TABLE_NAME='Services_CPE' and CHARACTER_MAXIMUM_LENGTH<50)
		ALTER TABLE Services_CPE ALTER COLUMN MaternalName varchar(50)
	if exists (Select * from INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME='AliasName' and TABLE_NAME='Services_CPE' and CHARACTER_MAXIMUM_LENGTH<50)
		ALTER TABLE Services_CPE ALTER COLUMN AliasName varchar(50)
END
GO
