SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


create procedure [dbo].[Lib_Update_payhistory]
(
      @NUMBER   int,
      @SEQ   int,
      @BATCHTYPE   varchar (3),
      @MATCHED   varchar (1),
      @CTL   varchar (3),
      @CUSTOMER   varchar (7),
      @SORTDATA   varchar (30),
      @PAYTYPE   varchar (30),
      @PAYMETHOD   varchar (30),
      @SYSTEMMONTH   int,
      @SYSTEMYEAR   int,
      @ENTERED   datetime,
      @DESK   varchar (10),
      @CHECKNBR   varchar (10),
      @INVOICED   datetime,
      @INVOICESORT   varchar (2),
      @INVOICETYPE   varchar (2),
      @INVOICEPAYTYPE   real,
      @COMMENT   char (30),
      @DATEPAID   datetime,
      @TOTALPAID   money,
      @PAID1   money,
      @PAID2   money,
      @PAID3   money,
      @PAID4   money,
      @PAID5   money,
      @PAID6   money,
      @PAID7   money,
      @PAID8   money,
      @PAID9   money,
      @PAID10   money,
      @FEE1   money,
      @FEE2   money,
      @FEE3   money,
      @FEE4   money,
      @FEE5   money,
      @FEE6   money,
      @FEE7   money,
      @FEE8   money,
      @FEE9   money,
      @FEE10   money,
      @BALANCE   money,
      @BALANCE1   money,
      @BALANCE3   money,
      @BALANCE4   money,
      @BALANCE5   money,
      @BALANCE6   money,
      @BALANCE7   money,
      @BALANCE8   money,
      @BALANCE9   money,
      @BALANCE10   money,
      @BALANCE2   money,
      @BATCHNUMBER   float,
      @UID   int,
      @INVOICE   int,
      @INVOICEFLAGS   varchar (10),
      @OVERPAIDAMT   money,
      @FORWARDEEFEE   money,
      @REVERSEOFUID   int,
      @ACCRUEDSURCHARGE   money,
      @TRANSCOST   money,
      @TAX   money,
      @ATTORNEYID   int,
      @COLLECTORFEE   money,
      @PAIDENTIFIER   varchar (30),
      @AIMAGENCYID   int,
      @AIMDUEAGENCY   money,
      @AIMAGENCYFEE   money
)
as
begin


update dbo.payhistory set
      SEQ = @SEQ,
      BATCHTYPE = @BATCHTYPE,
      MATCHED = @MATCHED,
      CTL = @CTL,
      CUSTOMER = @CUSTOMER,
      SORTDATA = @SORTDATA,
      PAYTYPE = @PAYTYPE,
      PAYMETHOD = @PAYMETHOD,
      SYSTEMMONTH = @SYSTEMMONTH,
      SYSTEMYEAR = @SYSTEMYEAR,
      ENTERED = @ENTERED,
      DESK = @DESK,
      CHECKNBR = @CHECKNBR,
      INVOICED = @INVOICED,
      INVOICESORT = @INVOICESORT,
      INVOICETYPE = @INVOICETYPE,
      INVOICEPAYTYPE = @INVOICEPAYTYPE,
      COMMENT = @COMMENT,
      DATEPAID = @DATEPAID,
      TOTALPAID = @TOTALPAID,
      PAID1 = @PAID1,
      PAID2 = @PAID2,
      PAID3 = @PAID3,
      PAID4 = @PAID4,
      PAID5 = @PAID5,
      PAID6 = @PAID6,
      PAID7 = @PAID7,
      PAID8 = @PAID8,
      PAID9 = @PAID9,
      PAID10 = @PAID10,
      FEE1 = @FEE1,
      FEE2 = @FEE2,
      FEE3 = @FEE3,
      FEE4 = @FEE4,
      FEE5 = @FEE5,
      FEE6 = @FEE6,
      FEE7 = @FEE7,
      FEE8 = @FEE8,
      FEE9 = @FEE9,
      FEE10 = @FEE10,
      BALANCE = @BALANCE,
      BALANCE1 = @BALANCE1,
      BALANCE3 = @BALANCE3,
      BALANCE4 = @BALANCE4,
      BALANCE5 = @BALANCE5,
      BALANCE6 = @BALANCE6,
      BALANCE7 = @BALANCE7,
      BALANCE8 = @BALANCE8,
      BALANCE9 = @BALANCE9,
      BALANCE10 = @BALANCE10,
      BALANCE2 = @BALANCE2,
      BATCHNUMBER = @BATCHNUMBER,
      --UID = @UID,
      INVOICE = @INVOICE,
      INVOICEFLAGS = @INVOICEFLAGS,
      OVERPAIDAMT = @OVERPAIDAMT,
      FORWARDEEFEE = @FORWARDEEFEE,
      REVERSEOFUID = @REVERSEOFUID,
      ACCRUEDSURCHARGE = @ACCRUEDSURCHARGE,
      TRANSCOST = @TRANSCOST,
      TAX = @TAX,
      ATTORNEYID = @ATTORNEYID,
      COLLECTORFEE = @COLLECTORFEE,
      PAIDENTIFIER = @PAIDENTIFIER,
      AIMAGENCYID = @AIMAGENCYID,
      AIMDUEAGENCY = @AIMDUEAGENCY,
      AIMAGENCYFEE = @AIMAGENCYFEE
where NUMBER = @NUMBER

end
GO
