SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[RebuildStairStep]
    @Customer VARCHAR(7) = NULL ,
    @IncludeNonInvoicable BIT = 0
AS
    SET NOCOUNT ON;
    SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
    SET ANSI_WARNINGS OFF;

	EXEC dbo.RefreshStairStepTempTables;

    CREATE TABLE #SS
        (
          [customer] NVARCHAR(7) NULL ,
          [SSYear] NVARCHAR(4) NULL ,
          [SSMonth] NVARCHAR(2) NULL ,
          [NumberPlaced] MONEY NOT NULL ,
          [GrossDollarsPlaced] MONEY NOT NULL ,
          [NetDollarsPlaced] MONEY NOT NULL ,
          [Adjustments] MONEY NOT NULL ,
          [GTCollections] MONEY NOT NULL ,
          [GTFees] MONEY NOT NULL ,
          [TMCollections] MONEY NOT NULL ,
          [TMFees] MONEY NOT NULL ,
          [LMCollections] MONEY NOT NULL ,
          [LMFees] MONEY NOT NULL ,
          [Month1] MONEY NOT NULL ,
          [Month2] MONEY NOT NULL ,
          [Month3] MONEY NOT NULL ,
          [Month4] MONEY NOT NULL ,
          [Month5] MONEY NOT NULL ,
          [Month6] MONEY NOT NULL ,
          [Month7] MONEY NOT NULL ,
          [Month8] MONEY NOT NULL ,
          [Month9] MONEY NOT NULL ,
          [Month10] MONEY NOT NULL ,
          [Month11] MONEY NOT NULL ,
          [Month12] MONEY NOT NULL ,
          [Month13] MONEY NOT NULL ,
          [Month14] MONEY NOT NULL ,
          [Month15] MONEY NOT NULL ,
          [Month16] MONEY NOT NULL ,
          [Month17] MONEY NOT NULL ,
          [Month18] MONEY NOT NULL ,
          [Month19] MONEY NOT NULL ,
          [Month20] MONEY NOT NULL ,
          [Month21] MONEY NOT NULL ,
          [Month22] MONEY NOT NULL ,
          [Month23] MONEY NOT NULL ,
          [Month24] MONEY NOT NULL ,
          [Month99] MONEY NOT NULL
        );

    IF @Customer IS NULL
        IF @IncludeNonInvoicable = 1
            INSERT  INTO #SS
                    ( [customer] ,
                      [SSYear] ,
                      [SSMonth] ,
                      [NumberPlaced] ,
                      [GrossDollarsPlaced] ,
                      [NetDollarsPlaced] ,
                      [Adjustments] ,
                      [GTCollections] ,
                      [GTFees] ,
                      [TMCollections] ,
                      [TMFees] ,
                      [LMCollections] ,
                      [LMFees] ,
                      [Month1] ,
                      [Month2] ,
                      [Month3] ,
                      [Month4] ,
                      [Month5] ,
                      [Month6] ,
                      [Month7] ,
                      [Month8] ,
                      [Month9] ,
                      [Month10] ,
                      [Month11] ,
                      [Month12] ,
                      [Month13] ,
                      [Month14] ,
                      [Month15] ,
                      [Month16] ,
                      [Month17] ,
                      [Month18] ,
                      [Month19] ,
                      [Month20] ,
                      [Month21] ,
                      [Month22] ,
                      [Month23] ,
                      [Month24] ,
                      [Month99]
                    )
                    SELECT  [Customer] ,
                            YEAR([PlacementMonth]) ,
                            MONTH([PlacementMonth]) ,
                            [AccountsPlaced] ,
                            [GrossDollarsPlaced] ,
                            [NetDollarsPlaced] ,
                            [Adjustments] ,
                            [TotalCollections] ,
                            [TotalFees] ,
                            [CurrentMonthCollections] ,
                            [CurrentMonthFees] ,
                            [LastMonthCollections] ,
                            [LastMonthFees] ,
                            [Month1Collections] ,
                            [Month2Collections] ,
                            [Month3Collections] ,
                            [Month4Collections] ,
                            [Month5Collections] ,
                            [Month6Collections] ,
                            [Month7Collections] ,
                            [Month8Collections] ,
                            [Month9Collections] ,
                            [Month10Collections] ,
                            [Month11Collections] ,
                            [Month12Collections] ,
                            [Month13Collections] ,
                            [Month14Collections] ,
                            [Month15Collections] ,
                            [Month16Collections] ,
                            [Month17Collections] ,
                            [Month18Collections] ,
                            [Month19Collections] ,
                            [Month20Collections] ,
                            [Month21Collections] ,
                            [Month22Collections] ,
                            [Month23Collections] ,
                            [Month24Collections] ,
                            [Month99Collections]
                    FROM    [dbo].[StairStep_ReportView];
        ELSE
            INSERT  INTO #SS
                    ( [customer] ,
                      [SSYear] ,
                      [SSMonth] ,
                      [NumberPlaced] ,
                      [GrossDollarsPlaced] ,
                      [NetDollarsPlaced] ,
                      [Adjustments] ,
                      [GTCollections] ,
                      [GTFees] ,
                      [TMCollections] ,
                      [TMFees] ,
                      [LMCollections] ,
                      [LMFees] ,
                      [Month1] ,
                      [Month2] ,
                      [Month3] ,
                      [Month4] ,
                      [Month5] ,
                      [Month6] ,
                      [Month7] ,
                      [Month8] ,
                      [Month9] ,
                      [Month10] ,
                      [Month11] ,
                      [Month12] ,
                      [Month13] ,
                      [Month14] ,
                      [Month15] ,
                      [Month16] ,
                      [Month17] ,
                      [Month18] ,
                      [Month19] ,
                      [Month20] ,
                      [Month21] ,
                      [Month22] ,
                      [Month23] ,
                      [Month24] ,
                      [Month99]
                    )
                    SELECT  [Customer] ,
                            YEAR([PlacementMonth]) ,
                            MONTH([PlacementMonth]) ,
                            [AccountsPlaced] ,
                            [GrossDollarsPlaced] ,
                            [NetDollarsPlaced] ,
                            [Adjustments] ,
                            [TotalInvoicableCollections] ,
                            [TotalInvoicableFees] ,
                            [CurrentMonthInvoicableCollections] ,
                            [CurrentMonthInvoicableFees] ,
                            [LastMonthInvoicableCollections] ,
                            [LastMonthInvoicableFees] ,
                            [Month1InvoicableCollections] ,
                            [Month2InvoicableCollections] ,
                            [Month3InvoicableCollections] ,
                            [Month4InvoicableCollections] ,
                            [Month5InvoicableCollections] ,
                            [Month6InvoicableCollections] ,
                            [Month7InvoicableCollections] ,
                            [Month8InvoicableCollections] ,
                            [Month9InvoicableCollections] ,
                            [Month10InvoicableCollections] ,
                            [Month11InvoicableCollections] ,
                            [Month12InvoicableCollections] ,
                            [Month13InvoicableCollections] ,
                            [Month14InvoicableCollections] ,
                            [Month15InvoicableCollections] ,
                            [Month16InvoicableCollections] ,
                            [Month17InvoicableCollections] ,
                            [Month18InvoicableCollections] ,
                            [Month19InvoicableCollections] ,
                            [Month20InvoicableCollections] ,
                            [Month21InvoicableCollections] ,
                            [Month22InvoicableCollections] ,
                            [Month23InvoicableCollections] ,
                            [Month24InvoicableCollections] ,
                            [Month99InvoicableCollections]
                    FROM    [dbo].[StairStep_ReportView];
    ELSE
        IF @IncludeNonInvoicable = 1
            INSERT  INTO #SS
                    ( [customer] ,
                      [SSYear] ,
                      [SSMonth] ,
                      [NumberPlaced] ,
                      [GrossDollarsPlaced] ,
                      [NetDollarsPlaced] ,
                      [Adjustments] ,
                      [GTCollections] ,
                      [GTFees] ,
                      [TMCollections] ,
                      [TMFees] ,
                      [LMCollections] ,
                      [LMFees] ,
                      [Month1] ,
                      [Month2] ,
                      [Month3] ,
                      [Month4] ,
                      [Month5] ,
                      [Month6] ,
                      [Month7] ,
                      [Month8] ,
                      [Month9] ,
                      [Month10] ,
                      [Month11] ,
                      [Month12] ,
                      [Month13] ,
                      [Month14] ,
                      [Month15] ,
                      [Month16] ,
                      [Month17] ,
                      [Month18] ,
                      [Month19] ,
                      [Month20] ,
                      [Month21] ,
                      [Month22] ,
                      [Month23] ,
                      [Month24] ,
                      [Month99]
                    )
                    SELECT  [Customer] ,
                            YEAR([PlacementMonth]) ,
                            MONTH([PlacementMonth]) ,
                            [AccountsPlaced] ,
                            [GrossDollarsPlaced] ,
                            [NetDollarsPlaced] ,
                            [Adjustments] ,
                            [TotalCollections] ,
                            [TotalFees] ,
                            [CurrentMonthCollections] ,
                            [CurrentMonthFees] ,
                            [LastMonthCollections] ,
                            [LastMonthFees] ,
                            [Month1Collections] ,
                            [Month2Collections] ,
                            [Month3Collections] ,
                            [Month4Collections] ,
                            [Month5Collections] ,
                            [Month6Collections] ,
                            [Month7Collections] ,
                            [Month8Collections] ,
                            [Month9Collections] ,
                            [Month10Collections] ,
                            [Month11Collections] ,
                            [Month12Collections] ,
                            [Month13Collections] ,
                            [Month14Collections] ,
                            [Month15Collections] ,
                            [Month16Collections] ,
                            [Month17Collections] ,
                            [Month18Collections] ,
                            [Month19Collections] ,
                            [Month20Collections] ,
                            [Month21Collections] ,
                            [Month22Collections] ,
                            [Month23Collections] ,
                            [Month24Collections] ,
                            [Month99Collections]
                    FROM    [dbo].[StairStep_ReportView]
                    WHERE   [Customer] = @Customer;
        ELSE
            INSERT  INTO #SS
                    ( [customer] ,
                      [SSYear] ,
                      [SSMonth] ,
                      [NumberPlaced] ,
                      [GrossDollarsPlaced] ,
                      [NetDollarsPlaced] ,
                      [Adjustments] ,
                      [GTCollections] ,
                      [GTFees] ,
                      [TMCollections] ,
                      [TMFees] ,
                      [LMCollections] ,
                      [LMFees] ,
                      [Month1] ,
                      [Month2] ,
                      [Month3] ,
                      [Month4] ,
                      [Month5] ,
                      [Month6] ,
                      [Month7] ,
                      [Month8] ,
                      [Month9] ,
                      [Month10] ,
                      [Month11] ,
                      [Month12] ,
                      [Month13] ,
                      [Month14] ,
                      [Month15] ,
                      [Month16] ,
                      [Month17] ,
                      [Month18] ,
                      [Month19] ,
                      [Month20] ,
                      [Month21] ,
                      [Month22] ,
                      [Month23] ,
                      [Month24] ,
                      [Month99]
                    )
                    SELECT  [Customer] ,
                            YEAR([PlacementMonth]) ,
                            MONTH([PlacementMonth]) ,
                            [AccountsPlaced] ,
                            [GrossDollarsPlaced] ,
                            [NetDollarsPlaced] ,
                            [Adjustments] ,
                            [TotalInvoicableCollections] ,
                            [TotalInvoicableFees] ,
                            [CurrentMonthInvoicableCollections] ,
                            [CurrentMonthInvoicableFees] ,
                            [LastMonthInvoicableCollections] ,
                            [LastMonthInvoicableFees] ,
                            [Month1InvoicableCollections] ,
                            [Month2InvoicableCollections] ,
                            [Month3InvoicableCollections] ,
                            [Month4InvoicableCollections] ,
                            [Month5InvoicableCollections] ,
                            [Month6InvoicableCollections] ,
                            [Month7InvoicableCollections] ,
                            [Month8InvoicableCollections] ,
                            [Month9InvoicableCollections] ,
                            [Month10InvoicableCollections] ,
                            [Month11InvoicableCollections] ,
                            [Month12InvoicableCollections] ,
                            [Month13InvoicableCollections] ,
                            [Month14InvoicableCollections] ,
                            [Month15InvoicableCollections] ,
                            [Month16InvoicableCollections] ,
                            [Month17InvoicableCollections] ,
                            [Month18InvoicableCollections] ,
                            [Month19InvoicableCollections] ,
                            [Month20InvoicableCollections] ,
                            [Month21InvoicableCollections] ,
                            [Month22InvoicableCollections] ,
                            [Month23InvoicableCollections] ,
                            [Month24InvoicableCollections] ,
                            [Month99InvoicableCollections]
                    FROM    [dbo].[StairStep_ReportView]
                    WHERE   [Customer] = @Customer;

    BEGIN TRANSACTION;

    IF @Customer IS NULL
        DELETE  FROM [StairStep];
    ELSE
        DELETE  FROM [StairStep]
        WHERE   [customer] = @Customer;

    INSERT  INTO [StairStep]
            ( [customer] ,
              [ctl] ,
              [SSYear] ,
              [SSMonth] ,
              [NumberPlaced] ,
              [GrossDollarsPlaced] ,
              [NetDollarsPlaced] ,
              [Adjustments] ,
              [GTcollections] ,
              [GTfees] ,
              [TMcollections] ,
              [TMfees] ,
              [LMcollections] ,
              [LMfees] ,
              [Month1] ,
              [Month2] ,
              [Month3] ,
              [Month4] ,
              [Month5] ,
              [Month6] ,
              [Month7] ,
              [Month8] ,
              [Month9] ,
              [Month10] ,
              [Month11] ,
              [Month12] ,
              [Month13] ,
              [Month14] ,
              [Month15] ,
              [Month16] ,
              [Month17] ,
              [Month18] ,
              [Month19] ,
              [Month20] ,
              [Month21] ,
              [Month22] ,
              [Month23] ,
              [Month24] ,
              [Month99]
            )
            SELECT  [customer] ,
                    NULL ,
                    [SSYear] ,
                    [SSMonth] ,
                    [NumberPlaced] ,
                    [GrossDollarsPlaced] ,
                    [NetDollarsPlaced] ,
                    [Adjustments] ,
                    [GTCollections] ,
                    [GTFees] ,
                    [TMCollections] ,
                    [TMFees] ,
                    [LMCollections] ,
                    [LMFees] ,
                    [Month1] ,
                    [Month2] ,
                    [Month3] ,
                    [Month4] ,
                    [Month5] ,
                    [Month6] ,
                    [Month7] ,
                    [Month8] ,
                    [Month9] ,
                    [Month10] ,
                    [Month11] ,
                    [Month12] ,
                    [Month13] ,
                    [Month14] ,
                    [Month15] ,
                    [Month16] ,
                    [Month17] ,
                    [Month18] ,
                    [Month19] ,
                    [Month20] ,
                    [Month21] ,
                    [Month22] ,
                    [Month23] ,
                    [Month24] ,
                    [Month99]
            FROM    #SS;

    COMMIT TRANSACTION;


    RETURN 0;


GO
