SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE    procedure [dbo].[Lib_Insert_Debtors]
(
      @DebtorID   int output,
      @NUMBER   int,
      @SEQ   int,
      @NAME   varchar (60),
      @STREET1   varchar (30),
      @STREET2   varchar (30),
      @CITY   varchar (30),
      @STATE   varchar (3),
      @ZIPCODE   varchar (10),
      @HOMEPHONE   varchar (30),
      @WORKPHONE   varchar (30),
      @SSN   varchar (15),
      @MR   varchar (1),
      @OTHERNAME   varchar (30),
      @DOB   datetime,
      @JOBNAME   varchar (50),
      @JOBADDR1   varchar (50),
      @JOBADDR2   varchar (50),
      @JOBCSZ   varchar (50),
      @JOBMEMO   text,
      @RELATIONSHIP   varchar (20),
      @SPOUSE   varchar (50),
      @SPOUSEJOBNAME   varchar (50),
      @SPOUSEJOBADDR1   varchar (50),
      @SPOUSEJOBADDR2   varchar (50),
      @SPOUSEJOBCSZ   varchar (50),
      @SPOUSEJOBMEMO   text,
      @SPOUSEHOMEPHONE   varchar (20),
      @SPOUSEWORKPHONE   varchar (20),
      @SPOUSERESPONSIBLE   varchar (1),
      @PAGER   varchar (20),
      @OTHERPHONE1   varchar (20),
      @OTHERPHONETYPE   varchar (15),
      @OTHERPHONE2   varchar (20),
      @OTHERPHONE2TYPE   varchar (15),
      @OTHERPHONE3   varchar (20),
      @OTHERPHONE3TYPE   varchar (15),
      @DEBTORMEMO   text,
      @LANGUAGE   varchar (30),
      @DLNUM   varchar (50),
      @FAX   varchar (50),
      @EMAIL   varchar (50),
      @DATECREATED   datetime,
      @DATEUPDATED   datetime,
      @COUNTRY   varchar (50),
	  @RESPONSIBLE bit,
	  @FIRSTNAME varchar(50),
	  @MIDDLENAME varchar(50),
	  @LASTNAME varchar(50),
	  @USPSKEYLINE VARCHAR(16),
	  @ISHOMEOWNER bit,
	  @EARLYTIMEZONE   int,
      @LATETIMEZONE   int,
      @BUSINESSNAME   varchar (50),
      @PREFIX   varchar (50),
      @GENDER   char (1),
      @OBSERVESDST   bit,
      @REGIONCODE   char (2),
      @COUNTY   varchar (50),
      @TIMEZONEOVERRIDE   bit,
	  @SUFFIX   varchar (50),
      @ISBUSINESS   bit,
      @ISPARSED   bit,
      @CBREXCEPTION   smallint,
      @CBREXCLUDE   bit,
	  @ISAUTHORIZEDACCOUNTUSER bit = null,
	  @CONTACTMETHOD varchar(10) 
)
as
begin


insert into dbo.Debtors
(
      NUMBER,
      SEQ,
      NAME,
      STREET1,
      STREET2,
      CITY,
      STATE,
      ZIPCODE,
      HOMEPHONE,
      WORKPHONE,
      SSN,
      MR,
      OTHERNAME,
      DOB,
      JOBNAME,
      JOBADDR1,
      JOBADDR2,
      JOBCSZ,
      JOBMEMO,
      RELATIONSHIP,
      SPOUSE,
      SPOUSEJOBNAME,
      SPOUSEJOBADDR1,
      SPOUSEJOBADDR2,
      SPOUSEJOBCSZ,
      SPOUSEJOBMEMO,
      SPOUSEHOMEPHONE,
      SPOUSEWORKPHONE,
      SPOUSERESPONSIBLE,
      PAGER,
      OTHERPHONE1,
      OTHERPHONETYPE,
      OTHERPHONE2,
      OTHERPHONE2TYPE,
      OTHERPHONE3,
      OTHERPHONE3TYPE,
      DEBTORMEMO,
      LANGUAGE,
      DLNUM,
      FAX,
      EMAIL,
      DATECREATED,
      DATEUPDATED,
      COUNTRY,
      RESPONSIBLE,
      FIRSTNAME,
      MIDDLENAME,
      LASTNAME,
      USPSKEYLINE ,
      ISHOMEOWNER,
	  SUFFIX,
      ISBUSINESS,
      ISPARSED,
      CBREXCEPTION,
      CBREXCLUDE,
      EARLYTIMEZONE,
      LATETIMEZONE,
      BUSINESSNAME,
      PREFIX,
      GENDER,
      OBSERVESDST,
      REGIONCODE,
      COUNTY,
      TIMEZONEOVERRIDE,
	  ISAUTHORIZEDACCOUNTUSER,
	  CONTACTMETHOD	  
)
values
(
      @NUMBER,
      @SEQ,
      ltrim(rtrim(left(@NAME,30))),
      @STREET1,
      @STREET2,
      @CITY,
      @STATE,
      @ZIPCODE,
      dbo.stripnondigits(@HOMEPHONE),
      dbo.stripnondigits(@WORKPHONE),
      @SSN,
      isnull(@MR,'N'),
      isnull(@OTHERNAME,''),
      @DOB,
      @JOBNAME,
      @JOBADDR1,
      @JOBADDR2,
      @JOBCSZ,
      @JOBMEMO,
      @RELATIONSHIP,
      @SPOUSE,
      @SPOUSEJOBNAME,
      @SPOUSEJOBADDR1,
      @SPOUSEJOBADDR2,
      @SPOUSEJOBCSZ,
      @SPOUSEJOBMEMO,
      @SPOUSEHOMEPHONE,
      @SPOUSEWORKPHONE,
      @SPOUSERESPONSIBLE,
      @PAGER,
      @OTHERPHONE1,
      @OTHERPHONETYPE,
      @OTHERPHONE2,
      @OTHERPHONE2TYPE,
      @OTHERPHONE3,
      @OTHERPHONE3TYPE,
      @DEBTORMEMO,
      @LANGUAGE,
      @DLNUM,
      @FAX,
      @EMAIL,
      @DATECREATED,
      @DATEUPDATED,
      @COUNTRY,
      @RESPONSIBLE,
      @FIRSTNAME,
      @MIDDLENAME,
      @LASTNAME,
      @USPSKEYLINE,
      @ISHOMEOWNER,
	  @SUFFIX,
      @ISBUSINESS,
      @ISPARSED,
      @CBREXCEPTION,
      @CBREXCLUDE,
      @EARLYTIMEZONE,
      @LATETIMEZONE,
      @BUSINESSNAME,
      @PREFIX,
      @GENDER,
      @OBSERVESDST,
      @REGIONCODE,
      @COUNTY,
      @TIMEZONEOVERRIDE,
	  @ISAUTHORIZEDACCOUNTUSER,
	  @CONTACTMETHOD
)

select @DebtorID = Scope_Identity()
end
GO
