SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO




/*sp_CCustomer_Update  */
CREATE Procedure [dbo].[sp_CCustomer_Update]
@CCustomerID int,
@Customer varchar(7),
@Status varchar(8),
@SelectedFlag varchar(1),
@Name varchar(50),
@Street1 varchar(30),
@Street2 varchar(30),
@City varchar(20),
@State varchar(3),
@Zipcode varchar(10),
@Contact varchar(30),
@Phone varchar(20),
@Lettercode varchar(50),
@Penalty money,
@Badcheck money,
@Ctl varchar(3),
@Fees money,
@Collections money,
@Mtdnumberplaced float,
@Mtddollarsplaced money,
@Ytdnumberplaced float,
@Ytddollarsplaced money,
@Mtdpdcfees money,
@Mtdpdccollections money,
@Mtdfees money,
@Mtdcollections money,
@Ytdfees money,
@Ytdcollections money,
@Bankcode varchar(30),
@Attorneycode varchar(30),
@Salesmancode varchar(30),
@Sifinfo text,
@Workinfo text,
@Miscinfo text,
@Invoicetype varchar(20),
@Invoicefreq varchar(20),
@Invoicesort varchar(20),
@Invoicemethod varchar(20),
@Options varchar(50),
@Option1 varchar(50),
@Fax varchar(15),
@Half money,
@Close_ money,
@FaxNumber varchar(30),
@AutoRecallStatus varchar(60),
@AutoRecallDays int,
@AutoRecallFlag varchar(1),
@Locate money,
@SpecialCode varchar(20),
@CustomerGroup varchar(10),
@Full0 money,
@AmtDueClient smallint,
@Feecode2 varchar(30),
@Feedays int,
@Cob varchar(50),
@Company varchar(40),
@LastInvoiceAttempt datetime,
@RemitMethod varchar(5),
@ABARoutingNum varchar(9),
@BankAcctNum varchar(20),
@CustGroup varchar(7),
@CheckHoldDays smallint,
@InvShowRcvd bit,
@InvShowBal bit,
@CCostPct real,
@CCostBucket tinyint,
@FeeSchedule varchar(5),
@IsPODCust bit,
@CBRRptType varchar(50),
@CBRMinBal money,
@CBRWaitDays int,
@UseEquifax bit,
@UseTransUnion bit,
@UseExperian bit,
@UseInnovis bit,
@EMail varchar(30),
@CBRClass varchar(40),
@ShowReverseOfDate bit,
@OnlineCheckFee money,
@AlphaCode varchar(50),
@Sweep bit,
@SweepDays int,
@SweepDaysPaid int,
@SweepMinBalance money,
@SweepDesk varchar(10),
@DefaultDesk varchar(10),
@FaxID varchar(50),
@LetterDeliveryMethod int
AS

UPDATE Customer
SET
--Customer = @Customer,
status = @Status,
SelectedFlag = @SelectedFlag,
Name = @Name,
Street1 = @Street1,
Street2 = @Street2,
City = @City,
State = @State,
Zipcode = @Zipcode,
Contact = @Contact,
phone = @Phone,
lettercode = @Lettercode,
penalty = @Penalty,
badcheck = @Badcheck,
ctl = @Ctl,
fees = @Fees,
collections = @Collections,
mtdnumberplaced = @Mtdnumberplaced,
mtddollarsplaced = @Mtddollarsplaced,
ytdnumberplaced = @Ytdnumberplaced,
ytddollarsplaced = @Ytddollarsplaced,
mtdpdcfees = @Mtdpdcfees,
mtdpdccollections = @Mtdpdccollections,
mtdfees = @Mtdfees,
mtdcollections = @Mtdcollections,
ytdfees = @Ytdfees,
ytdcollections = @Ytdcollections,
bankcode = @Bankcode,
attorneycode = @Attorneycode,
salesmancode = @Salesmancode,
sifinfo = @Sifinfo,
workinfo = @Workinfo,
miscinfo = @Miscinfo,
invoicetype = @Invoicetype,
invoicefreq = @Invoicefreq,
invoicesort = @Invoicesort,
invoicemethod = @Invoicemethod,
options = @Options,
option1 = @Option1,
fax = @Fax,
Half = @Half,
Close_ = @Close_,
FaxNumber = @FaxNumber,
AutoRecallStatus = @AutoRecallStatus,
AutoRecallDays = @AutoRecallDays,
AutoRecallFlag = @AutoRecallFlag,
locate = @Locate,
SpecialCode = @SpecialCode,
CustomerGroup = @CustomerGroup,
Full0 = @Full0,
AmtDueClient = @AmtDueClient,
feecode2 = @Feecode2,
feedays = @Feedays,
cob = @Cob,
company = @Company,
LastInvoiceAttempt = @LastInvoiceAttempt,
RemitMethod = @RemitMethod,
ABARoutingNum = @ABARoutingNum,
BankAcctNum = @BankAcctNum,
CustGroup = @CustGroup,
CheckHoldDays = @CheckHoldDays,
InvShowRcvd = @InvShowRcvd,
InvShowBal = @InvShowBal,
CCostPct = @CCostPct,
CCostBucket = @CCostBucket,
FeeSchedule = @FeeSchedule,
IsPODCust = @IsPODCust,
CBRRptType = @CBRRptType,
CBRMinBal = @CBRMinBal,
CBRWaitDays = @CBRWaitDays,
UseEquifax = @UseEquifax,
UseTransUnion = @UseTransUnion,
UseExperian = @UseExperian,
UseInnovis = @UseInnovis,
eMail = @EMail,
CBRClass = @CBRClass,
ShowReverseOfDate = @ShowReverseOfDate,
OnlineCheckFee = @OnlineCheckFee,
AlphaCode = @AlphaCode,
Sweep = @Sweep,
SweepDays = @SweepDays,
SweepDaysPaid = @SweepDaysPaid,
SweepMinBalance = @SweepMinBalance,
SweepDesk = @SweepDesk,
DefaultDesk = @DefaultDesk,
FaxID = @FaxID,
LetterDeliveryMethod = @LetterDeliveryMethod
WHERE CCustomerID = @CCustomerID

GO
