SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE procedure [dbo].[Lib_Update_Insurance]
(
      @INSURANCEID   int,
      @NUMBER   int,
      @INSUREDNAME   varchar (50),
      @INSUREDSTREET1   varchar (50),
      @INSUREDSTREET2   varchar (50),
      @INSUREDCITY   varchar (50),
      @INSUREDSTATE   char (3),
      @INSUREDZIP   char (10),
      @INSUREDPHONE   char (20),
      @INSUREDBIRTHDAY   datetime,
      @INSUREDSEX   char (1),
      @INSUREDEMPLOYER   varchar (50),
      @AUTHPMTTOPROVIDOR   bit,
      @ACCEPTASSIGNMENT   bit,
      @EMPLOYERHEALTHPLAN   varchar (50),
      @POLICYNUMBER   varchar (50),
      @PATIENTRELATIONTOINSURED   varchar (50),
      @PROGRAM   varchar (50),
      @GROUPNUMBER   varchar (50),
      @GROUPNAME   varchar (50),
      @CARRIERNAME   varchar (100),
      @CARRIERSTREET1   varchar (50),
      @CARRIERSTREET2   varchar (50),
      @CARRIERCITY   varchar (50),
      @CARRIERSTATE   char (3),
      @CARRIERZIP   char (10),
      @CARRIERDOCPROVIDERNUMBER   varchar (30),
      @CARRIERREFDOCPROVIDERNUMBER   varchar (30),
      @ADDITIONALINFO   varchar (5000),
      @DATECREATED   datetime,
      @DATEUPDATED   datetime,
      @UPDATECHECKSUM   varchar (10),
      @UPDATEDBY   int,
      @COORDINATIONNUMBER VARCHAR(50) = NULL,
      @INSUREDSSN VARCHAR(20) = NULL,
      @INSUREDWORKPHONE VARCHAR(15) = NULL
)
as
begin

		if  exists(select * from sysobjects o join syscolumns c on c.id = o.id where o.name = 'Insurance' and o.xtype = 'U' and c.name = 'INSUREDWORKPHONE')
		BEGIN
			update dbo.Insurance set
				  [NUMBER] = @NUMBER,
				  [INSUREDNAME] = @INSUREDNAME,
				  [INSUREDSTREET1] = @INSUREDSTREET1,
				  [INSUREDSTREET2] = @INSUREDSTREET2,
				  [INSUREDCITY] = @INSUREDCITY,
				  [INSUREDSTATE] = @INSUREDSTATE,
				  [INSUREDZIP] = @INSUREDZIP,
				  [INSUREDPHONE] = @INSUREDPHONE,
				  [INSUREDBIRTHDAY] = @INSUREDBIRTHDAY,
				  [INSUREDSEX] = @INSUREDSEX,
				  [INSUREDEMPLOYER] = @INSUREDEMPLOYER,
				  [AUTHPMTTOPROVIDOR] = @AUTHPMTTOPROVIDOR,
				  [ACCEPTASSIGNMENT] = @ACCEPTASSIGNMENT,
				  [EMPLOYERHEALTHPLAN] = @EMPLOYERHEALTHPLAN,
				  [POLICYNUMBER] = @POLICYNUMBER,
				  [PATIENTRELATIONTOINSURED] = @PATIENTRELATIONTOINSURED,
				  [PROGRAM] = @PROGRAM,
				  [GROUPNUMBER] = @GROUPNUMBER,
				  [GROUPNAME] = @GROUPNAME,
				  [CARRIERNAME] = @CARRIERNAME,
				  [CARRIERSTREET1] = @CARRIERSTREET1,
				  [CARRIERSTREET2] = @CARRIERSTREET2,
				  [CARRIERCITY] = @CARRIERCITY,
				  [CARRIERSTATE] = @CARRIERSTATE,
				  [CARRIERZIP] = @CARRIERZIP,
				  [CARRIERDOCPROVIDERNUMBER] = @CARRIERDOCPROVIDERNUMBER,
				  [CARRIERREFDOCPROVIDERNUMBER] = @CARRIERREFDOCPROVIDERNUMBER,
				  [ADDITIONALINFO] = @ADDITIONALINFO,
				  [DATECREATED] = @DATECREATED,
				  [DATEUPDATED] = @DATEUPDATED,
				  [UPDATECHECKSUM] = CHECKSUM(GETDATE()),
				  [UPDATEDBY] = @UPDATEDBY,
				  [COORDINATIONNUMBER] = @COORDINATIONNUMBER,
				  [INSUREDSSN] = @INSUREDSSN,
				  [INSUREDWORKPHONE] = @INSUREDWORKPHONE
			WHERE
				  [INSURANCEID] = @INSURANCEID
		END
		ELSE
		BEGIN
		
			update dbo.Insurance set
				  [NUMBER] = @NUMBER,
				  [INSUREDNAME] = @INSUREDNAME,
				  [INSUREDSTREET1] = @INSUREDSTREET1,
				  [INSUREDSTREET2] = @INSUREDSTREET2,
				  [INSUREDCITY] = @INSUREDCITY,
				  [INSUREDSTATE] = @INSUREDSTATE,
				  [INSUREDZIP] = @INSUREDZIP,
				  [INSUREDPHONE] = @INSUREDPHONE,
				  [INSUREDBIRTHDAY] = @INSUREDBIRTHDAY,
				  [INSUREDSEX] = @INSUREDSEX,
				  [INSUREDEMPLOYER] = @INSUREDEMPLOYER,
				  [AUTHPMTTOPROVIDOR] = @AUTHPMTTOPROVIDOR,
				  [ACCEPTASSIGNMENT] = @ACCEPTASSIGNMENT,
				  [EMPLOYERHEALTHPLAN] = @EMPLOYERHEALTHPLAN,
				  [POLICYNUMBER] = @POLICYNUMBER,
				  [PATIENTRELATIONTOINSURED] = @PATIENTRELATIONTOINSURED,
				  [PROGRAM] = @PROGRAM,
				  [GROUPNUMBER] = @GROUPNUMBER,
				  [GROUPNAME] = @GROUPNAME,
				  [CARRIERNAME] = @CARRIERNAME,
				  [CARRIERSTREET1] = @CARRIERSTREET1,
				  [CARRIERSTREET2] = @CARRIERSTREET2,
				  [CARRIERCITY] = @CARRIERCITY,
				  [CARRIERSTATE] = @CARRIERSTATE,
				  [CARRIERZIP] = @CARRIERZIP,
				  [CARRIERDOCPROVIDERNUMBER] = @CARRIERDOCPROVIDERNUMBER,
				  [CARRIERREFDOCPROVIDERNUMBER] = @CARRIERREFDOCPROVIDERNUMBER,
				  [ADDITIONALINFO] = @ADDITIONALINFO,
				  [DATECREATED] = @DATECREATED,
				  [DATEUPDATED] = @DATEUPDATED,
				  [UPDATECHECKSUM] = CHECKSUM(GETDATE()),
				  [UPDATEDBY] = @UPDATEDBY
			WHERE
				  [INSURANCEID] = @INSURANCEID		
		END
end

GO
