SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- Changes:		04/08/2021 BGM Updated where clause so the proper variable types will match.
--				04/12/2021 BGM Changed ESD table to Left outer join
--				08/20/2021 BGM added code to check if Agency Date Sent data changed.
-- =============================================
CREATE PROCEDURE [dbo].[Custom_PPNB_Export_Maintenance_File_V2]
	-- Add the parameters for the stored procedure here
	--EXEC Custom_PPNB_Export_Placement_File
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

--Pre export maintenance query
SELECT CUSTOMER_ACCOUNT_ID, ACCOUNT_CATEGORY , CUSTOMER_LAST_NAME , CUSTOMER_FIRST_NAME , 
		CUSTOMER_BIRTH_DATE , SOCIAL_SECURITY_NUMBER , CHARGED_OFF_FLAG , CONVERT(VARCHAR(10), CHARGED_OFF_DATE, 120) AS CHARGED_OFF_DATE , CUSTOMER_CREATE_DATE , CUSTOMER_BALANCE , FEE_AMOUNT,
		CUSTOMER_BALANCE_CHANGE_REASON , CURRENCY_CODE , PLACEABLE_DAYS , ADDRESS_LINE_1 , ADDRESS_LINE_2 , ADDRESS_CITY , 
		ADDRESS_STATE , ADDRESS_POSTAL_CODE , ADDRESS_COUNTRY , CUSTOMER_PHONE_HOME , CUSTOMER_PHONE_WORK , CUSTOMER_EMAIL , 
		BANK_NAME , PENDING_BALANCE , CONFIRMED_BALANCE , ACCOUNT_STATUS_ID , ACCOUNT_LIMITATIONS , ACCOUNT_LIMITATIONS_FLAG , 
		EXEMPTION , EXEMPTION_FLAG , NEG_BAL_EMAIL_FLAG , ACCOUNT_MANAGED_FLAG , PARENT_STUDENT_ACCOUNT_ID , STUDENT_ACCOUNT_FLAG, TAX_ID_NUMBER , LAST_PAYMENT_DATE , 
		LAST_PAYMENT_AMOUNT , LAST_PAYMENT_TYPE , LAST_LOGIN_DATE , AGENCY_NAME , AGENCY_DATE_SENT , AGENCY_DAYS_PLACED , PREVIOUS_AGENCY_NAME , 
		WAREHOUSE_NAME , WAREHOUSE_DATE_SENT, WAREHOUSE_DAYS_PLACED, PREVIOUS_WAREHOUSE_NAME , SEGMENTATION_GROUP_ID , SEGMENTATION_ID , STRATEGY_ID , APPLICATION_STATUS_ID ,
        APPLICATION_STATUS_EXPIRE_DATE , RANDOM_DIGIT_CODE , INTERNAL_ACCOUNT_ID , ACCOUNT_CYCLE_CODE , DAYS_DELINQUENT_COUNT , CYCLES_DELINQUENT_COUNT , CURRENT_MINIMUM_PAYMENT ,
        PAYMENT_ACTIVITY_HISTORY , COLLECTOR_CODE , CONVERT(VARCHAR(10), CHARGED_OFF_DATE, 120) AS LAST_WORK_DATE , NEXT_WORK_DATE , SEC_NEG_BAL_EMAIL_DATE , CYCLE_DATE_NEXT ,
        DAYS_TO_CYCLE , CYCLE_MDATE_NEXT , BUCKET_PENDING_AMOUNT , BUCKET_1_AMOUNT , BUCKET_2_AMOUNT , BUCKET_3_AMOUNT ,
        BUCKET_4_AMOUNT , BUCKET_5_AMOUNT , BUCKET_6_AMOUNT , BUCKET_7_AMOUNT , ALT_PHN_1 , ALT_PHN_2 , ALT_PHN_3 , ALT_PHN_4 , ALT_PHN_5 , ALT_PHN_6 , ALT_PHN_7 ,
        ALT_PHN_8 , ALT_PHN_9 , ALT_PHN_10, RISK_SCORE_1 , RISK_SCORE_2, RISK_SCORE_3 , RISK_SCORE_4 , RISK_SCORE_5 , RISK_SCORE_6 , RISK_SCORE_7 , RISK_SCORE_8 , RISK_SCORE_9 ,
        RISK_SCORE_10 , PPIVR , CUSTOMER_LANGUAGE , ACCOUNT_LINKING_TYPE_ID, LINKING_DAYS , 
        LINKING_TYPE_FLAG  , NEGATIVE_BALANCE_REASON , BUYER_SELLER  , Timezone , 
        TIMEZONE_DAY_LIGHT_SAVING_FLAG , cppnif.DOB AS DOB , BUSINESS_NAME
        FROM Custom_PayPal_NB_Inbound_File cppnif WITH (NOLOCK) 
			INNER JOIN master m WITH (NOLOCK) ON cppnif.CUSTOMER_ACCOUNT_ID = m.account AND m.closed IS NULL AND customer IN ('0002337', '0002338')
			LEFT OUTER JOIN EarlyStageData esd WITH (NOLOCK) ON m.number = esd.AccountID
        WHERE CUSTOMER_ACCOUNT_ID NOT IN (SELECT ACCT_ID FROM Custom_PayPal_NB_Post_CO_Master cppnpcm WITH (NOLOCK))
        AND
			(
			ACCOUNT_CYCLE_CODE <> ISNULL(esd.CycleCode, '')
			OR DAYS_DELINQUENT_COUNT <> ISNULL(esd.SubStatuses, '')
			OR CURRENT_MINIMUM_PAYMENT <> CASE WHEN CONVERT(VARCHAR(255), esd.CurrentDue) = 0.00 THEN '' ELSE '' END
			OR PAYMENT_ACTIVITY_HISTORY <> ISNULL(esd.PaymentHistory, '')
		    OR CYCLE_DATE_NEXT <> ISNULL(CONVERT(VARCHAR(10), esd.CycleNextDue, 101), '')
		    OR BUCKET_PENDING_AMOUNT <> CASE WHEN CONVERT(VARCHAR(255), esd.StatementMinDue) = 0.00 THEN '' ELSE '' END
			OR CAST(BUCKET_1_AMOUNT AS MONEY) <> ISNULL(esd.Statement30, 0)
			OR CAST(BUCKET_2_AMOUNT AS MONEY) <> ISNULL(esd.Statement60, 0)
			OR CAST(BUCKET_3_AMOUNT AS MONEY) <> ISNULL(esd.Statement90, 0)
			OR CAST(BUCKET_4_AMOUNT AS MONEY) <> ISNULL(esd.Statement120, 0)
			OR CAST(BUCKET_5_AMOUNT AS MONEY) <> ISNULL(esd.Statement150, 0)
			OR CAST(BUCKET_6_AMOUNT AS MONEY) <> ISNULL(esd.Statement180, 0)
			OR CHARGED_OFF_DATE <> CAST(m.chargeoffdate AS DATE)
			OR (CHARGED_OFF_DATE <> '' AND m.ChargeOffDate IS NULL) 
			OR (SELECT TOP 1 CAST(thedata AS DATE) FROM MiscExtra me WITH (NOLOCK) WHERE m.number = number AND title = 'acc.0.Agency_Date_Sent') <>  CAST(cppnif.AGENCY_DATE_SENT AS DATE)
			)

END
GO
