SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO

CREATE  procedure [dbo].[Lib_Insert_payhistory]
(
      @UID   int output,
      @NUMBER   int,
      @SEQ   int,
      @BATCHTYPE   varchar (3),
      @MATCHED   varchar (1),
      @CTL   varchar (3),
      @CUSTOMER   varchar (7),
      @SORTDATA   varchar (30),
      @PAYTYPE   varchar (30),
      @PAYMETHOD   varchar (30),
      @SYSTEMMONTH   int,
      @SYSTEMYEAR   int,
      @ENTERED   datetime,
      @DESK   varchar (10),
      @CHECKNBR   varchar (10),
      @INVOICED   datetime,
      @INVOICESORT   varchar (2),
      @INVOICETYPE   varchar (2),
      @INVOICEPAYTYPE   real,
      @COMMENT   char (30),
      @DATEPAID   datetime,
      @TOTALPAID   money,
      @PAID1   money,
      @PAID2   money,
      @PAID3   money,
      @PAID4   money,
      @PAID5   money,
      @PAID6   money,
      @PAID7   money,
      @PAID8   money,
      @PAID9   money,
      @PAID10   money,
      @FEE1   money,
      @FEE2   money,
      @FEE3   money,
      @FEE4   money,
      @FEE5   money,
      @FEE6   money,
      @FEE7   money,
      @FEE8   money,
      @FEE9   money,
      @FEE10   money,
      @BALANCE   money,
      @BALANCE1   money,
      @BALANCE3   money,
      @BALANCE4   money,
      @BALANCE5   money,
      @BALANCE6   money,
      @BALANCE7   money,
      @BALANCE8   money,
      @BALANCE9   money,
      @BALANCE10   money,
      @BALANCE2   money,
      @BATCHNUMBER   float,
      @INVOICE   int,
      @INVOICEFLAGS   varchar (10),
      @OVERPAIDAMT   money,
      @FORWARDEEFEE   money,
      @REVERSEOFUID   int,
      @ACCRUEDSURCHARGE   money,
      @TRANSCOST   money,
      @TAX   money,
      @ATTORNEYID   int,
      @COLLECTORFEE   money,
      @PAIDENTIFIER   varchar (30),
      @AIMAGENCYID   int,
      @AIMDUEAGENCY   money,
      @AIMAGENCYFEE   money
)
as
begin

select @SYSTEMMONTH = currentmonth, @SYSTEMYEAR = currentyear from controlfile


insert into dbo.payhistory
(
      NUMBER,
      SEQ,
      BATCHTYPE,
      MATCHED,
      CTL,
      CUSTOMER,
      SORTDATA,
      PAYTYPE,
      PAYMETHOD,
      SYSTEMMONTH,
      SYSTEMYEAR,
      ENTERED,
      DESK,
      CHECKNBR,
      INVOICED,
      INVOICESORT,
      INVOICETYPE,
      INVOICEPAYTYPE,
      COMMENT,
      DATEPAID,
      TOTALPAID,
      PAID1,
      PAID2,
      PAID3,
      PAID4,
      PAID5,
      PAID6,
      PAID7,
      PAID8,
      PAID9,
      PAID10,
      FEE1,
      FEE2,
      FEE3,
      FEE4,
      FEE5,
      FEE6,
      FEE7,
      FEE8,
      FEE9,
      FEE10,
      BALANCE,
      BALANCE1,
      BALANCE3,
      BALANCE4,
      BALANCE5,
      BALANCE6,
      BALANCE7,
      BALANCE8,
      BALANCE9,
      BALANCE10,
      BALANCE2,
      BATCHNUMBER,
      INVOICE,
      INVOICEFLAGS,
      OVERPAIDAMT,
      FORWARDEEFEE,
      REVERSEOFUID,
      ACCRUEDSURCHARGE,
      TRANSCOST,
      TAX,
      ATTORNEYID,
      COLLECTORFEE,
      PAIDENTIFIER,
      AIMAGENCYID,
      AIMDUEAGENCY,
      AIMAGENCYFEE
)
values
(
      @NUMBER,
      @SEQ,
      @BATCHTYPE,
      @MATCHED,
      @CTL,
      @CUSTOMER,
      @SORTDATA,
      @PAYTYPE,
      @PAYMETHOD,
      @SYSTEMMONTH,
      @SYSTEMYEAR,
      @ENTERED,
      @DESK,
      @CHECKNBR,
      @INVOICED,
      @INVOICESORT,
      @INVOICETYPE,
      @INVOICEPAYTYPE,
      @COMMENT,
      @DATEPAID,
      @TOTALPAID,
      @PAID1,
      @PAID2,
      @PAID3,
      @PAID4,
      @PAID5,
      @PAID6,
      @PAID7,
      @PAID8,
      @PAID9,
      @PAID10,
      @FEE1,
      @FEE2,
      @FEE3,
      @FEE4,
      @FEE5,
      @FEE6,
      @FEE7,
      @FEE8,
      @FEE9,
      @FEE10,
      @BALANCE,
      @BALANCE1,
      @BALANCE3,
      @BALANCE4,
      @BALANCE5,
      @BALANCE6,
      @BALANCE7,
      @BALANCE8,
      @BALANCE9,
      @BALANCE10,
      @BALANCE2,
      @BATCHNUMBER,
      @INVOICE,
      @INVOICEFLAGS,
      @OVERPAIDAMT,
      @FORWARDEEFEE,
      @REVERSEOFUID,
      @ACCRUEDSURCHARGE,
      @TRANSCOST,
      @TAX,
      @ATTORNEYID,
      @COLLECTORFEE,
      @PAIDENTIFIER,
      @AIMAGENCYID,
      @AIMDUEAGENCY,
      @AIMAGENCYFEE
)

select @UID = Scope_Identity()
end

GO
