SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[Custom_Toyota_Process_SoftRecalls]
@NUMBER INT
AS

-- LOCAL VARIABLE DECLARATIONS.
DECLARE @COMMENT VARCHAR(1000)
DECLARE @SOFT_RECALL_CEILING INT 
DECLARE @SOFT_RECALL_FLOOR INT
DECLARE @SOFT_RECALL_STATUS VARCHAR(3)
DECLARE @SOFT_RECALL_TITLE VARCHAR(100)
DECLARE @PAYHISTORY_UID VARCHAR(100)
DECLARE @LASTPAID DATETIME

-- LOCAL VARIABLE INITIALIZATION.
SET @SOFT_RECALL_CEILING = 180
SET @SOFT_RECALL_FLOOR = 150
SET @SOFT_RECALL_TITLE = 'TOYOTA_MAINTENANCE_A1R_RECALL'
--SET @SOFT_RECALL_STATUS = 'APP|A1P|A2P|A3P'
--SET @SOFT_RECALL_HOLD = 'APH|A1H|A2H|A3H'


-- TRANSACTIONAL PROCESSING.
BEGIN TRANSACTION


SELECT @PAYHISTORY_UID = ISNULL((SELECT TOP 1 UID
FROM Payhistory  WITH (NOLOCK)
WHERE Number = @NUMBER
ORDER BY DATEPAID DESC), '0')


IF @PAYHISTORY_UID <> '0'
	BEGIN
	
		SELECT @LASTPAID = (SELECT DatePaid FROM PAYHISTORY WHERE UID = @PAYHISTORY_UID)
		
		UPDATE Master 
		SET ID1 = 
			CASE	
		            WHEN (DATEDIFF(DAY, @LASTPAID, GETDATE()) > 60) THEN 
				
				    case me.TheData
					 when 'APP' THEN 'APR'
					 when 'A1P' THEN 'A1R'
					 when 'A2P' THEN 'A2R'
					 when 'A3P' THEN 'A3R'
				    end	
			    ELSE  
	                            case me.TheData
					 when 'APP' THEN 'APH'
					 when 'A1P' THEN 'A1H'
					 when 'A2P' THEN 'A2H'
					 when 'A3P' THEN 'A3H'                                          		 
				    end
			end
		FROM Master m WITH (NOLOCK) JOIN MiscExtra me WITH (NOLOCK)
		ON ((me.Number = m.Number) AND (me.Title like '%' + @SOFT_RECALL_TITLE + '%'))
		WHERE (m.number = @NUMBER) AND
		      (DATEDIFF(DAY, m.Received, GETDATE()) between @SOFT_RECALL_FLOOR AND
		                                                    @SOFT_RECALL_CEILING) AND
		      (ISNULL(m.ID1, '') <> me.TheData) 
	END
ELSE

	BEGIN
		UPDATE Master 
		SET ID1 = 
		    case me.TheData
			 when 'APP' THEN 'APR'
			 when 'A1P' THEN 'A1R'
			 when 'A2P' THEN 'A2R'
			 when 'A3P' THEN 'A3R'
		    end	
		FROM Master m WITH (NOLOCK) JOIN MiscExtra me WITH (NOLOCK)
		ON (me.Number = m.Number) AND (me.Title like '%' + @SOFT_RECALL_TITLE + '%')
		WHERE (m.number = @NUMBER) AND
		      (DATEDIFF(DAY, m.Received, GETDATE()) between @SOFT_RECALL_FLOOR AND
		                                                    @SOFT_RECALL_CEILING) AND
		      (ISNULL(m.ID1, '') <> me.TheData)
	END

IF (SELECT (DATEDIFF(DAY, Received, GETDATE())) 
    FROM MASTER 
    WHERE NUMBER = @Number) BETWEEN @SOFT_RECALL_FLOOR AND @SOFT_RECALL_CEILING
	BEGIN
		SET @COMMENT = 'EXCHANGE: TOYOTA A1R(SOFT) RECALL REQUEST HAS BEEN ISSUED.' 
		INSERT INTO NOTES(NUMBER, CTL, CREATED, USER0, [ACTION], RESULT, COMMENT, SEQ, ISPRIVATE)
		VALUES(@NUMBER, 'CTL', GetDate(), 'EXCHNG', 'STATUS', 'CHANGE', @COMMENT, NULL, NULL)
	END


-- IF NO ERROR...
IF @@ERROR = 0
	BEGIN
		COMMIT TRANSACTION
	END
ELSE -- AN ERROR OCCURED.
	BEGIN
		ROLLBACK TRANSACTION
	END


-- DELETE THE SPECIFIC MISC EXTRA NO MATTER WHAT.
DELETE FROM MISCEXTRA 
WHERE Number = @NUMBER AND 
      TITLE LIKE '%' + @SOFT_RECALL_TITLE + '%' AND
      TheData = @SOFT_RECALL_STATUS
GO
