CREATE TYPE [dbo].[CbrDataTbl] AS TABLE
(
[FileId] [int] NULL,
[CbrEnabled] [bit] NULL,
[CbrPortfolioType] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CbrAccountType] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CbrMinBalance] [money] NULL,
[CbrWaitDays] [int] NULL,
[CbrCreditorClass] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CbrDefaultOriginalCreditor] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CbrUseAccountOriginalCreditor] [bit] NULL,
[CbrUseCustomerOriginalCreditor] [bit] NULL,
[CbrPrincipalOnly] [bit] NULL,
[CbrIncludeCodebtors] [bit] NULL,
[CbrDeleteReturns] [bit] NULL,
[CbrIndustryCode] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CbrCustomercode] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CbrCustomerid] [int] NULL,
[CbrCustomerName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CbrCustomerCreditorClass] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CbrCustomerOriginalCreditor] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CbrParmAbbrev] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CbrValueLookup] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Customer] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[number] [int] NULL,
[Status] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[qlevel] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[receiveddate] [datetime] NULL,
[DelinquencyDate] [datetime] NULL,
[OriginalPrincipal] [money] NULL,
[original] [money] NULL,
[CurrentPrincipal] [money] NULL,
[CurrentBalance] [money] NULL,
[lastpaid] [datetime] NULL,
[OriginalCreditor] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ContractDate] [datetime] NULL,
[ConsumerAccountNumber] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SettlementID] [int] NULL,
[soldportfolio] [int] NULL,
[purchasedportfolio] [int] NULL,
[lastpaidamt] [money] NULL,
[CLIDLP] [datetime] NULL,
[specialnote] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cbrPrevent] [bit] NULL,
[CbrOverride] [bit] NULL,
[cbrextenddays] [int] NULL,
[PrvCbrException] [int] NULL,
[PersonalReceivership_Amortization] [bit] NULL,
[StatusCbrReport] [bit] NULL,
[StatusCbrDelete] [bit] NULL,
[IsBankruptcy] [bit] NULL,
[IsDeceased] [bit] NULL,
[IsDisputed] [bit] NULL,
[StatusIsPIF] [bit] NULL,
[StatusIsSIF] [bit] NULL,
[StatusIsFraud] [bit] NULL,
[McoChargeoffnumber] [int] NULL,
[McoSecondaryAgencyIdenitifier] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[McoSecondaryAccountNumber] [varchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[McoMortgageIdentificationNumber] [varchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[McoTermsDuration] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[McoClosedDate] [datetime] NULL,
[McoChargeOffStatus] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[McoChargeOffAmount] [money] NULL,
[McoPaymentHistoryProfile] [varchar] (24) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[McoPaymentHistoryDate] [datetime] NULL,
[McoHighestCredit] [money] NULL,
[McoCreditLimit] [money] NULL,
[McoSpecialComment] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[McoComplianceCondition] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[portfolioid] [int] NULL,
[AimGroupSeller] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AimGroupBuyer] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PortfolioSoldDate] [datetime] NULL,
[debtornumber] [int] NULL,
[PrimaryDebtorID] [int] NULL,
[DebtorID] [int] NULL,
[Debtorseq] [int] NULL,
[Debtorname] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DebtorResponsible] [bit] NULL,
[CbrExclude] [bit] NULL,
[PrvDebtorExceptions] [int] NULL,
[IsBusiness] [bit] NULL,
[DebtorSSN] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DebtorStreet1] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DebtorStreet2] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DebtorCity] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DebtorState] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DebtorZipCode] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsAuthorizedAccountUser] [bit] NULL,
[bankruptdebtorid] [int] NULL,
[bankruptchapter] [tinyint] NULL,
[bankruptdateFiled] [datetime] NULL,
[bankruptdateNotice] [datetime] NULL,
[bankruptproofFiled] [datetime] NULL,
[bankruptdateTime341] [datetime] NULL,
[bankruptWithdrawnDate] [datetime] NULL,
[bankruptdischargeDate] [datetime] NULL,
[bankruptdismissalDate] [datetime] NULL,
[bankruptreaffirmDateFiled] [datetime] NULL,
[cccdebtorid] [int] NULL,
[CCCS] [bit] NULL,
[PrimaryDebtorDispute] [bit] NULL,
[datedeceased] [datetime] NULL,
[lastpaidnumber] [int] NULL,
[LastPaymentDate] [datetime] NULL,
[lastPaymentAmount] [money] NULL,
[payhistorydatepaid] [datetime] NULL,
[DebtorDOB] [datetime] NULL
)
GO
