CREATE TABLE [bck].[Payhistory_Remove_brianm_12052023_164212]
(
[historyid] [int] NOT NULL,
[number] [int] NULL,
[Seq] [int] NOT NULL,
[batchtype] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[matched] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ctl] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[customer] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sortdata] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[paytype] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[paymethod] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[systemmonth] [smallint] NULL,
[systemyear] [smallint] NULL,
[entered] [datetime] NULL,
[desk] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[checknbr] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[invoiced] [datetime] NULL,
[InvoiceSort] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InvoiceType] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InvoicePayType] [real] NULL,
[comment] [char] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[datepaid] [datetime] NOT NULL,
[totalpaid] [money] NOT NULL,
[paid1] [money] NOT NULL,
[paid2] [money] NOT NULL,
[paid3] [money] NOT NULL,
[paid4] [money] NOT NULL,
[paid5] [money] NOT NULL,
[paid6] [money] NOT NULL,
[paid7] [money] NOT NULL,
[paid8] [money] NOT NULL,
[paid9] [money] NOT NULL,
[paid10] [money] NOT NULL,
[fee1] [money] NOT NULL,
[fee2] [money] NOT NULL,
[fee3] [money] NOT NULL,
[fee4] [money] NOT NULL,
[fee5] [money] NOT NULL,
[fee6] [money] NOT NULL,
[fee7] [money] NOT NULL,
[fee8] [money] NOT NULL,
[fee9] [money] NOT NULL,
[fee10] [money] NOT NULL,
[balance] [money] NULL,
[balance1] [money] NULL,
[balance3] [money] NULL,
[balance4] [money] NULL,
[balance5] [money] NULL,
[balance6] [money] NULL,
[balance7] [money] NULL,
[balance8] [money] NULL,
[balance9] [money] NULL,
[balance10] [money] NULL,
[balance2] [money] NULL,
[BatchNumber] [float] NULL,
[UID] [int] NOT NULL,
[Invoice] [int] NULL,
[InvoiceFlags] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[OverPaidAmt] [money] NULL,
[ForwardeeFee] [money] NULL,
[ReverseOfUID] [int] NULL,
[AccruedSurcharge] [money] NULL,
[TransCost] [money] NULL,
[Tax] [money] NULL,
[AttorneyID] [int] NULL,
[CollectorFee] [money] NULL,
[PAIdentifier] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AIMAgencyId] [int] NULL,
[AIMDueAgency] [money] NULL,
[AIMAgencyFee] [money] NULL,
[FeeSched] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CollectorFeeSched] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PaidToDate] [money] NULL,
[IsFreeDemand] [bit] NOT NULL,
[IsCorrection] [bit] NOT NULL,
[CreatedBy] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Created] [datetime] NOT NULL,
[BatchPmtCreatedBy] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[BatchPmtCreated] [datetime] NOT NULL,
[datetimeentered] [datetime] NULL,
[CurrencyISO3] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AIMBatchId] [int] NULL,
[AIMSendingID] [int] NULL,
[SubBatchType] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PostDateUID] [int] NULL,
[PaymentLinkUID] [int] NULL,
[DebtorId] [int] NULL,
[Echo] [bit] NULL,
[Echoed] [datetime] NULL,
[EchoID] [int] NULL,
[PromiseAppliedAmt] [money] NULL,
[Reference] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
