CREATE TABLE [bck].[LetterRequest_Remove_brianm_12052023_164212]
(
[historyid] [int] NOT NULL,
[LetterRequestID] [int] NOT NULL,
[AccountID] [int] NOT NULL,
[CustomerCode] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LetterID] [int] NOT NULL,
[LetterCode] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateRequested] [datetime] NOT NULL,
[DateProcessed] [datetime] NOT NULL,
[JobName] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DueDate] [datetime] NOT NULL,
[AmountDue] [money] NOT NULL,
[UserName] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Suspend] [bit] NOT NULL,
[SifPmt1] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SifPmt2] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SifPmt3] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SifPmt4] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SifPmt5] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SifPmt6] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Manual] [bit] NOT NULL,
[AddEditMode] [bit] NOT NULL,
[Edited] [bit] NOT NULL,
[DocumentData] [varbinary] (max) NULL,
[Deleted] [bit] NOT NULL,
[CopyCustomer] [bit] NOT NULL,
[SaveImage] [bit] NOT NULL,
[ProcessingMethod] [int] NOT NULL,
[ErrorDescription] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateCreated] [datetime] NOT NULL,
[DateUpdated] [datetime] NOT NULL,
[SubjDebtorID] [int] NULL,
[SenderID] [int] NULL,
[RequesterID] [int] NULL,
[FutureID] [int] NOT NULL,
[RecipientDebtorID] [int] NULL,
[RecipientDebtorSeq] [tinyint] NULL,
[LtrSeriesQueueID] [int] NULL,
[SifPmt7] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SifPmt8] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SifPmt9] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SifPmt10] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SifPmt11] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SifPmt12] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SifPmt13] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SifPmt14] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SifPmt15] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SifPmt16] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SifPmt17] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SifPmt18] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SifPmt19] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SifPmt20] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SifPmt21] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SifPmt22] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SifPmt23] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SifPmt24] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PdcId] [int] NULL
) ON [PRIMARY]
GO
