CREATE TABLE [bck].[Bankruptcy_Remove_brianm_12052023_164212]
(
[historyid] [int] NOT NULL,
[BankruptcyID] [int] NOT NULL,
[AccountID] [int] NOT NULL,
[DebtorID] [int] NOT NULL,
[Chapter] [tinyint] NULL,
[DateFiled] [datetime] NULL,
[CaseNumber] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CourtCity] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CourtDistrict] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CourtDivision] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CourtPhone] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CourtStreet1] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CourtStreet2] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CourtState] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CourtZipcode] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Trustee] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TrusteeStreet1] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TrusteeStreet2] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TrusteeCity] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TrusteeState] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TrusteeZipcode] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TrusteePhone] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Has341Info] [bit] NOT NULL,
[DateTime341] [datetime] NULL,
[Location341] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Comments] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Status] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TransmittedDate] [smalldatetime] NULL,
[ConvertedFrom] [tinyint] NULL,
[DateNotice] [datetime] NULL,
[ProofFiled] [datetime] NULL,
[DischargeDate] [datetime] NULL,
[DismissalDate] [datetime] NULL,
[ConfirmationHearingDate] [datetime] NULL,
[HasAsset] [bit] NULL,
[Reaffirm] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReaffirmDateFiled] [datetime] NULL,
[ReaffirmAmount] [money] NULL,
[ReaffirmTerms] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VoluntaryDate] [datetime] NULL,
[VoluntaryAmount] [money] NULL,
[VoluntaryTerms] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SurrenderDate] [datetime] NULL,
[SurrenderMethod] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AuctionHouse] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AuctionDate] [datetime] NULL,
[AuctionAmount] [money] NULL,
[AuctionFee] [money] NULL,
[AuctionAmountApplied] [money] NULL,
[SecuredAmount] [money] NULL,
[SecuredPercentage] [smallmoney] NULL,
[UnsecuredAmount] [money] NULL,
[UnsecuredPercentage] [smallmoney] NULL,
[ctl] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WithdrawnDate] [datetime] NULL,
[CreatedDate] [datetime] NOT NULL,
[UpdatedDate] [datetime] NULL
) ON [PRIMARY]
GO
