CREATE TABLE [dbo].[Services_IdInfo_RealEstate]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[RequestID] [int] NULL,
[PID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FirstName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MiddleInitial] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GenerationalSuffix] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Owner2FirstName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Owner2MiddleName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Owner2LastName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SpouseFirstName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SpouseMiddleName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SpouseLastName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MailAddressFull] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StreetNumber] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PreDirection] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StreetName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StreetSuffix] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PostDirection] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UnitDesignator] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UnitNumber] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[City] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[State] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Zipcode] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SiteAddressFull] [varchar] (300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SiteStreetNumber] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SitePreDirection] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SiteStreetName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SiteStreetSuffix] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SitePostDirection] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SiteUnitDesignator] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SiteUnitNumber] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SiteCity] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SiteState] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SiteZipcode] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LoadAmount1] [money] NULL,
[LoanAmount2] [money] NULL,
[LoanAmount3] [money] NULL,
[HomeEquity] [money] NULL,
[SiteFIPSCounty] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SiteFIPSState] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PurchaseAmount] [money] NULL,
[PurchaseDate] [datetime] NULL,
[LotSize] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AssessedValue] [money] NULL,
[MarketValue] [money] NULL,
[SquareFeet] [decimal] (18, 2) NULL,
[BusinessName] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SiteFIPSCountyResolved] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PropertyOwnership] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ParcelIDNumber] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Services_IdInfo_RealEstate] ADD CONSTRAINT [PK_Services_IdInfo_RealEstate] PRIMARY KEY CLUSTERED ([ID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
