CREATE TABLE [dbo].[SERVICES_INNOVIS_COLLECTIONBUNDLE_BANKODECEASED]
(
[Id] [int] NOT NULL IDENTITY(1, 1),
[RequestID] [int] NOT NULL,
[BKY_Case_Number] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BKY_Debtor_First_Name] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BKY_Debtor_Middle_Name] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BKY_Debtors_Secondary_Surname] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BKY_Debtors_Last_Name] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BKY_Debtors_Generation_Code] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BKY_Debtors_Address] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BKY_Debtors_2nd_Line_of_Address] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BKY_Debtors_City] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BKY_Debtors_State] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BKY_Debtors_Zip] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BKY_Debtors_Zip+4] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BKY_Debtors_SSN] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BKY_Filing_Type] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BKY_Filing_Status] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BKY_Filing_Status_Description] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BKY_Filing_Date] [datetime] NULL,
[BKY_Status_Date] [datetime] NULL,
[BKY_Converted_Date] [datetime] NULL,
[BKY_Meeting_of_Creditors_Date] [datetime] NULL,
[BKY_Meeting_of_Creditors_Time] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BKY_Meeting_of_Creditors_Location] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BKY_Judge] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BKY_Attorney_Name] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BKY_Attorney_Street_Address] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BKY_Attorney_City] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BKY_Attorney_State] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BKY_Attorney_ZIP_Code] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BKY_Attorney_Phone_Number] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BKY_Court_Name] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BKY_Court_Street_Address] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BKY_Court_2nd_Line_of_Address] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BKY_Court_City] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BKY_Court_State] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BKY_Court_ZIP_Code] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BKY_Court_Phone_Number] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BKY_Trustee_Name] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BKY_Trustee_Street_Address] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BKY_Trustee_2nd_Line_of_Address] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BKY_Trustee_City] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BKY_Trustee_State] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BKY_Trustee_ZIP_Code] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BKY_Trustee_Phone_Number] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BKY_Match_Code] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DEC_Social_Security_Number] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DEC_First_Name_of_Decedent] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DEC_Last_Name_of_Decedent] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DEC_State_Last_Residence] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DEC_ZIP_Code_Last_Residence] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DEC_Date_of_Birth] [datetime] NULL,
[DEC_Date_of_Death] [datetime] NULL,
[DEC_Deceased_Match_Code] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SERVICES_INNOVIS_COLLECTIONBUNDLE_BANKODECEASED] ADD CONSTRAINT [PK_SERVICES_INNOVIS_COLLECTIONBUNDLE_BANKODECEASED] PRIMARY KEY CLUSTERED ([Id]) ON [PRIMARY]
GO
