CREATE TABLE [dbo].[Services_TLO_Bankruptcy]
(
[Id] [int] NOT NULL IDENTITY(1, 1),
[RequestID] [int] NOT NULL,
[Chapter] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CaseNumber] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FileDate] [datetime] NULL,
[DischargeDate] [datetime] NULL,
[ClosedDate] [datetime] NULL,
[NoticeType] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AttorneyName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AttorneyStreet1] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AttorneyStreet2] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AttorneyCity] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AttorneyState] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AttorneyZip] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AttorneyPhone] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CourtDistrict] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CourtDivision] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CourtStreet1] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CourtStreet2] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CourtCity] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CourtState] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CourtZip] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CourtPhone] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrusteeName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrusteeStreet1] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrusteeStreet2] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrusteeCity] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrusteeState] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrusteeZip] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrusteePhone] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TLOFirstName] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TLOMiddleName] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TLOLastName] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TLOSuffix] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TLOSSN] [varchar] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TLOStreet1] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TLOStreet2] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TLOCity] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TLOState] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TLOZip] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DismissedDate] [datetime] NULL,
[TransferredDate] [datetime] NULL,
[PriDebtorFullName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PriDebtorPhone] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PriDebtorSSN] [varchar] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SecDebtorFullName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SecDebtorFullAddr] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SecDebtorPhone] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SecDebtorSSN] [varchar] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SecDebtorAka1] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BankruptcyFlag] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Bky341Date] [datetime] NULL,
[Bky341Time] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Bky341FullAddr] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VoluntaryFlag] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AssetsIndicator] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OriginalChapter] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ConvertedChapter] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UpdatedDate] [datetime] NULL,
[JudgeInitials] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CourtName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProSeIndicator] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LawFirm] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BarDate] [datetime] NULL,
[MatchCodes] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Services_TLO_Bankruptcy] ADD CONSTRAINT [PK_Services_TLO_Bankruptcy] PRIMARY KEY CLUSTERED ([Id]) ON [PRIMARY]
GO
