CREATE TABLE [dbo].[cbr_metro2_file_trailer]
(
[cbr_metro2_file_trailerId] [int] NOT NULL IDENTITY(1, 1),
[FileId] [int] NOT NULL,
[SetupId] [int] NOT NULL,
[ReservedByte21] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TotalBase] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TotalStatusCodeDF] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TotalJ1] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TotalJ2] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BlockCount] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TotalStatusCodeDA] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TotalStatusCode05] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TotalStatusCode11] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TotalStatusCode13] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TotalStatusCode61] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TotalStatusCode62] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TotalStatusCode63] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TotalStatusCode64] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TotalStatusCode65] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TotalStatusCode71] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TotalStatusCode78] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TotalStatusCode80] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TotalStatusCode82] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TotalStatusCode83] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TotalStatusCode84] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TotalStatusCode88] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TotalStatusCode89] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TotalStatusCode93] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TotalStatusCode94] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TotalStatusCode95] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TotalStatusCode96] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TotalStatusCode97] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TotalEcoaCodeZ] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TotalN1] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TotalK1] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TotalK2] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TotalK3] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TotalK4] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TotalL1] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TotalSSNJ1] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TotalSSNJ2] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TotalDOB] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TotalDOBBase] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TotalDOBJ1] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TotalDOBJ2] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TotalPhones] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReservedByte408] [varchar] (19) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RecordDescriptorWord] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[cbr_metro2_file_trailer] ADD CONSTRAINT [PK_cbr_metro2_file_trailer] PRIMARY KEY CLUSTERED ([cbr_metro2_file_trailerId]) ON [PRIMARY]
GO
EXEC sp_addextendedproperty N'MS_Description', N'Unique File Id', 'SCHEMA', N'dbo', 'TABLE', N'cbr_metro2_file_trailer', 'COLUMN', N'FileId'
GO
