CREATE TABLE [dbo].[ZipCodesProbate]
(
[ZipCode] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[City] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[State] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[County] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AreaCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CityType] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CityAliasAbbreviation] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CityAliasName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Latitude] [float] NULL,
[Longitude] [float] NULL,
[TimeZone] [float] NULL,
[Elevation] [float] NULL,
[CountyFIPS] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DayLightSaving] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PreferredLastLineKey] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ClassificationCode] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MultiCounty] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StateFIPS] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CityStateKey] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CityAliasCode] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PrimaryRecord] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CityMixedCase] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CityAliasMixedCase] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StateANSI] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CountyANSI] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FacilityCode] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CityDeliveryIndicator] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CarrierRouteRateSortation] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FinanceNumber] [float] NULL,
[UniqueZIPName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
