CREATE TABLE [dbo].[tempcbrAccountHistory]
(
[recordID] [int] NULL,
[fileID] [int] NULL,
[dateReported] [datetime] NULL,
[accountID] [int] NULL,
[customerID] [int] NULL,
[primaryDebtorID] [int] NULL,
[portfolioType] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[accountType] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[accountStatus] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[originalLoan] [money] NULL,
[actualPayment] [money] NULL,
[currentBalance] [money] NULL,
[amountPastDue] [money] NULL,
[termsDuration] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[specialComment] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[openDate] [datetime] NULL,
[billingDate] [datetime] NULL,
[delinquencyDate] [datetime] NULL,
[closedDate] [datetime] NULL,
[lastPaymentDate] [datetime] NULL,
[originalCreditor] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[creditorClassification] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ConsumerAccountNumber] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ChargeOffAmount] [money] NULL,
[PaymentHistoryProfile] [varchar] (24) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PaymentHistoryDate] [datetime] NULL,
[CreditLimit] [money] NULL,
[SecondaryAgencyIdenitifier] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SecondaryAccountNumber] [varchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MortgageIdentificationNumber] [varchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PortfolioIndicator] [int] NULL,
[SoldToPurchasedFrom] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[complianceCondition] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PendingComplianceCondition] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
