CREATE TABLE [dbo].[NewBizBMasterDiscover]
(
[number] [int] NOT NULL,
[link] [int] NULL,
[desk] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__NewBizBMas__desk__0D5574B5] DEFAULT (0),
[Name] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Street1] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Street2] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[City] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[State] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Zipcode] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ctl] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[other] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MR] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[account] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[homephone] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[workphone] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[specialnote] [varchar] (75) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[received] [datetime] NULL,
[closed] [datetime] NULL,
[returned] [datetime] NULL,
[lastpaid] [datetime] NULL,
[lastpaidamt] [money] NULL,
[lastinterest] [datetime] NULL,
[interestrate] [money] NULL,
[worked] [datetime] NULL,
[userdate1] [datetime] NULL,
[userdate2] [datetime] NULL,
[userdate3] [datetime] NULL,
[contacted] [datetime] NULL,
[status] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[customer] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSN] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[original] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__origi__0E4998EE] DEFAULT (0),
[original1] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__origi__0F3DBD27] DEFAULT (0),
[original2] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__origi__1031E160] DEFAULT (0),
[original3] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__origi__11260599] DEFAULT (0),
[original4] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__origi__121A29D2] DEFAULT (0),
[original5] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__origi__130E4E0B] DEFAULT (0),
[original6] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__origi__14027244] DEFAULT (0),
[original7] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__origi__14F6967D] DEFAULT (0),
[original8] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__origi__15EABAB6] DEFAULT (0),
[original9] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__origi__16DEDEEF] DEFAULT (0),
[original10] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__origi__17D30328] DEFAULT (0),
[Accrued2] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__Accru__18C72761] DEFAULT (0),
[Accrued10] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__Accru__19BB4B9A] DEFAULT (0),
[paid] [money] NOT NULL CONSTRAINT [DF__NewBizBMas__paid__1AAF6FD3] DEFAULT (0),
[paid1] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__paid1__1BA3940C] DEFAULT (0),
[paid2] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__paid2__1C97B845] DEFAULT (0),
[paid3] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__paid3__1D8BDC7E] DEFAULT (0),
[paid4] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__paid4__1E8000B7] DEFAULT (0),
[paid5] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__paid5__1F7424F0] DEFAULT (0),
[paid6] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__paid6__20684929] DEFAULT (0),
[paid7] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__paid7__215C6D62] DEFAULT (0),
[paid8] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__paid8__2250919B] DEFAULT (0),
[paid9] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__paid9__2344B5D4] DEFAULT (0),
[paid10] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__paid1__2438DA0D] DEFAULT (0),
[current0] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__curre__252CFE46] DEFAULT (0),
[current1] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__curre__2621227F] DEFAULT (0),
[current2] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__curre__271546B8] DEFAULT (0),
[current3] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__curre__28096AF1] DEFAULT (0),
[current4] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__curre__28FD8F2A] DEFAULT (0),
[current5] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__curre__29F1B363] DEFAULT (0),
[current6] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__curre__2AE5D79C] DEFAULT (0),
[current7] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__curre__2BD9FBD5] DEFAULT (0),
[current8] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__curre__2CCE200E] DEFAULT (0),
[current9] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__curre__2DC24447] DEFAULT (0),
[current10] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__curre__2EB66880] DEFAULT (0),
[attorney] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[assignedattorney] [datetime] NULL,
[promamt] [money] NULL,
[promdue] [datetime] NULL,
[sifpct] [money] NULL,
[queue] [varchar] (26) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[qflag] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[qdate] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[qlevel] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[qtime] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[extracodes] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Salary] [money] NULL,
[feecode] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[clidlc] [datetime] NULL,
[clidlp] [datetime] NULL,
[seq] [int] NULL,
[Pseq] [int] NOT NULL CONSTRAINT [DF__NewBizBMas__Pseq__2FAA8CB9] DEFAULT (0),
[Branch] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__NewBizBMa__Branc__309EB0F2] DEFAULT (0),
[Finders] [datetime] NULL,
[COMPLETE1] [datetime] NULL,
[Complete2] [datetime] NULL,
[DESK1] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DESK2] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Full0] [datetime] NULL,
[TotalViewed] [int] NOT NULL,
[TotalWorked] [int] NOT NULL,
[TotalContacted] [int] NOT NULL,
[nsf] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HasBigNote] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FirstDesk] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FirstReceived] [datetime] NULL,
[AgencyFlag] [tinyint] NULL,
[AgencyCode] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FeeSchedule] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustDivision] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustDistrict] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustBranch] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Delinquencydate] [datetime] NULL,
[CurrencyType] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DOB] [datetime] NULL,
[sysmonth] [tinyint] NULL,
[SysYear] [smallint] NULL,
[DMDateStamp] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__NewBizBMa__DMDat__3192D52B] DEFAULT (''),
[id1] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[id2] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PurchasedPortfolio] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SoldPortfolio] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OriginalCreditor] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AttorneyID] [int] NULL,
[BPDate] [datetime] NULL,
[NSFDate] [datetime] NULL,
[ContractDate] [datetime] NULL,
[ChargeOffDate] [datetime] NULL,
[ShouldQueue] [bit] NOT NULL CONSTRAINT [DF__NewBizBMa__Shoul__3286F964] DEFAULT (1),
[RestrictedAccess] [bit] NOT NULL CONSTRAINT [DF__NewBizBMa__Restr__337B1D9D] DEFAULT (0),
[LinkDriver] [bit] NOT NULL CONSTRAINT [DF__NewBizBMa__LinkD__346F41D6] DEFAULT (1),
[Score] [smallint] NULL,
[Salesman1ID] [int] NOT NULL CONSTRAINT [DF__NewBizBMa__Sales__3563660F] DEFAULT (0),
[Salesman2ID] [int] NOT NULL CONSTRAINT [DF__NewBizBMa__Sales__36578A48] DEFAULT (0),
[Salesman3ID] [int] NOT NULL CONSTRAINT [DF__NewBizBMa__Sales__374BAE81] DEFAULT (0),
[AIMAgency] [int] NULL,
[AIMAssigned] [datetime] NULL,
[cbrPrevent] [bit] NOT NULL CONSTRAINT [DF__NewBizBMa__cbrPr__383FD2BA] DEFAULT (0),
[cbrException] [smallint] NOT NULL CONSTRAINT [DF__NewBizBMa__cbrEx__3933F6F3] DEFAULT (0),
[cbrExtendDays] [int] NULL,
[clialp] [money] NULL,
[clialc] [money] NULL,
[cbrOverride] [bit] NOT NULL CONSTRAINT [DF__NewBizBMa__cbrOv__3A281B2C] DEFAULT (0),
[viewed] [datetime] NULL,
[QueueHold] [datetime] NULL,
[Secured] [bit] NOT NULL CONSTRAINT [DF__NewBizBMa__Secur__3B1C3F65] DEFAULT (0),
[PreviousCreditor] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StatuteDate] [datetime] NULL,
[AttorneyLawList] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AttorneyStatus] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ClassOfBusiness] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ClaimType] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AttorneyAccountID] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InterestBuckets] [smallint] NULL,
[BlanketSIFOverride] [float] NULL
) ON [PRIMARY]
GO
