CREATE TABLE [dbo].[Service_CPE_BU_72007]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[RequestId] [int] NULL,
[SH01] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FirstName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MiddleName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Prefix] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Suffix] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MaternalName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AliasName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HouseNumber] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Predirection] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StreetName] [varchar] (27) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Postdirection] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StreetType] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ApartmentNumber] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[City] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[State] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ZipCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AddressDateReported] [datetime] NULL,
[PreviousHouseNumber] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PreviousStreetName] [varchar] (27) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PreviousPreDirection] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PreviousPostdirection] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PreviousStreetType] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PreviousApartmentNumber] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PreviousCity] [varchar] (27) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PreviousState] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PreviousZipCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PreviousAddressDateReported] [datetime] NULL,
[2ndPreviousHouseNumber] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[2ndPreviousPredirection] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[2ndPreviousStreetName] [varchar] (27) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[2ndPreviousPostdirection] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[2ndPreviousStreetType] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[2ndPreviousApartmentNumber] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[2ndPreviousCity] [varchar] (27) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[2ndPreviousState] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[2ndPreviousZipCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SocialSecurityNumber] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateOfBirth] [datetime] NULL,
[PhoneNumber] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PhoneAreaCode] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PhonePrivateNumberIndicator] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EmploymentSegment] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EmploymentName] [varchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SourceIndicator] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Occupation] [varchar] (22) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateHired] [datetime] NULL,
[DateSeperated] [datetime] NULL,
[DateVerified] [datetime] NULL,
[DateVerifiedCode] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Income] [money] NULL,
[PayBasis] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PreviousEmploymentSegment] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PreviousEmployerName] [varchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PreviousSourceIndicator] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PreviousOccupation] [varchar] (22) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PreviousDateHired] [datetime] NULL,
[PreviousDateSeperated] [datetime] NULL,
[PreviousDateVerified] [datetime] NULL,
[PreviousDateVerifiedCode] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PreviousIncome] [money] NULL,
[PreviousPayBasis] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DeceasedFlag] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BankruptcyFlag] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FrozenFlagIndicator] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
