CREATE TABLE [dbo].[Services_TransUnion_TFC]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[RequestId] [int] NULL,
[UserReferenceNumber] [varchar] (24) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RequestType] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FirstName] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MiddleName] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastName] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Suffix] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AddressNumber] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PreDirectionalCode] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StreetName] [varchar] (27) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PostDirectionalCode] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StreetTypeCode] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UnitNumber] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[City] [varchar] (27) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[State] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ZIPCode] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PhoneNumber] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SocialSecurityNumber] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SubscriberMarketArea] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SubscriberSubmarketArea] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SubscriberIndustryCode] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MemberCode] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FILLER1] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FILLER2] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AccountBalance] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PortfolioType] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProcessingDate] [datetime] NULL,
[NewInquiryFlag] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NewAddressFlag] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NewEmploymentFlag] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NewPhoneNumberFlag] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BankcardRecoveryModelIncreaseFlag] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BankcardRecoveryModelDecreaseFlag] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Recovery10ModelIncreaseFlag] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Recovery10ModelDecreaseFlag] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Recovery20ModelIncreaseFlag] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Recovery20ModelDecreaseFlag] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NewBankcardTradeFlag] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NewBankruptcyPublicRecordFlag] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NewMortgageTradeFlag] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IncreaseinOpentoBuyBankcardFlag] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NewForeclosureTradeFlag] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NewPaidChargeOffFlag] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NewPaidCollectionFlag] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NewFraudAlertFlag] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NewDeceasedIndicatorFlag] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FILLER] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateofInquiry] [datetime] NULL,
[InquiryCustomerName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KOB] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InquiryAddressNumber] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InquiryPreDirectionalCode] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InquiryStreetTypeCode] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InquiryStreetName] [varchar] (28) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InquiryPostDirectionalCode] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InquiryUnitTypeCode] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InquiryUnitNumber] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InquiryCity] [varchar] (28) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InquiryState] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InquiryZIPCode] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InquiryExtendedZIPCode] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InquiryPhoneNumber] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InquiryEmployer] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NewAddressHouseNumber] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NewAddressPre-DirectionalCode] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NewAddressStreetTypeCode] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NewAddressStreetName] [varchar] (28) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NewAddressPost-DirectionalCode] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NewAddressUnitTypeCode] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NewAddressUnitNumber] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NewAddressCity] [varchar] (28) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NewAddressState] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NewAddressZIPCode] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NewAddressExtendedZIPCode] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NewEmployerName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NewEmployerCity] [varchar] (27) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NewEmployerState] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NewPhoneNumber1] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NewPhoneNumber2] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BankcardRecoveryScore] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BankcardRecoveryScoreChange] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Recovery10Score] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Recovery10ScoreChange] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Recovery20Score] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Recovery20ScoreChange] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NewBankcardTradeAccountType] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NewBankcardTradeAccountDateOpened] [datetime] NULL,
[NewBankcardTradeAccountBalance] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NewBankcardTradeAccountHighCredit] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NewBankcardTradeCreditLimit] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NewBankruptcyPublicRecordCode] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NewBankruptcyReportingSubscriber] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NewBankruptcyDocketNumber] [varchar] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NewBankruptcyCourtLocationCity] [varchar] (27) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NewBankruptcyCourtLocationState] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NewMortgageTradeAccountType] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NewMortgageTradeAccountDateOpened] [datetime] NULL,
[NewMortgageTradeAccountBalance] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NewMortgageTradeAccountHighCredit] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NewMortgageTradeCreditLimit] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Totaldollarsopentobuy] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Totalopentobuypercentage] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NewForeclosureTradeAccountType] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NewForeclosureTradeAccountDateOpened] [datetime] NULL,
[NewForeclosureTradeAccountBalance] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NewForeclosureTradeAccountHighCredit] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NewForeclosureTradeCreditLimit] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NewPaidChargeOffTradeAccountType] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NewPaidChargeOffTradeAccountDateOpened] [datetime] NULL,
[NewPaidChargeOffTradeAccountDateVerified] [datetime] NULL,
[NewPaidChargeOffTradeAccountBalance] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NewPaidChargeOffTradeAccountHighCredit] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NewPaidChargeOffTradeCreditLimit] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NewPaidChargeOffTradeCurrentMOP] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NewPaidCollectionAccountType] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NewPaidCollectionAccountDateOpened] [datetime] NULL,
[NewPaidCollectionAccountDateVerified] [datetime] NULL,
[NewPaidCollectionAccountBalance] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NewPaidCollectionAccountHighCredit] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NewPaidCollectionCreditLimit] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NewPaidCollectionCurrentMOP] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DecedentsSSN] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DecedentsDOB] [datetime] NULL,
[DeceasedDateofClaim] [datetime] NULL,
[DecedentsLastName] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DecedentsFirstName] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Services_TransUnion_TFC] ADD CONSTRAINT [PK_Services_TransUnion_TFC] PRIMARY KEY CLUSTERED ([ID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
