CREATE TABLE [dbo].[NewBizBDebtorsDiscover]
(
[Number] [int] NULL,
[Seq] [int] NULL,
[Name] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Street1] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Street2] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[City] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[State] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Zipcode] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HomePhone] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WorkPhone] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSN] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MR] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OtherName] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DOB] [datetime] NULL,
[JobName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[JobAddr1] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Jobaddr2] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[JobCSZ] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[JobMemo] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Relationship] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Spouse] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SpouseJobName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SpouseJobAddr1] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SpouseJobAddr2] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SpouseJobCSZ] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SpouseJobMemo] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SpouseHomePhone] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SpouseWorkPhone] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SpouseResponsible] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Pager] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OtherPhone1] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OtherPhoneType] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OtherPhone2] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OtherPhone2Type] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OtherPhone3] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OtherPhone3Type] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DebtorMemo] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[language] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DLNum] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fax] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Email] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateCreated] [datetime] NOT NULL CONSTRAINT [DF__NewBizBDe__DateC__02D7E642] DEFAULT (getdate()),
[DateUpdated] [datetime] NOT NULL CONSTRAINT [DF__NewBizBDe__DateU__03CC0A7B] DEFAULT (getdate()),
[Country] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lastName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[firstName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[middleName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[suffix] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[isBusiness] [bit] NOT NULL CONSTRAINT [DF__NewBizBDe__isBus__04C02EB4] DEFAULT (0),
[isParsed] [bit] NOT NULL CONSTRAINT [DF__NewBizBDe__isPar__05B452ED] DEFAULT (0),
[cbrException] [smallint] NOT NULL CONSTRAINT [DF__NewBizBDe__cbrEx__06A87726] DEFAULT (0),
[cbrExclude] [bit] NOT NULL CONSTRAINT [DF__NewBizBDe__cbrEx__079C9B5F] DEFAULT (0),
[Responsible] [bit] NOT NULL CONSTRAINT [DF__NewBizBDe__Respo__0890BF98] DEFAULT (1),
[USPSKeyLine] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EarlyTimeZone] [int] NULL,
[LateTimeZone] [int] NULL,
[businessName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[prefix] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[gender] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__NewBizBDe__gende__0984E3D1] DEFAULT ('U'),
[ObservesDST] [bit] NOT NULL CONSTRAINT [DF__NewBizBDe__Obser__0A79080A] DEFAULT (1),
[RegionCode] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[County] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TimeZoneOverride] [bit] NOT NULL CONSTRAINT [DF__NewBizBDe__TimeZ__0B6D2C43] DEFAULT (0),
[ISHOMEOWNER] [bit] NULL
) ON [PRIMARY]
GO
