CREATE TABLE [dbo].[RPmtType]
(
[number] [int] NULL,
[paytype] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[paymethod] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[batchtype] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[account] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[customer] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[entered] [datetime] NULL,
[datepaid] [datetime] NULL,
[paid1] [money] NULL,
[paid2] [money] NULL,
[paid3] [money] NULL,
[paid4] [money] NULL,
[paid5] [money] NULL,
[paid6] [money] NULL,
[paid8] [money] NULL,
[fee1] [money] NULL,
[fee2] [money] NULL,
[fee3] [money] NULL,
[fee4] [money] NULL,
[fee5] [money] NULL,
[fee6] [money] NULL,
[fee8] [money] NULL,
[UID] [int] NULL,
[BeginDate] [datetime] NULL,
[EndDate] [datetime] NULL,
[CalculatedField] [numeric] (10, 2) NULL,
[TranType] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ChgType] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AmtPU] [money] NULL,
[AmtPC] [money] NULL,
[AmtOther] [money] NULL,
[AgencyFee] [money] NULL
) ON [PRIMARY]
GO
