CREATE TABLE [dbo].[Attorney_StairStep]
(
[StairStepId] [int] NOT NULL IDENTITY(1, 1),
[BatchFileHistoryId] [int] NULL,
[AttorneyId] [int] NULL,
[TotalNumberPlaced] [int] NULL,
[TotalDollarsPlaced] [money] NULL,
[Adjustments] [money] NULL,
[TotalFees] [money] NULL,
[DatePlaced] [datetime] NULL,
[Month1] [money] NULL CONSTRAINT [DF__Attorney___Month__4055F5CE] DEFAULT ((0)),
[Month2] [money] NULL CONSTRAINT [DF__Attorney___Month__414A1A07] DEFAULT ((0)),
[Month3] [money] NULL CONSTRAINT [DF__Attorney___Month__423E3E40] DEFAULT ((0)),
[Month4] [money] NULL CONSTRAINT [DF__Attorney___Month__43326279] DEFAULT ((0)),
[Month5] [money] NULL CONSTRAINT [DF__Attorney___Month__442686B2] DEFAULT ((0)),
[Month6] [money] NULL CONSTRAINT [DF__Attorney___Month__451AAAEB] DEFAULT ((0)),
[Month7] [money] NULL CONSTRAINT [DF__Attorney___Month__460ECF24] DEFAULT ((0)),
[Month8] [money] NULL CONSTRAINT [DF__Attorney___Month__4702F35D] DEFAULT ((0)),
[Month9] [money] NULL CONSTRAINT [DF__Attorney___Month__47F71796] DEFAULT ((0)),
[Month10] [money] NULL CONSTRAINT [DF__Attorney___Month__48EB3BCF] DEFAULT ((0)),
[Month11] [money] NULL CONSTRAINT [DF__Attorney___Month__49DF6008] DEFAULT ((0)),
[Month12] [money] NULL CONSTRAINT [DF__Attorney___Month__4AD38441] DEFAULT ((0)),
[Month13] [money] NULL CONSTRAINT [DF__Attorney___Month__4BC7A87A] DEFAULT ((0)),
[Month14] [money] NULL CONSTRAINT [DF__Attorney___Month__4CBBCCB3] DEFAULT ((0)),
[Month15] [money] NULL CONSTRAINT [DF__Attorney___Month__4DAFF0EC] DEFAULT ((0)),
[Month16] [money] NULL CONSTRAINT [DF__Attorney___Month__4EA41525] DEFAULT ((0)),
[Month17] [money] NULL CONSTRAINT [DF__Attorney___Month__4F98395E] DEFAULT ((0)),
[Month18] [money] NULL CONSTRAINT [DF__Attorney___Month__508C5D97] DEFAULT ((0)),
[Month19] [money] NULL CONSTRAINT [DF__Attorney___Month__518081D0] DEFAULT ((0)),
[Month20] [money] NULL CONSTRAINT [DF__Attorney___Month__5274A609] DEFAULT ((0)),
[Month21] [money] NULL CONSTRAINT [DF__Attorney___Month__5368CA42] DEFAULT ((0)),
[Month22] [money] NULL CONSTRAINT [DF__Attorney___Month__545CEE7B] DEFAULT ((0)),
[Month23] [money] NULL CONSTRAINT [DF__Attorney___Month__555112B4] DEFAULT ((0)),
[Month24] [money] NULL CONSTRAINT [DF__Attorney___Month__564536ED] DEFAULT ((0)),
[Month99] [money] NULL CONSTRAINT [DF__Attorney___Month__57395B26] DEFAULT ((0)),
[TotalCollected] [money] NULL,
[PlacementSysMonth] [int] NULL,
[PlacementSysYear] [int] NULL,
[Customer] [char] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BatchID] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Attorney_StairStep] ADD CONSTRAINT [PK_Attorney_StairStep] PRIMARY KEY CLUSTERED ([StairStepId]) ON [PRIMARY]
GO
