CREATE TABLE [dbo].[NewBizBMasterFirstData]
(
[number] [int] NOT NULL,
[link] [int] NULL,
[desk] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__NewBizBMas__desk__701A1789] DEFAULT ((0)),
[Name] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Street1] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Street2] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[City] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[State] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Zipcode] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ctl] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[other] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MR] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[account] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[homephone] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[workphone] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[specialnote] [varchar] (75) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[received] [datetime] NULL,
[closed] [datetime] NULL,
[returned] [datetime] NULL,
[lastpaid] [datetime] NULL,
[lastpaidamt] [money] NULL,
[lastinterest] [datetime] NULL,
[interestrate] [money] NULL,
[worked] [datetime] NULL,
[userdate1] [datetime] NULL,
[userdate2] [datetime] NULL,
[userdate3] [datetime] NULL,
[contacted] [datetime] NULL,
[status] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[customer] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSN] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[original] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__origi__710E3BC2] DEFAULT ((0)),
[original1] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__origi__72025FFB] DEFAULT ((0)),
[original2] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__origi__72F68434] DEFAULT ((0)),
[original3] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__origi__73EAA86D] DEFAULT ((0)),
[original4] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__origi__74DECCA6] DEFAULT ((0)),
[original5] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__origi__75D2F0DF] DEFAULT ((0)),
[original6] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__origi__76C71518] DEFAULT ((0)),
[original7] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__origi__77BB3951] DEFAULT ((0)),
[original8] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__origi__78AF5D8A] DEFAULT ((0)),
[original9] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__origi__79A381C3] DEFAULT ((0)),
[original10] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__origi__7A97A5FC] DEFAULT ((0)),
[Accrued2] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__Accru__7B8BCA35] DEFAULT ((0)),
[Accrued10] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__Accru__7C7FEE6E] DEFAULT ((0)),
[paid] [money] NOT NULL CONSTRAINT [DF__NewBizBMas__paid__7D7412A7] DEFAULT ((0)),
[paid1] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__paid1__7E6836E0] DEFAULT ((0)),
[paid2] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__paid2__7F5C5B19] DEFAULT ((0)),
[paid3] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__paid3__00507F52] DEFAULT ((0)),
[paid4] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__paid4__0144A38B] DEFAULT ((0)),
[paid5] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__paid5__0238C7C4] DEFAULT ((0)),
[paid6] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__paid6__032CEBFD] DEFAULT ((0)),
[paid7] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__paid7__04211036] DEFAULT ((0)),
[paid8] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__paid8__0515346F] DEFAULT ((0)),
[paid9] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__paid9__060958A8] DEFAULT ((0)),
[paid10] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__paid1__06FD7CE1] DEFAULT ((0)),
[current0] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__curre__07F1A11A] DEFAULT ((0)),
[current1] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__curre__08E5C553] DEFAULT ((0)),
[current2] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__curre__09D9E98C] DEFAULT ((0)),
[current3] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__curre__0ACE0DC5] DEFAULT ((0)),
[current4] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__curre__0BC231FE] DEFAULT ((0)),
[current5] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__curre__0CB65637] DEFAULT ((0)),
[current6] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__curre__0DAA7A70] DEFAULT ((0)),
[current7] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__curre__0E9E9EA9] DEFAULT ((0)),
[current8] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__curre__0F92C2E2] DEFAULT ((0)),
[current9] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__curre__1086E71B] DEFAULT ((0)),
[current10] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__curre__117B0B54] DEFAULT ((0)),
[attorney] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[assignedattorney] [datetime] NULL,
[promamt] [money] NULL,
[promdue] [datetime] NULL,
[sifpct] [money] NULL,
[queue] [varchar] (26) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[qflag] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[qdate] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[qlevel] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[qtime] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[extracodes] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Salary] [money] NULL,
[feecode] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[clidlc] [datetime] NULL,
[clidlp] [datetime] NULL,
[seq] [int] NULL,
[Pseq] [int] NOT NULL CONSTRAINT [DF__NewBizBMas__Pseq__126F2F8D] DEFAULT ((0)),
[Branch] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__NewBizBMa__Branc__136353C6] DEFAULT ((0)),
[Finders] [datetime] NULL,
[COMPLETE1] [datetime] NULL,
[Complete2] [datetime] NULL,
[DESK1] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DESK2] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Full0] [datetime] NULL,
[TotalViewed] [int] NOT NULL,
[TotalWorked] [int] NOT NULL,
[TotalContacted] [int] NOT NULL,
[nsf] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HasBigNote] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FirstDesk] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FirstReceived] [datetime] NULL,
[AgencyFlag] [tinyint] NULL,
[AgencyCode] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FeeSchedule] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustDivision] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustDistrict] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustBranch] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Delinquencydate] [datetime] NULL,
[CurrencyType] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DOB] [datetime] NULL,
[sysmonth] [tinyint] NULL,
[SysYear] [smallint] NULL,
[DMDateStamp] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__NewBizBMa__DMDat__145777FF] DEFAULT (''),
[id1] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[id2] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PurchasedPortfolio] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SoldPortfolio] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OriginalCreditor] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AttorneyID] [int] NULL,
[BPDate] [datetime] NULL,
[NSFDate] [datetime] NULL,
[ContractDate] [datetime] NULL,
[ChargeOffDate] [datetime] NULL,
[ShouldQueue] [bit] NOT NULL CONSTRAINT [DF__NewBizBMa__Shoul__154B9C38] DEFAULT ((1)),
[RestrictedAccess] [bit] NOT NULL CONSTRAINT [DF__NewBizBMa__Restr__163FC071] DEFAULT ((0)),
[LinkDriver] [bit] NOT NULL CONSTRAINT [DF__NewBizBMa__LinkD__1733E4AA] DEFAULT ((1)),
[Score] [smallint] NULL,
[Salesman1ID] [int] NOT NULL CONSTRAINT [DF__NewBizBMa__Sales__182808E3] DEFAULT ((0)),
[Salesman2ID] [int] NOT NULL CONSTRAINT [DF__NewBizBMa__Sales__191C2D1C] DEFAULT ((0)),
[Salesman3ID] [int] NOT NULL CONSTRAINT [DF__NewBizBMa__Sales__1A105155] DEFAULT ((0)),
[AIMAgency] [int] NULL,
[AIMAssigned] [datetime] NULL,
[cbrPrevent] [bit] NOT NULL CONSTRAINT [DF__NewBizBMa__cbrPr__1B04758E] DEFAULT ((0)),
[cbrException] [smallint] NOT NULL CONSTRAINT [DF__NewBizBMa__cbrEx__1BF899C7] DEFAULT ((0)),
[cbrExtendDays] [int] NULL,
[clialp] [money] NULL,
[clialc] [money] NULL,
[cbrOverride] [bit] NOT NULL CONSTRAINT [DF__NewBizBMa__cbrOv__1CECBE00] DEFAULT ((0)),
[viewed] [datetime] NULL,
[QueueHold] [datetime] NULL,
[Secured] [bit] NOT NULL CONSTRAINT [DF__NewBizBMa__Secur__1DE0E239] DEFAULT ((0)),
[PreviousCreditor] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StatuteDate] [datetime] NULL,
[AttorneyLawList] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AttorneyStatus] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ClassOfBusiness] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ClaimType] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AttorneyAccountID] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InterestBuckets] [smallint] NULL,
[BlanketSIFOverride] [float] NULL
) ON [PRIMARY]
GO
