CREATE TABLE [dbo].[CustomerBCK11052021]
(
[customer] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[status] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SelectedFlag] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Name] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Street1] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Street2] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[City] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[State] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Zipcode] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Contact] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[phone] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lettercode] [varchar] (75) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[penalty] [money] NULL,
[badcheck] [money] NULL,
[ctl] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fees] [money] NULL,
[collections] [money] NULL,
[mtdnumberplaced] [float] NULL,
[mtddollarsplaced] [money] NULL,
[ytdnumberplaced] [float] NULL,
[ytddollarsplaced] [money] NULL,
[mtdpdcfees] [money] NULL,
[mtdpdccollections] [money] NULL,
[mtdfees] [money] NULL,
[mtdcollections] [money] NULL,
[ytdfees] [money] NULL,
[ytdcollections] [money] NULL,
[bankcode] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[attorneycode] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[salesmancode] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sifinfo] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[workinfo] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[miscinfo] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[invoicetype] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[invoicefreq] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[invoicesort] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[invoicemethod] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[options] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[option1] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fax] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Half] [money] NULL,
[Close_] [money] NULL,
[FaxNumber] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AutoRecallStatus] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AutoRecallDays] [int] NULL,
[AutoRecallFlag] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[locate] [money] NULL,
[SpecialCode] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerGroup] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Full0] [money] NULL,
[AmtDueClient] [smallint] NULL,
[feecode2] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[feedays] [int] NULL,
[cob] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[company] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastInvoiceAttempt] [datetime] NULL,
[RemitMethod] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ABARoutingNum] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BankAcctNum] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustGroup] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CheckHoldDays] [smallint] NULL,
[InvShowRcvd] [bit] NULL,
[InvShowBal] [bit] NULL,
[CCostPct] [float] NULL,
[CCostBucket] [tinyint] NULL,
[FeeSchedule] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsPODCust] [bit] NULL,
[CBRRptType] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CBRMinBal] [money] NULL,
[CBRWaitDays] [int] NULL,
[UseEquifax] [bit] NULL,
[UseTransUnion] [bit] NULL,
[UseExperian] [bit] NULL,
[UseInnovis] [bit] NULL,
[eMail] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CBRClass] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShowReverseOfDate] [bit] NULL,
[OnlineCheckFee] [money] NULL,
[AlphaCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sweep] [bit] NULL,
[SweepDays] [int] NULL,
[SweepDaysPaid] [int] NULL,
[SweepMinBalance] [money] NULL,
[SweepDesk] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DefaultDesk] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FaxID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CbrAcctRtnSendDel] [bit] NULL,
[CustomDate1] [datetime] NULL,
[CustomDate2] [datetime] NULL,
[CustomDate3] [datetime] NULL,
[CustomDate4] [datetime] NULL,
[CustomDate5] [datetime] NULL,
[CustomDate6] [datetime] NULL,
[CustomDate7] [datetime] NULL,
[CustomDate8] [datetime] NULL,
[CustomDate9] [datetime] NULL,
[CustomOption1] [bit] NULL,
[CustomOption2] [bit] NULL,
[CustomOption3] [bit] NULL,
[CustomOption4] [bit] NULL,
[CustomOption5] [bit] NULL,
[CustomOption6] [bit] NULL,
[CustomOption7] [bit] NULL,
[CustomOption8] [bit] NULL,
[CustomOption9] [bit] NULL,
[CustomValue1] [int] NULL,
[CustomValue2] [int] NULL,
[CustomValue3] [int] NULL,
[CustomValue4] [int] NULL,
[CustomValue5] [int] NULL,
[CustomValue6] [int] NULL,
[CustomValue7] [int] NULL,
[CustomValue8] [int] NULL,
[CustomValue9] [int] NULL,
[LegalFeeSchedule] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CCustomerID] [int] NOT NULL,
[LetterDeliveryMethod] [int] NOT NULL,
[DateCreated] [datetime] NOT NULL,
[DateUpdated] [datetime] NOT NULL,
[FeeCode] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BlanketSif] [float] NULL,
[IsPrincipleCust] [bit] NOT NULL,
[CustomText1] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomText2] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomText3] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomText4] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomText5] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BankID] [int] NULL,
[DefaultInterest] [float] NOT NULL,
[InvShowOther] [bit] NULL,
[AcknowledgeNewBiz] [bit] NOT NULL,
[Salesman1ID] [int] NOT NULL,
[Salesman2ID] [int] NOT NULL,
[Salesman3ID] [int] NOT NULL,
[CollectorFeeSchedule] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CbrOriginalCreditor] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CbrAccountType] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CbrCreditorClass] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FeeCapAmount] [money] NOT NULL,
[FeeCapPercent] [real] NOT NULL,
[InvoiceReport] [varchar] (120) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CreatedBy] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[UpdatedBy] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[FreeDemandDays] [tinyint] NOT NULL,
[FreeDemandBatchTypes] [tinyint] NOT NULL,
[CultureCode] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InterestBuckets] [smallint] NULL,
[Priority] [tinyint] NOT NULL
) ON [PRIMARY]
GO
