CREATE TABLE [dbo].[Services_FirstData_FastBatch_Bankruptcy]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[RequestId] [int] NULL,
[Matchtyperesultcode] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TypeofRecord] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AssociationCode1Single2Joint] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CourtID] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CourtName] [varchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CourtAddress] [varchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CourtCity] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CourtState] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CourtZip] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CourtPhoneNumber] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OriginalChapter] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CaseNumber] [varchar] (17) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Filler] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FilingDateMMDDYYYY] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DispositionCodeDDischargeRDismissal] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ConvertedChapter] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DismissalDischargeDateMMDDYYYY] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Liability] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Assets] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AttorneyFirm] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AttorneyName] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AttorneyAddress] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AttorneyCity] [varchar] (24) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AttorneyState] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AttorneyZip] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AttorneyPhone] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AssetsAvailableYYesNNoUUnknown] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Scheduled341DateMMDDYYYY] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Scheduled341TimeHHMM] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Scheduled341Location] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[JudgesInitials] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OtherCaseNumber] [varchar] (13) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DefendantSSN] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DefendantName] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DefendantGenerationCode] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DefendantAddress] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DefendantCity] [varchar] (24) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DefendantState] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DefendantZip] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrusteeName] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrusteeAddress] [varchar] (28) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrusteeCity] [varchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrusteeState] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrusteeZip] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrusteePhone] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BankruptcyAddedUpdatedDateMMDDYYYY] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BankruptcyFileTypeCode] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CodefendantSSNNumber] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CodefendantName] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CodefendantAddress] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CodefendantCity] [varchar] (24) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CodefendantState] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CodefendantZip] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ConfirmationHearingDateYYMMDD] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OriginalAssetsAvailable] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProofofClaimDateYYMMDD] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ComplaintDeadlineDateYYMMDD] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Services_FirstData_FastBatch_Bankruptcy] ADD CONSTRAINT [PK_Services_FirstData_FastBatch_Bankruptcy] PRIMARY KEY CLUSTERED ([ID]) ON [PRIMARY]
GO
