CREATE TABLE [dbo].[Custom_Marblehead_Debtor_Info]
(
[id] [int] NOT NULL IDENTITY(1, 1),
[lastname] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[firstname] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[taxid] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[city] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[state] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[zip] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[homephone] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[officephone] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[validaddress] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[filler] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ref1acctnum] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ref1lastname] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ref1firstname] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ref1address1] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ref1address2] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ref1city] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ref1state] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ref1zip] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ref1homephone] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ref1officephone] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ref2acctnum] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ref2lastname] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ref2firstname] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ref2address1] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ref2address2] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ref2city] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ref2state] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ref2zip] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ref2homephone] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ref2officephone] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[skipind] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[defforbcode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[defforbbegindate] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[defforbenddate] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[emailaddress] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bortotalpastdue] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lastcontactdate] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[filler1] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[birthdate] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cellphone] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[filler2] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[borinfocode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[filler3] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Custom_Marblehead_Debtor_Info] ADD CONSTRAINT [PK_Custom_Marblehead_Debtor_Info] PRIMARY KEY CLUSTERED ([id]) ON [PRIMARY]
GO
