CREATE TABLE [dbo].[SERVICES_INNOVIS_COLLECTIONBUNDLE]
(
[Id] [int] NOT NULL IDENTITY(1, 1),
[RequestID] [int] NOT NULL,
[Loan_Number] [int] NULL,
[Innovis_Account_Number] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Client_Key] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[First_Name] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Middle_Name] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Last_Name] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSN] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Street_Address_1] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Street_Address_2] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[City] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[State] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Zip] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Prior1_Street_Address_1] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Prior1_Street_Address_2] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Prior1_City] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Prior1_State] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Prior1_Zip] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Prior2_Street_Address_1] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Prior2_Street_Address_2] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Prior2_City] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Prior2_State] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Prior2_Zip] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Prior3_Street_Address_1] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Prior3_Street_Address_2] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Prior3_City] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Prior3_State] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Prior3_Zip] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Prior4_Street_Address_1] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Prior4_Street_Address_2] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Prior4_City] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Prior4_State] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Prior4_Zip] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Phone_Number1] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Phone_Number2] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Phone_Number3] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Phone_Number4] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Phone_Number5] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Phone_Number6] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Phone_Number7] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Phone_Number8] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Phone_Number9] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Phone_Number10] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Phone_Number11] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Phone_Number12] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Phone_Number13] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Phone_Number14] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Phone_Number15] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Phone_Number16] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Phone_Number17] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Phone_Number18] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Phone_Number19] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Phone_Number20] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Phone_Number21] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Phone_Number22] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Phone_Number23] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Phone_Number24] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Phone_Number25] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Phone_Number26] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Phone_Number27] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Phone_Number28] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Phone_Number29] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Phone_Number30] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Phone_Number31] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Phone_Number32] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Agreement_Date] [datetime] NULL,
[Reported_First_Name] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported_Middle_Name] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported_Last_Name] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported_Name_Active_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported_Name_Total_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported_Name_1st_Reported_Date] [datetime] NULL,
[Reported_Name_Last_Reported_Date] [datetime] NULL,
[Reported_Street_Address_1] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported_Street_Address_2] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported_City] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported_State] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported_Zip] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported_Address_Active_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported_Address_Total_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported_Address_1st_Reported_Date] [datetime] NULL,
[Reported_Address_Last_Reported_Date] [datetime] NULL,
[Reported2_Street_Address_1] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported2_Street_Address_2] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported2_City] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported2_State] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported2_Zip] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported2_Address_Active_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported2_Address_Total_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported2_Address_1st_Reported_Date] [datetime] NULL,
[Reported2_Address_Last_Reported_Date] [datetime] NULL,
[Reported3_Street_Address_1] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported3_Street_Address_2] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported3_City] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported3_State] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported3_Zip] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported3_Address_Active_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported3_Address_Total_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported3_Address_1st_Reported_Date] [datetime] NULL,
[Reported3_Address_Last_Reported_Date] [datetime] NULL,
[Reported4_Street_Address_1] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported4_Street_Address_2] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported4_City] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported4_State] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported4_Zip] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported4_Address_Active_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported4_Address_Total_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported4_Address_1st_Reported_Date] [datetime] NULL,
[Reported4_Address_Last_Reported_Date] [datetime] NULL,
[Reported5_Street_Address_1] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported5_Street_Address_2] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported5_City] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported5_State] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported5_Zip] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported5_Address_Active_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported5_Address_Total_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported5_Address_1st_Reported_Date] [datetime] NULL,
[Reported5_Address_Last_Reported_Date] [datetime] NULL,
[Reported6_Street_Address_1] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported6_Street_Address_2] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported6_City] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported6_State] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported6_Zip] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported6_Address_Active_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported6_Address_Total_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported6_Address_1st_Reported_Date] [datetime] NULL,
[Reported6_Address_Last_Reported_Date] [datetime] NULL,
[Reported7_Street_Address_1] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported7_Street_Address_2] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported7_City] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported7_State] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported7_Zip] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported7_Address_Active_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported7_Address_Total_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported7_Address_1st_Reported_Date] [datetime] NULL,
[Reported7_Address_Last_Reported_Date] [datetime] NULL,
[Reported8_Street_Address_1] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported8_Street_Address_2] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported8_City] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported8_State] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported8_Zip] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported8_Address_Active_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported8_Address_Total_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported8_Address_1st_Reported_Date] [datetime] NULL,
[Reported8_Address_Last_Reported_Date] [datetime] NULL,
[Reported9_Street_Address_1] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported9_Street_Address_2] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported9_City] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported9_State] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported9_Zip] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported9_Address_Active_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported9_Address_Total_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported9_Address_1st_Reported_Date] [datetime] NULL,
[Reported9_Address_Last_Reported_Date] [datetime] NULL,
[Reported10_Street_Address_1] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported10_Street_Address_2] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported10_City] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported10_State] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported10_Zip] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported10_Address_Active_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported10_Address_Total_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported10_Address_1st_Reported_Date] [datetime] NULL,
[Reported10_Address_Last_Reported_Date] [datetime] NULL,
[Reported11_Street_Address_1] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported11_Street_Address_2] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported11_City] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported11_State] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported11_Zip] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported11_Address_Active_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported11_Address_Total_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported11_Address_1st_Reported_Date] [datetime] NULL,
[Reported11_Address_Last_Reported_Date] [datetime] NULL,
[Reported12_Street_Address_1] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported12_Street_Address_2] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported12_City] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported12_State] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported12_Zip] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported12_Address_Active_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported12_Address_Total_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported12_Address_1st_Reported_Date] [datetime] NULL,
[Reported12_Address_Last_Reported_Date] [datetime] NULL,
[Reported13_Street_Address_1] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported13_Street_Address_2] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported13_City] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported13_State] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported13_Zip] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported13_Address_Active_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported13_Address_Total_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported13_Address_1st_Reported_Date] [datetime] NULL,
[Reported13_Address_Last_Reported_Date] [datetime] NULL,
[Reported14_Street_Address_1] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported14_Street_Address_2] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported14_City] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported14_State] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported14_Zip] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported14_Address_Active_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported14_Address_Total_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported14_Address_1st_Reported_Date] [datetime] NULL,
[Reported14_Address_Last_Reported_Date] [datetime] NULL,
[Reported15_Street_Address_1] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported15_Street_Address_2] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported15_City] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported15_State] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported15_Zip] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported15_Address_Active_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported15_Address_Total_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported15_Address_1st_Reported_Date] [datetime] NULL,
[Reported15_Address_Last_Reported_Date] [datetime] NULL,
[Reported16_Street_Address_1] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported16_Street_Address_2] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported16_City] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported16_State] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported16_Zip] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported16_Address_Active_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported16_Address_Total_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported16_Address_1st_Reported_Date] [datetime] NULL,
[Reported16_Address_Last_Reported_Date] [datetime] NULL,
[Reported17_Street_Address_1] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported17_Street_Address_2] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported17_City] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported17_State] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported17_Zip] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported17_Address_Active_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported17_Address_Total_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported17_Address_1st_Reported_Date] [datetime] NULL,
[Reported17_Address_Last_Reported_Date] [datetime] NULL,
[Reported18_Street_Address_1] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported18_Street_Address_2] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported18_City] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported18_State] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported18_Zip] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported18_Address_Active_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported18_Address_Total_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported18_Address_1st_Reported_Date] [datetime] NULL,
[Reported18_Address_Last_Reported_Date] [datetime] NULL,
[Reported19_Street_Address_1] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported19_Street_Address_2] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported19_City] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported19_State] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported19_Zip] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported19_Address_Active_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported19_Address_Total_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported19_Address_1st_Reported_Date] [datetime] NULL,
[Reported19_Address_Last_Reported_Date] [datetime] NULL,
[Reported20_Street_Address_1] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported20_Street_Address_2] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported20_City] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported20_State] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported20_Zip] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported20_Address_Active_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported20_Address_Total_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported20_Address_1st_Reported_Date] [datetime] NULL,
[Reported20_Address_Last_Reported_Date] [datetime] NULL,
[Reported1_Phone_Number] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported1_Phone_Type] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported1_Phone_Active_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported1_Phone_Total_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported1_Phone_1st_Reported_Date] [datetime] NULL,
[Reported1_Phone_Last_Reported_Date] [datetime] NULL,
[Reported2_Phone_Number] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported2_Phone_Type] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported2_Phone_Active_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported2_Phone_Total_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported2_Phone_1st_Reported_Date] [datetime] NULL,
[Reported2_Phone_Last_Reported_Date] [datetime] NULL,
[Reported3_Phone_Number] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported3_Phone_Type] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported3_Phone_Active_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported3_Phone_Total_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported3_Phone_1st_Reported_Date] [datetime] NULL,
[Reported3_Phone_Last_Reported_Date] [datetime] NULL,
[Reported4_Phone_Number] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported4_Phone_Type] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported4_Phone_Active_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported4_Phone_Total_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported4_Phone_1st_Reported_Date] [datetime] NULL,
[Reported4_Phone_Last_Reported_Date] [datetime] NULL,
[Reported5_Phone_Number] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported5_Phone_Type] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported5_Phone_Active_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported5_Phone_Total_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported5_Phone_1st_Reported_Date] [datetime] NULL,
[Reported5_Phone_Last_Reported_Date] [datetime] NULL,
[Reported6_Phone_Number] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported6_Phone_Type] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported6_Phone_Active_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported6_Phone_Total_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported6_Phone_1st_Reported_Date] [datetime] NULL,
[Reported6_Phone_Last_Reported_Date] [datetime] NULL,
[Reported7_Phone_Number] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported7_Phone_Type] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported7_Phone_Active_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported7_Phone_Total_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported7_Phone_1st_Reported_Date] [datetime] NULL,
[Reported7_Phone_Last_Reported_Date] [datetime] NULL,
[Reported8_Phone_Number] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported8_Phone_Type] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported8_Phone_Active_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported8_Phone_Total_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported8_Phone_1st_Reported_Date] [datetime] NULL,
[Reported8_Phone_Last_Reported_Date] [datetime] NULL,
[Reported9_Phone_Number] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported9_Phone_Type] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported9_Phone_Active_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported9_Phone_Total_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported9_Phone_1st_Reported_Date] [datetime] NULL,
[Reported9_Phone_Last_Reported_Date] [datetime] NULL,
[Reported10_Phone_Number] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported10_Phone_Type] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported10_Phone_Active_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported10_Phone_Total_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported10_Phone_1st_Reported_Date] [datetime] NULL,
[Reported10_Phone_Last_Reported_Date] [datetime] NULL,
[Reported11_Phone_Number] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported11_Phone_Type] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported11_Phone_Active_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported11_Phone_Total_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported11_Phone_1st_Reported_Date] [datetime] NULL,
[Reported11_Phone_Last_Reported_Date] [datetime] NULL,
[Reported12_Phone_Number] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported12_Phone_Type] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported12_Phone_Active_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported12_Phone_Total_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported12_Phone_1st_Reported_Date] [datetime] NULL,
[Reported12_Phone_Last_Reported_Date] [datetime] NULL,
[Reported13_Phone_Number] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported13_Phone_Type] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported13_Phone_Active_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported13_Phone_Total_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported13_Phone_1st_Reported_Date] [datetime] NULL,
[Reported13_Phone_Last_Reported_Date] [datetime] NULL,
[Reported14_Phone_Number] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported14_Phone_Type] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported14_Phone_Active_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported14_Phone_Total_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported14_Phone_1st_Reported_Date] [datetime] NULL,
[Reported14_Phone_Last_Reported_Date] [datetime] NULL,
[Reported15_Phone_Number] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported15_Phone_Type] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported15_Phone_Active_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported15_Phone_Total_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported15_Phone_1st_Reported_Date] [datetime] NULL,
[Reported15_Phone_Last_Reported_Date] [datetime] NULL,
[Reported16_Phone_Number] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported16_Phone_Type] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported16_Phone_Active_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported16_Phone_Total_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported16_Phone_1st_Reported_Date] [datetime] NULL,
[Reported16_Phone_Last_Reported_Date] [datetime] NULL,
[Reported17_Phone_Number] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported17_Phone_Type] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported17_Phone_Active_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported17_Phone_Total_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported17_Phone_1st_Reported_Date] [datetime] NULL,
[Reported17_Phone_Last_Reported_Date] [datetime] NULL,
[Reported18_Phone_Number] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported18_Phone_Type] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported18_Phone_Active_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported18_Phone_Total_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported18_Phone_1st_Reported_Date] [datetime] NULL,
[Reported18_Phone_Last_Reported_Date] [datetime] NULL,
[Reported19_Phone_Number] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported19_Phone_Type] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported19_Phone_Active_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported19_Phone_Total_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported19_Phone_1st_Reported_Date] [datetime] NULL,
[Reported19_Phone_Last_Reported_Date] [datetime] NULL,
[Reported20_Phone_Number] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported20_Phone_Type] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported20_Phone_Active_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported20_Phone_Total_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported20_Phone_1st_Reported_Date] [datetime] NULL,
[Reported20_Phone_Last_Reported_Date] [datetime] NULL,
[Reported21_Phone_Number] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported21_Phone_Type] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported21_Phone_Active_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported21_Phone_Total_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported21_Phone_1st_Reported_Date] [datetime] NULL,
[Reported21_Phone_Last_Reported_Date] [datetime] NULL,
[Reported22_Phone_Number] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported22_Phone_Type] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported22_Phone_Active_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported22_Phone_Total_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported22_Phone_1st_Reported_Date] [datetime] NULL,
[Reported22_Phone_Last_Reported_Date] [datetime] NULL,
[Reported23_Phone_Number] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported23_Phone_Type] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported23_Phone_Active_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported23_Phone_Total_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported23_Phone_1st_Reported_Date] [datetime] NULL,
[Reported23_Phone_Last_Reported_Date] [datetime] NULL,
[Reported24_Phone_Number] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported24_Phone_Type] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported24_Phone_Active_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported24_Phone_Total_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported24_Phone_1st_Reported_Date] [datetime] NULL,
[Reported24_Phone_Last_Reported_Date] [datetime] NULL,
[Reported25_Phone_Number] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported25_Phone_Type] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported25_Phone_Active_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported25_Phone_Total_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported25_Phone_1st_Reported_Date] [datetime] NULL,
[Reported25_Phone_Last_Reported_Date] [datetime] NULL,
[Reported26_Phone_Number] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported26_Phone_Type] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported26_Phone_Active_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported26_Phone_Total_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported26_Phone_1st_Reported_Date] [datetime] NULL,
[Reported26_Phone_Last_Reported_Date] [datetime] NULL,
[Reported27_Phone_Number] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported27_Phone_Type] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported27_Phone_Active_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported27_Phone_Total_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported27_Phone_1st_Reported_Date] [datetime] NULL,
[Reported27_Phone_Last_Reported_Date] [datetime] NULL,
[Reported28_Phone_Number] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported28_Phone_Type] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported28_Phone_Active_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported28_Phone_Total_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported28_Phone_1st_Reported_Date] [datetime] NULL,
[Reported28_Phone_Last_Reported_Date] [datetime] NULL,
[Reported29_Phone_Number] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported29_Phone_Type] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported29_Phone_Active_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported29_Phone_Total_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported29_Phone_1st_Reported_Date] [datetime] NULL,
[Reported29_Phone_Last_Reported_Date] [datetime] NULL,
[Reported30_Phone_Number] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported30_Phone_Type] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported30_Phone_Active_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported30_Phone_Total_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported30_Phone_1st_Reported_Date] [datetime] NULL,
[Reported30_Phone_Last_Reported_Date] [datetime] NULL,
[Reported31_Phone_Number] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported31_Phone_Type] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported31_Phone_Active_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported31_Phone_Total_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported31_Phone_1st_Reported_Date] [datetime] NULL,
[Reported31_Phone_Last_Reported_Date] [datetime] NULL,
[Reported32_Phone_Number] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported32_Phone_Type] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported32_Phone_Active_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported32_Phone_Total_Sources] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reported32_Phone_1st_Reported_Date] [datetime] NULL,
[Reported32_Phone_Last_Reported_Date] [datetime] NULL,
[Input_Phone1] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Input_Phone_Type1] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Input_Phone2] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Input_Phone_Type2] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Input_Phone3] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Input_Phone_Type3] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Input_Phone4] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Input_Phone_Type4] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Input_Phone5] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Input_Phone_Type5] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Input_Phone6] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Input_Phone_Type6] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Input_Phone7] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Input_Phone_Type7] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Input_Phone8] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Input_Phone_Type8] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Input_Phone9] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Input_Phone_Type9] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Input_Phone10] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Input_Phone_Type10] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Input_Phone11] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Input_Phone_Type11] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Input_Phone12] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Input_Phone_Type12] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Input_Phone13] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Input_Phone_Type13] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Input_Phone14] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Input_Phone_Type14] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Input_Phone15] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Input_Phone_Type15] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Input_Phone16] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Input_Phone_Type16] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Input_Phone17] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Input_Phone_Type17] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Input_Phone18] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Input_Phone_Type18] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Input_Phone19] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Input_Phone_Type19] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Input_Phone20] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Input_Phone_Type20] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Input_Phone21] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Input_Phone_Type21] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Input_Phone22] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Input_Phone_Type22] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Input_Phone23] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Input_Phone_Type23] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Input_Phone24] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Input_Phone_Type24] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Input_Phone25] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Input_Phone_Type25] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Input_Phone26] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Input_Phone_Type26] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Input_Phone27] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Input_Phone_Type27] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Input_Phone28] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Input_Phone_Type28] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Input_Phone29] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Input_Phone_Type29] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Input_Phone30] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Input_Phone_Type30] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Input_Phone31] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Input_Phone_Type31] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SERVICES_INNOVIS_COLLECTIONBUNDLE] ADD CONSTRAINT [PK_SERVICES_INNOVIS_COLLECTIONBUNDLE] PRIMARY KEY CLUSTERED ([Id]) ON [PRIMARY]
GO
