CREATE TABLE [dbo].[Custom_UnionBank_Import_Dial_File]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[SystemNo] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PrinNo] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CollCode] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CHDAccountNo] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PrinName] [varchar] (26) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SpouseName] [varchar] (26) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CredBurFlag] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WorkPhone] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HomePhone] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ExtStatus] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IntStatus] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CurrBalance] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Creditline] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AmountDelq] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DaysDelq] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateLastPayment] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AmountLastPayment] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ZipCode] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreditScore] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RemoteNumber] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AuthFlag] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AddressLine1] [varchar] (26) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AddressLine2] [varchar] (26) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[City] [varchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[State] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ZipLast4] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GropMMBRTypeCD] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Filler] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Format] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PIID] [varchar] (19) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SocSecurityNo] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SecondarySocSecurityNo] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NextCyclDT] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Del1CYCAMT] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Del2CYCAMT] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Del3CYCAMT] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Del4CYCAMT] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Del5CYCAMT] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Del6CYCAMT] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Del7CYCAMT] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Del8CYCAMT] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OpenDate] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Custom_UnionBank_Import_Dial_File] ADD CONSTRAINT [PK_Custom_UnionBank_Import_Dial_File] PRIMARY KEY CLUSTERED ([ID]) ON [PRIMARY]
GO
