CREATE TABLE [dbo].[Services_SurePlacement_Bankrupt]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[RequestId] [int] NOT NULL,
[MatchType] [int] NULL,
[Screen] [int] NULL,
[CaseNumber] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Chapter] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ChapterCode] [int] NULL,
[FileDate] [datetime] NULL,
[StatusDate] [datetime] NULL,
[Disp] [varchar] (45) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DispCode] [int] NULL,
[Debtor1SSN] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Debtor1First] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Debtor1Middle] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Debtor1Last] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Debtor1Suffix] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Debtor1Address] [varchar] (55) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Debtor1City] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Debtor1State] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Debtor1Zipcode] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Debtor1AKAFirst] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Debtor1AKAMiddle] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Debtor1AKALast] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Debtor1AKA2First] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Debtor1AKA2Middle] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Debtor1AKA2Last] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Debtor2SSN] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Debtor2First] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Debtor2Middle] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Debtor2Last] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Debtor2Suffix] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Debtor2Address] [varchar] (55) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Debtor2City] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Debtor2State] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Debtor2Zipcode] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Debtor2AKAFirst] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Debtor2AKAMiddle] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Debtor2AKALast] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Debtor2AKA2First] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Debtor2AKA2Middle] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Debtor2AKA2Last] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BusinessName1] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BusinessName2] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CourtCode] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CityFiled] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StateFiled] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[County] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Judge] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LawFirm] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AttyName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AttyAddress1] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AttyAddress2] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AttyCity] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AttyState] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AttyZipcode] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AttyPhone] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrusteeName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrusteeAddress1] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrusteeAddress2] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrusteeCity] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrusteeState] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrusteeZipcode] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrusteePhone] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[341Date] [datetime] NULL,
[341Time] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[341Location] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[341City] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[341State] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[341Zipcode] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BarDate] [datetime] NULL,
[ECOACode] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Funds] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Services_SurePlacement_Bankrupt] ADD CONSTRAINT [PK_Services_SurePlacement_Bankrupt] PRIMARY KEY CLUSTERED ([ID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
