CREATE TABLE [dbo].[Services_VeriFacts_SkipTrace]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[RequestID] [int] NULL,
[LOCATEINDICATORCODE] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ACCTNUM] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[BATCH] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SSN] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[NAME] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ADDR1] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ADDR2] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CITY] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[STATE] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ZIP] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PHONE] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[EMPINF1] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[EMPINF2] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[EMPINF3] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[EMPCITY] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[EMPSTATE] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[EMPZIP] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[EMPPHONE] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[EMP21] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[EMP22] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[EMP23] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[EMP2CITY] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[EMP2STATE] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[EMP2ZIP] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[EMP2PHONE] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[LOCDATE] [datetime] NOT NULL,
[TR] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SK] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ACCTBAL] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[LOCATEFLAG] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[COMMENT1] [varchar] (70) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[COMMENT2] [varchar] (70) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[COMMENT3] [varchar] (70) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[COMMENT4] [varchar] (70) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[COMMENT5] [varchar] (70) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[COMMENT6] [varchar] (70) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[COMMENT7] [varchar] (70) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[COMMENT8] [varchar] (70) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[COMMENT9] [varchar] (70) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[COMMENT10] [varchar] (70) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[COMMENT11] [varchar] (70) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[COMMENT12] [varchar] (70) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[COMMENT13] [varchar] (70) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[COMMENT14] [varchar] (70) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[COMMENT15] [varchar] (70) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[COMMENT16] [varchar] (70) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[COMMENT17] [varchar] (70) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Services_VeriFacts_SkipTrace] ADD CONSTRAINT [PK_Services_VeriFacts_SkipTrace] PRIMARY KEY CLUSTERED ([ID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
