CREATE TABLE [dbo].[Services_LexisNexis_PropertyInfo]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[RequestId] [int] NULL,
[LNID] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ACCTNUMIN] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FNAMEIN] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LNAMEIN] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSNIN] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ARMATCH] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ARTAXF] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AROWN] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ARADDR] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ARCITY] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ARSTATE] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ARZIP] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ARMADDR] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ARMCITY] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ARMSTATE] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ARMZIP] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ARPRICE] [decimal] (15, 5) NULL,
[ARTVL] [decimal] (15, 5) NULL,
[ARAIV] [decimal] (15, 5) NULL,
[ARALV] [decimal] (15, 5) NULL,
[ARAYR] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ARAPN] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ARBKPG] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ARDOCNUM] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ARDOCTYP] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ARRCD] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AREXEMP] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ARUSE] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ARLGL] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ARMIV] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ARMLV] [decimal] (15, 5) NULL,
[ARMVY] [decimal] (15, 5) NULL,
[ARCHR] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ARREC] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ARRECDT] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ARTAPE] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ARTAX] [decimal] (15, 5) NULL,
[ARTRC] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ARTYR] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ARTAV] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ARTMV] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DDMATCH] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DDBUYER] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DDMADDR] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DDMCITY] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DDMSTATE] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DDMZIP] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DDADDR] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DDCITY] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DDSTATE] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DDZIP] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DDSELLER] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DDSADDR] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DDSCITY] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DDSSTATE] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DDSZIP] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DDSALEDT] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DDPRICE] [decimal] (15, 5) NULL,
[DDTLV] [decimal] (15, 5) NULL,
[DDAPN] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DDBKPG] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DDTYPE] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DDDOCNUM] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DDUSE] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DDLGL] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DDLENDER] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DDLNAMT] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DDLOT] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DDMAD] [varchar] (155) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DDPIT] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DDPBP] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DDPTR] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DDRATE] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DDRECDT] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DDTERM] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DDTITLE] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DDMORT] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MTMATCH] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MTBRW] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MTMADDR] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MTMCITY] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MTMSTATE] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MTMZIP] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MTADDR] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MTCITY] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MTSTATE] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MTZIP] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MTAMT] [decimal] (15, 5) NULL,
[MTINT] [decimal] (15, 5) NULL,
[MTIND] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MTAPN] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MTCHI] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MTDOCNUM] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MTDUEDT] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MTGDN] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MTLGL] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MTLTP] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MTLENDER] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MTLOANTP] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MTMRF] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MTTYPE] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MTMSA] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MTUSE] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MTRTCH] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MTRECDT] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MTFIN] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Services_LexisNexis_PropertyInfo] ADD CONSTRAINT [PK_Services_LexisNexis_PropertyInfo] PRIMARY KEY CLUSTERED ([ID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
