CREATE TABLE [dbo].[Custom_BrighTree_Import_NewBiz_File]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[CollectionType] [nvarchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreditBureau] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DebtorIdent] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreditorIdent] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreditorName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreditorAddress1] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreditorAddress2] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreditorCity] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreditorState] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreditorPostalCode] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreditorPhone] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreditorContactFirstName] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreditorContactLastName] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreditorContactPhone] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreditorContactExtension] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreditorContactFax] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreditorContactEmail] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PatientAccountNo] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PatientFirstName] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PatientLastName] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PatientBirthDate] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSPBusinessName] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSPFirstName] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSPLastName] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSPAddr1] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSPAddr2] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSPCity] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSPState] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSPPostalCode] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSPSSN] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSPPhone] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EmployerName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EmployerPhone] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SpouseFirstName] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SpouseLastName] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SpouseSSN] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SpouseEmployer] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SpouseEmployerPhone] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RelativeName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RelativePhone] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EmergencyContact] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EmergencyContactPhone] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Note1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Note2] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InsuranceName1] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InsuranceName2] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InsuranceName3] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OriginalAmount] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LateFee] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TotalDue] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ServiceDate] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InvoiceDate] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ServiceAmount] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ServiceDesc] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InvoiceNo] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BalanceDue] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastPayDate] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Custom_BrighTree_Import_NewBiz_File] ADD CONSTRAINT [PK_Custom_BrighTree_Import_NewBiz_File] PRIMARY KEY CLUSTERED ([ID]) ON [PRIMARY]
GO
