CREATE TABLE [dbo].[pdcdelkennyb20070206]
(
[UID] [int] NOT NULL IDENTITY(1, 1),
[number] [int] NULL,
[ctl] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PDC_Type] [tinyint] NULL,
[entered] [datetime] NULL,
[onhold] [datetime] NULL,
[processed1] [datetime] NULL,
[processedflag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[deposit] [datetime] NULL,
[amount] [money] NULL,
[checknbr] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SEQ] [int] NULL,
[LtrCode] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[nitd] [datetime] NULL,
[Desk] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[customer] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fill1] [char] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fill2] [char] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fill3] [char] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fill4] [char] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fill5] [char] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SurCharge] [money] NULL,
[Printed] [bit] NULL,
[ApprovedBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PromiseMode] [tinyint] NULL,
[ProjectedFee] [money] NULL,
[UseProjectedFee] [bit] NOT NULL,
[Active] [bit] NOT NULL,
[CollectorFee] [money] NULL,
[DateCreated] [datetime] NULL,
[DateUpdated] [datetime] NULL,
[CreatedBy] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PrintedDate] [datetime] NULL,
[NSFCount] [int] NULL,
[ProcessStatus] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
