CREATE TABLE [dbo].[Custom_AFF_Outsourcer_Address_Import]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[ADDRESSES_PLACEMENT_ADDRESSES] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ADDRESSES_OUTSOURCERACOUNTID] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ADDRESSES_ACCOUNTREF] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ADDRESSES_STREET1] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ADDRESSES_STREET2] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ADDRESSES_CITY] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ADDRESSES_STATE] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ADDRESSES_ZIPCODE] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ADDRESSES_COUNTRY] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ADDRESSES_ADDRESS_TYPE] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Custom_AFF_Outsourcer_Address_Import] ADD CONSTRAINT [PK_Custom_AFF_Outsourcer_Address_Import] PRIMARY KEY CLUSTERED ([ID]) ON [PRIMARY]
GO
