CREATE TABLE [dbo].[Custom_Equabli_Asset_Info]
(
[UID] [int] NOT NULL IDENTITY(1, 1),
[recordType] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[equabliAccountNumber] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[assetId] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[clientAccountNumber] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[equabliClientId] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[assetCategory] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[assetTypeCode] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[assetName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[vin] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[mileage] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bookValue] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bookValueDate] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[color] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[gpsStatus] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[opcode] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[licensePlate] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[gap] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[warranty] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[propertyAddressLine1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[propertyAddressLine2] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[propertyCountry] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[propertyCity] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[propertyState] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[propertyZipCode] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[filingCountyTownCity] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[oVCost] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[assetCompany] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[assetBranch] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[assetRouting] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[assetAcctno] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[assetPhone] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[assetFax] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[assetValue] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[assetParcel] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[assetOwner] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[assetOwnerSecondary] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[assetSaleDate] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[assetSalePrice] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[assetSellerName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[assetMortgageAmount] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[assetValueAssessed] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[assetMarketValue] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[assetLegalDescription] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[externalSystemId] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[assetYear] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[assetModel] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[assetVersion] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Custom_Equabli_Asset_Info] ADD CONSTRAINT [PK_Custom_Equabli_Asset_Info] PRIMARY KEY CLUSTERED ([UID]) ON [PRIMARY]
GO
