CREATE TABLE [dbo].[Services_DPE]
(
[Id] [int] NOT NULL IDENTITY(1, 1),
[RequestId] [int] NULL,
[Subcode] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FirstName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Balance] [money] NULL,
[AccountDate] [datetime] NULL,
[KeyCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SsnValidationResult] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SsnFraudCode] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SsnAppendResultCode] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BestNameAddressResultCode] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BestState] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BestDemoResultCode] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AddressFraudIndicator] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[YearOfBirth] [int] NULL,
[DwellingType] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateAddressFirstOpened] [datetime] NULL,
[DateAddressLastUpdate] [datetime] NULL,
[SsnDeceasedResultCode] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FileOnePhoneAppendResultCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FileOnePhoneLastUpdate] [datetime] NULL,
[FileTwoPhoneLastUpdate] [datetime] NULL,
[FileThreePhoneLastUpdate] [datetime] NULL,
[POEResultCode] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[POEDateToFile] [datetime] NULL,
[POEDateLastUpdated] [datetime] NULL,
[Model1Code] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Model1Score] [int] NULL,
[Model2Code] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Model2Score] [int] NULL,
[Model3Code] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Model3Score] [int] NULL,
[33CollectionAttribResultCode] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q24DEC] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q24BKC7] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q24BKC11] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q24BKC13] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q24LSAT1] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q24DG01] [int] NULL,
[Q24TD01] [int] NULL,
[Q24TD02] [int] NULL,
[Q24TD03] [int] NULL,
[Q24TD04] [int] NULL,
[Q24TC01] [int] NULL,
[Q24TC02] [int] NULL,
[Q24TAL15] [money] NULL,
[Q24TMT11] [money] NULL,
[Q24TMT12] [money] NULL,
[Q24THE11] [money] NULL,
[Q24THE12] [money] NULL,
[Q24TIN12] [money] NULL,
[Q24TRV11] [money] NULL,
[Q24TRV12] [money] NULL,
[Q24TRV13] [money] NULL,
[Q24TBC13] [money] NULL,
[Q24TBC14] [money] NULL,
[Q24TAU12] [money] NULL,
[Q24TAU13] [money] NULL,
[Q24TAE12] [money] NULL,
[Q24TAE13] [money] NULL,
[Q24TAL21] [int] NULL,
[Q24TRV22] [int] NULL,
[Q24TIB22] [int] NULL,
[Q24TFN31] [int] NULL,
[Q24IAL01] [int] NULL,
[Q24IAL02] [int] NULL,
[BankruptcyResultCode] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BKStatusCode] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BKStatusDate] [datetime] NULL,
[BKOrigFilingDate] [datetime] NULL,
[AdditionalNamesResultCode] [int] NULL,
[AdditionalAddressResultCode] [int] NULL,
[Address1FirstReportedDate] [datetime] NULL,
[Adderss1LastUpdatedDate] [datetime] NULL,
[Address2FirstReportedDate] [datetime] NULL,
[Address2LastUpdatedDate] [datetime] NULL,
[Address3FirstReportedDate] [datetime] NULL,
[Address3LastUpdatedDate] [datetime] NULL,
[FCRAConsumerStmtIndicator] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCRANumBKWithdrawn] [int] NULL,
[FCRAChp7Bk] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCRAChp11Bk] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCRAChp12Bk] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCRAChp13Bk] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCRAAccountsClosed] [int] NULL,
[FCRAAccountsDisputed] [int] NULL,
[AddressMismatch] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Services_DPE] ADD CONSTRAINT [PK_Services_DPE] PRIMARY KEY CLUSTERED ([Id]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
