CREATE TABLE [dbo].[Custom_Equabli_Compliance_Info]
(
[UID] [int] NOT NULL IDENTITY(1, 1),
[recordType] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[equabliAccountNumber] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[clientAccountNumber] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[equabliClientId] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[clientConsumerNumber] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[equabliConsumerId] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[complianceType] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[complianceSubType] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[description] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[filingDate] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[complianceChannel] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[complianceCreationMode] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[complianceStatus] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[resolutionNote] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[resolvedDate] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[contactDetails] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[complianceReason] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[validationRequiredFlag] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[remark] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[raisedDate] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[regulatoryBody] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[firstSLADate] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[secondSLADate] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[caseFileNumber] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bkPrincipal] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bkInterest] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bkFees] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[totalAmount] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[courtCity] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[externalSystemId] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[consumerIdentificationNumber] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bankruptcyType] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[complianceAction] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[defendant] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[balanceAtTimeOfEvent] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[attorneyRetained] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[attorneyDate] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[attorneyType] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[attorneyOfficeFax] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dueClaimProofDate] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[filedClaimProofDate] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[eventDate] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[balanceAtTimeOfNotification] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Custom_Equabli_Compliance_Info] ADD CONSTRAINT [PK_Custom_Equabli_Compliance_Info] PRIMARY KEY CLUSTERED ([UID]) ON [PRIMARY]
GO
