CREATE TABLE [dbo].[Custom_MT_CACS_LegalData]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[AgencyID] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LocationCode] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AcctNumber] [varchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TransactionCode] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TransactionDate] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FilingFees] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StipulationBalance] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FirstStipPayDueD] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StipulationPayCnt] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DayStipulationPay] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FinalStipulationPa] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FinalStipulationAm] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StipContractSentD] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StipContractSigned] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MTHStipulationAmt] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FinanceChargePercent] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AttorneyFee] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AttorneyDataText1] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AttorneyDataText2] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AttorneyDataText3] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AttorneyDataText4] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AttorneyDataText5] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AttorneyDataText6] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AttorneyDataText7] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CourtName] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DocketNumber] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AbstractDate] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PostJudgementExpen] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[JudgementAmt] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[JudgementDate] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DismissSatisfiedCo] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DismissSatisfiedDa] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LevyAmt] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LevyType] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LevyDate] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CountyName] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LevyRequestDate] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LevyRequestAmt] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PrincipalAmt] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OthDelinqAmt] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IntOwingAtCo] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ChargeOffDate] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COAmount] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AcctOpenDate] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ModelYear] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Manufacturer] [varchar] (14) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Model] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReposessionDate] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SaleDate] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GrossProceeds] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BBRepoDate] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BBSaleDate] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BBSoldAmount] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreditScore] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OfficerNum] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CollateralCode] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateOfDeathPrimary] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateOfDeathSSCoMaker] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateOfDeathGuarantor] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TotalCOBalance] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PmtsCrdtsSinceCO] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Custom_MT_CACS_LegalData] ADD CONSTRAINT [PK_Custom_MT_CACS_LegalData] PRIMARY KEY CLUSTERED ([ID]) ON [PRIMARY]
GO
