CREATE TABLE [dbo].[HCS_FTE]
(
[CreditorID] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[FTE] [int] NOT NULL CONSTRAINT [DF__HCS_FTE__FTE__1F9A496F] DEFAULT (0),
[UID] [int] NOT NULL IDENTITY(1, 1)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[HCS_FTE] ADD CONSTRAINT [PK_HCS_FTE] PRIMARY KEY CLUSTERED ([UID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [CreditorIDInd] ON [dbo].[HCS_FTE] ([CreditorID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
