CREATE TABLE [dbo].[TestNewBizMaster]
(
[number] [int] NOT NULL,
[link] [int] NULL,
[desk] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__TestNewBiz__desk__7287ABD6] DEFAULT (0),
[Name] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Street1] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Street2] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[City] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[State] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Zipcode] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ctl] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[other] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MR] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[account] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[homephone] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[workphone] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[specialnote] [varchar] (75) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[received] [datetime] NULL,
[closed] [datetime] NULL,
[returned] [datetime] NULL,
[lastpaid] [datetime] NULL,
[lastpaidamt] [money] NULL,
[lastinterest] [datetime] NULL,
[interestrate] [money] NULL,
[worked] [datetime] NULL,
[userdate1] [datetime] NULL,
[userdate2] [datetime] NULL,
[userdate3] [datetime] NULL,
[contacted] [datetime] NULL,
[status] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[customer] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSN] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[original] [money] NOT NULL CONSTRAINT [DF__TestNewBi__origi__737BD00F] DEFAULT (0),
[original1] [money] NOT NULL CONSTRAINT [DF__TestNewBi__origi__746FF448] DEFAULT (0),
[original2] [money] NOT NULL CONSTRAINT [DF__TestNewBi__origi__75641881] DEFAULT (0),
[original3] [money] NOT NULL CONSTRAINT [DF__TestNewBi__origi__76583CBA] DEFAULT (0),
[original4] [money] NOT NULL CONSTRAINT [DF__TestNewBi__origi__774C60F3] DEFAULT (0),
[original5] [money] NOT NULL CONSTRAINT [DF__TestNewBi__origi__7840852C] DEFAULT (0),
[original6] [money] NOT NULL CONSTRAINT [DF__TestNewBi__origi__7934A965] DEFAULT (0),
[original7] [money] NOT NULL CONSTRAINT [DF__TestNewBi__origi__7A28CD9E] DEFAULT (0),
[original8] [money] NOT NULL CONSTRAINT [DF__TestNewBi__origi__7B1CF1D7] DEFAULT (0),
[original9] [money] NOT NULL CONSTRAINT [DF__TestNewBi__origi__7C111610] DEFAULT (0),
[original10] [money] NOT NULL CONSTRAINT [DF__TestNewBi__origi__7D053A49] DEFAULT (0),
[Accrued2] [money] NOT NULL CONSTRAINT [DF__TestNewBi__Accru__7DF95E82] DEFAULT (0),
[Accrued10] [money] NOT NULL CONSTRAINT [DF__TestNewBi__Accru__7EED82BB] DEFAULT (0),
[paid] [money] NOT NULL CONSTRAINT [DF__TestNewBiz__paid__7FE1A6F4] DEFAULT (0),
[paid1] [money] NOT NULL CONSTRAINT [DF__TestNewBi__paid1__00D5CB2D] DEFAULT (0),
[paid2] [money] NOT NULL CONSTRAINT [DF__TestNewBi__paid2__01C9EF66] DEFAULT (0),
[paid3] [money] NOT NULL CONSTRAINT [DF__TestNewBi__paid3__02BE139F] DEFAULT (0),
[paid4] [money] NOT NULL CONSTRAINT [DF__TestNewBi__paid4__03B237D8] DEFAULT (0),
[paid5] [money] NOT NULL CONSTRAINT [DF__TestNewBi__paid5__04A65C11] DEFAULT (0),
[paid6] [money] NOT NULL CONSTRAINT [DF__TestNewBi__paid6__059A804A] DEFAULT (0),
[paid7] [money] NOT NULL CONSTRAINT [DF__TestNewBi__paid7__068EA483] DEFAULT (0),
[paid8] [money] NOT NULL CONSTRAINT [DF__TestNewBi__paid8__0782C8BC] DEFAULT (0),
[paid9] [money] NOT NULL CONSTRAINT [DF__TestNewBi__paid9__0876ECF5] DEFAULT (0),
[paid10] [money] NOT NULL CONSTRAINT [DF__TestNewBi__paid1__096B112E] DEFAULT (0),
[current0] [money] NOT NULL CONSTRAINT [DF__TestNewBi__curre__0A5F3567] DEFAULT (0),
[current1] [money] NOT NULL CONSTRAINT [DF__TestNewBi__curre__0B5359A0] DEFAULT (0),
[current2] [money] NOT NULL CONSTRAINT [DF__TestNewBi__curre__0C477DD9] DEFAULT (0),
[current3] [money] NOT NULL CONSTRAINT [DF__TestNewBi__curre__0D3BA212] DEFAULT (0),
[current4] [money] NOT NULL CONSTRAINT [DF__TestNewBi__curre__0E2FC64B] DEFAULT (0),
[current5] [money] NOT NULL CONSTRAINT [DF__TestNewBi__curre__0F23EA84] DEFAULT (0),
[current6] [money] NOT NULL CONSTRAINT [DF__TestNewBi__curre__10180EBD] DEFAULT (0),
[current7] [money] NOT NULL CONSTRAINT [DF__TestNewBi__curre__110C32F6] DEFAULT (0),
[current8] [money] NOT NULL CONSTRAINT [DF__TestNewBi__curre__1200572F] DEFAULT (0),
[current9] [money] NOT NULL CONSTRAINT [DF__TestNewBi__curre__12F47B68] DEFAULT (0),
[current10] [money] NOT NULL CONSTRAINT [DF__TestNewBi__curre__13E89FA1] DEFAULT (0),
[attorney] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[assignedattorney] [datetime] NULL,
[promamt] [money] NULL,
[promdue] [datetime] NULL,
[sifpct] [money] NULL,
[queue] [varchar] (26) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[qflag] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[qdate] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[qlevel] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[qtime] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[extracodes] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Salary] [money] NULL,
[feecode] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[clidlc] [datetime] NULL,
[clidlp] [datetime] NULL,
[seq] [int] NULL,
[Pseq] [int] NOT NULL CONSTRAINT [DF__TestNewBiz__Pseq__14DCC3DA] DEFAULT (0),
[Branch] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__TestNewBi__Branc__15D0E813] DEFAULT (0),
[Finders] [datetime] NULL,
[COMPLETE1] [datetime] NULL,
[Complete2] [datetime] NULL,
[DESK1] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DESK2] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Full0] [datetime] NULL,
[TotalViewed] [int] NOT NULL,
[TotalWorked] [int] NOT NULL,
[TotalContacted] [int] NOT NULL,
[nsf] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HasBigNote] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FirstDesk] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FirstReceived] [datetime] NULL,
[AgencyFlag] [tinyint] NULL,
[AgencyCode] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FeeSchedule] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustDivision] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustDistrict] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustBranch] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Delinquencydate] [datetime] NULL,
[CurrencyType] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DOB] [datetime] NULL,
[sysmonth] [tinyint] NULL,
[SysYear] [smallint] NULL,
[DMDateStamp] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__TestNewBi__DMDat__16C50C4C] DEFAULT (''),
[id1] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[id2] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PurchasedPortfolio] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SoldPortfolio] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OriginalCreditor] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AttorneyID] [int] NULL,
[BPDate] [datetime] NULL,
[NSFDate] [datetime] NULL,
[ContractDate] [datetime] NULL,
[ChargeOffDate] [datetime] NULL,
[ShouldQueue] [bit] NOT NULL CONSTRAINT [DF__TestNewBi__Shoul__17B93085] DEFAULT (1),
[RestrictedAccess] [bit] NOT NULL CONSTRAINT [DF__TestNewBi__Restr__18AD54BE] DEFAULT (0),
[LinkDriver] [bit] NOT NULL CONSTRAINT [DF__TestNewBi__LinkD__19A178F7] DEFAULT (1),
[Score] [smallint] NULL,
[Salesman1ID] [int] NOT NULL CONSTRAINT [DF__TestNewBi__Sales__1A959D30] DEFAULT (0),
[Salesman2ID] [int] NOT NULL CONSTRAINT [DF__TestNewBi__Sales__1B89C169] DEFAULT (0),
[Salesman3ID] [int] NOT NULL CONSTRAINT [DF__TestNewBi__Sales__1C7DE5A2] DEFAULT (0),
[AIMAgency] [int] NULL,
[AIMAssigned] [datetime] NULL,
[cbrPrevent] [bit] NOT NULL CONSTRAINT [DF__TestNewBi__cbrPr__1D7209DB] DEFAULT (0),
[cbrException] [smallint] NOT NULL CONSTRAINT [DF__TestNewBi__cbrEx__1E662E14] DEFAULT (0),
[cbrExtendDays] [int] NULL,
[clialp] [money] NULL,
[clialc] [money] NULL
) ON [PRIMARY]
GO
