CREATE TABLE [dbo].[NbWork]
(
[ID] [int] NOT NULL,
[Batch] [int] NULL,
[Seq] [int] NULL,
[processed] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[name] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[street1] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Street2] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[City] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[State] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Zipcode] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HomePhone] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WorkPhone] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Account] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSN] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Anumber] [int] NULL,
[Enumber] [int] NULL,
[Adollars] [money] NULL,
[Edollars] [money] NULL,
[Customer] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Customername] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BALANCE] [money] NULL,
[oTHER] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DESK] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EXTRA1] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EXTRA2] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EXTRA3] [varchar] (152) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EXTRA4] [varchar] (152) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EXTRA5] [varchar] (152) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[specialnote] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[e1] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[e2] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[e3] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[e4] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[e5] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[e6] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[number] [int] NULL,
[received] [datetime] NULL,
[original] [money] NULL,
[original1] [money] NULL,
[original2] [money] NULL,
[original3] [money] NULL,
[original4] [money] NULL,
[original5] [money] NULL,
[original6] [money] NULL,
[original7] [money] NULL,
[original8] [money] NULL,
[original9] [money] NULL,
[original10] [money] NULL,
[paid] [money] NULL,
[paid1] [money] NULL,
[paid2] [money] NULL,
[paid3] [money] NULL,
[paid4] [money] NULL,
[paid5] [money] NULL,
[paid6] [money] NULL,
[paid7] [money] NULL,
[paid8] [money] NULL,
[paid9] [money] NULL,
[paid10] [money] NULL,
[current1] [money] NULL,
[current2] [money] NULL,
[current3] [money] NULL,
[current4] [money] NULL,
[current5] [money] NULL,
[current6] [money] NULL,
[current7] [money] NULL,
[current8] [money] NULL,
[current9] [money] NULL,
[current10] [money] NULL,
[mr] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[current_] [money] NULL,
[restart] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EXTRAdata1] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EXTRAdata2] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EXTRAdata3] [varchar] (152) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EXTRAdata4] [varchar] (152) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EXTRAdata5] [varchar] (152) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[userdate1] [datetime] NULL,
[userdate2] [datetime] NULL,
[userdate3] [datetime] NULL
) ON [PRIMARY]
GO
