CREATE TABLE [dbo].[ServiceBatch_PRODUCTS]
(
[Id] [int] NOT NULL IDENTITY(1, 1),
[BatchID] [uniqueidentifier] NOT NULL,
[ProductID] [uniqueidentifier] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ServiceBatch_PRODUCTS] ADD CONSTRAINT [PK_ServiceBatch_PRODUCTS] PRIMARY KEY CLUSTERED ([Id]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_ServiceBatch_PRODUCTS_ProductID] ON [dbo].[ServiceBatch_PRODUCTS] ([ProductID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ServiceBatch_PRODUCTS] ADD CONSTRAINT [FK_ServiceBatch_PRODUCTS_ServiceBatch_REQUESTS] FOREIGN KEY ([BatchID]) REFERENCES [dbo].[ServiceBatch_REQUESTS] ([BatchID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
