CREATE TABLE [dbo].[MasterPaidBcktsBackup_20070215]
(
[number] [int] NOT NULL,
[status] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[qlevel] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[received] [datetime] NULL,
[closed] [datetime] NULL,
[original] [money] NOT NULL,
[original1] [money] NOT NULL,
[original2] [money] NOT NULL,
[original3] [money] NOT NULL,
[original4] [money] NOT NULL,
[original5] [money] NOT NULL,
[original6] [money] NOT NULL,
[original7] [money] NOT NULL,
[original8] [money] NOT NULL,
[original9] [money] NOT NULL,
[original10] [money] NOT NULL,
[current0] [money] NOT NULL,
[current1] [money] NOT NULL,
[current2] [money] NOT NULL,
[current3] [money] NOT NULL,
[current4] [money] NOT NULL,
[current5] [money] NOT NULL,
[current6] [money] NOT NULL,
[current7] [money] NOT NULL,
[current8] [money] NOT NULL,
[current9] [money] NOT NULL,
[current10] [money] NOT NULL,
[paid] [money] NOT NULL,
[paid1] [money] NOT NULL,
[paid2] [money] NOT NULL,
[paid3] [money] NOT NULL,
[paid4] [money] NOT NULL,
[paid5] [money] NOT NULL,
[paid6] [money] NOT NULL,
[paid7] [money] NOT NULL,
[paid8] [money] NOT NULL,
[paid9] [money] NOT NULL,
[paid10] [money] NOT NULL,
[accrued2] [money] NOT NULL,
[accrued10] [money] NOT NULL
) ON [PRIMARY]
GO
