CREATE TABLE [dbo].[NewBizBmaster]
(
[number] [int] NOT NULL,
[link] [int] NULL,
[LinkDriver] [bit] NOT NULL CONSTRAINT [DF__NewBizBma__LinkD__589DBCA1] DEFAULT (1),
[desk] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__NewBizBmas__desk__3183EF80] DEFAULT (0),
[Name] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Street1] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Street2] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[City] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[State] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Zipcode] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ctl] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[other] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MR] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[account] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OriginalCreditor] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[homephone] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[workphone] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[specialnote] [varchar] (75) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[received] [datetime] NULL,
[closed] [datetime] NULL,
[returned] [datetime] NULL,
[lastpaid] [datetime] NULL,
[lastpaidamt] [money] NULL,
[lastinterest] [datetime] NULL,
[interestrate] [money] NULL,
[worked] [datetime] NULL,
[userdate1] [datetime] NULL,
[userdate2] [datetime] NULL,
[userdate3] [datetime] NULL,
[contacted] [datetime] NULL,
[status] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[customer] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSN] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[original] [money] NOT NULL CONSTRAINT [DF__NewBizBma__origi__327813B9] DEFAULT (0),
[original1] [money] NOT NULL CONSTRAINT [DF__NewBizBma__origi__336C37F2] DEFAULT (0),
[original2] [money] NOT NULL CONSTRAINT [DF__NewBizBma__origi__34605C2B] DEFAULT (0),
[original3] [money] NOT NULL CONSTRAINT [DF__NewBizBma__origi__35548064] DEFAULT (0),
[original4] [money] NOT NULL CONSTRAINT [DF__NewBizBma__origi__3648A49D] DEFAULT (0),
[original5] [money] NOT NULL CONSTRAINT [DF__NewBizBma__origi__373CC8D6] DEFAULT (0),
[original6] [money] NOT NULL CONSTRAINT [DF__NewBizBma__origi__3830ED0F] DEFAULT (0),
[original7] [money] NOT NULL CONSTRAINT [DF__NewBizBma__origi__39251148] DEFAULT (0),
[original8] [money] NOT NULL CONSTRAINT [DF__NewBizBma__origi__3A193581] DEFAULT (0),
[original9] [money] NOT NULL CONSTRAINT [DF__NewBizBma__origi__3B0D59BA] DEFAULT (0),
[original10] [money] NOT NULL CONSTRAINT [DF__NewBizBma__origi__3C017DF3] DEFAULT (0),
[Accrued2] [money] NOT NULL CONSTRAINT [DF__NewBizBma__Accru__3CF5A22C] DEFAULT (0),
[Accrued10] [money] NOT NULL CONSTRAINT [DF__NewBizBma__Accru__3DE9C665] DEFAULT (0),
[paid] [money] NOT NULL CONSTRAINT [DF__NewBizBmas__paid__3EDDEA9E] DEFAULT (0),
[paid1] [money] NOT NULL CONSTRAINT [DF__NewBizBma__paid1__3FD20ED7] DEFAULT (0),
[paid2] [money] NOT NULL CONSTRAINT [DF__NewBizBma__paid2__40C63310] DEFAULT (0),
[paid3] [money] NOT NULL CONSTRAINT [DF__NewBizBma__paid3__41BA5749] DEFAULT (0),
[paid4] [money] NOT NULL CONSTRAINT [DF__NewBizBma__paid4__42AE7B82] DEFAULT (0),
[paid5] [money] NOT NULL CONSTRAINT [DF__NewBizBma__paid5__43A29FBB] DEFAULT (0),
[paid6] [money] NOT NULL CONSTRAINT [DF__NewBizBma__paid6__4496C3F4] DEFAULT (0),
[paid7] [money] NOT NULL CONSTRAINT [DF__NewBizBma__paid7__458AE82D] DEFAULT (0),
[paid8] [money] NOT NULL CONSTRAINT [DF__NewBizBma__paid8__467F0C66] DEFAULT (0),
[paid9] [money] NOT NULL CONSTRAINT [DF__NewBizBma__paid9__4773309F] DEFAULT (0),
[paid10] [money] NOT NULL CONSTRAINT [DF__NewBizBma__paid1__486754D8] DEFAULT (0),
[current0] [money] NOT NULL CONSTRAINT [DF__NewBizBma__curre__495B7911] DEFAULT (0),
[current1] [money] NOT NULL CONSTRAINT [DF__NewBizBma__curre__4A4F9D4A] DEFAULT (0),
[current2] [money] NOT NULL CONSTRAINT [DF__NewBizBma__curre__4B43C183] DEFAULT (0),
[current3] [money] NOT NULL CONSTRAINT [DF__NewBizBma__curre__4C37E5BC] DEFAULT (0),
[current4] [money] NOT NULL CONSTRAINT [DF__NewBizBma__curre__4D2C09F5] DEFAULT (0),
[current5] [money] NOT NULL CONSTRAINT [DF__NewBizBma__curre__4E202E2E] DEFAULT (0),
[current6] [money] NOT NULL CONSTRAINT [DF__NewBizBma__curre__4F145267] DEFAULT (0),
[current7] [money] NOT NULL CONSTRAINT [DF__NewBizBma__curre__500876A0] DEFAULT (0),
[current8] [money] NOT NULL CONSTRAINT [DF__NewBizBma__curre__50FC9AD9] DEFAULT (0),
[current9] [money] NOT NULL CONSTRAINT [DF__NewBizBma__curre__51F0BF12] DEFAULT (0),
[current10] [money] NOT NULL CONSTRAINT [DF__NewBizBma__curre__52E4E34B] DEFAULT (0),
[attorney] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AttorneyID] [int] NULL,
[assignedattorney] [datetime] NULL,
[promamt] [money] NULL,
[promdue] [datetime] NULL,
[sifpct] [money] NULL,
[queue] [varchar] (26) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[qflag] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[qdate] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[qlevel] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[qtime] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[extracodes] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Salary] [money] NULL,
[feecode] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[clidlc] [datetime] NULL,
[clidlp] [datetime] NULL,
[seq] [int] NULL,
[Pseq] [int] NOT NULL CONSTRAINT [DF__NewBizBmas__Pseq__53D90784] DEFAULT (0),
[Branch] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__NewBizBma__Branc__54CD2BBD] DEFAULT (0),
[Finders] [datetime] NULL,
[COMPLETE1] [datetime] NULL,
[Complete2] [datetime] NULL,
[DESK1] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DESK2] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Full0] [datetime] NULL,
[TotalViewed] [int] NOT NULL,
[TotalWorked] [int] NOT NULL,
[TotalContacted] [int] NOT NULL,
[nsf] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HasBigNote] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FirstDesk] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FirstReceived] [datetime] NULL,
[AgencyFlag] [tinyint] NULL,
[AgencyCode] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FeeSchedule] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustDivision] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustDistrict] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustBranch] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Delinquencydate] [datetime] NULL,
[CurrencyType] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DOB] [datetime] NULL,
[sysmonth] [tinyint] NULL,
[SysYear] [smallint] NULL,
[DMDateStamp] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__NewBizBma__DMDat__55C14FF6] DEFAULT (''),
[id1] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[id2] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PurchasedPortfolio] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SoldPortfolio] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BPDate] [datetime] NULL,
[NSFDate] [datetime] NULL,
[ContractDate] [datetime] NULL,
[ChargeOffDate] [datetime] NULL,
[ShouldQueue] [bit] NOT NULL CONSTRAINT [DF__NewBizBma__Shoul__56B5742F] DEFAULT (1),
[RestrictedAccess] [bit] NOT NULL CONSTRAINT [DF__NewBizBma__Restr__57A99868] DEFAULT (0),
[Score] [smallint] NULL,
[Salesman1ID] [int] NOT NULL CONSTRAINT [DF__NewBizBma__Sales__5991E0DA] DEFAULT (0),
[Salesman2ID] [int] NOT NULL CONSTRAINT [DF__NewBizBma__Sales__5A860513] DEFAULT (0),
[Salesman3ID] [int] NOT NULL CONSTRAINT [DF__NewBizBma__Sales__5B7A294C] DEFAULT (0),
[AIMAgency] [int] NULL,
[AIMAssigned] [datetime] NULL,
[cbrPrevent] [bit] NOT NULL CONSTRAINT [DF__NewBizBma__cbrPr__5C6E4D85] DEFAULT (0),
[cbrException] [smallint] NOT NULL CONSTRAINT [DF__NewBizBma__cbrEx__5D6271BE] DEFAULT (0),
[cbrExtendDays] [int] NULL,
[clialp] [money] NULL,
[clialc] [money] NULL,
[cbrOverride] [bit] NOT NULL CONSTRAINT [DF__NewBizBMa__cbrOv__6CAFA246] DEFAULT (0),
[viewed] [datetime] NULL,
[QueueHold] [datetime] NULL,
[Secured] [bit] NOT NULL CONSTRAINT [DF__NewBizBMa__Secur__6DA3C67F] DEFAULT (0),
[PreviousCreditor] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StatuteDate] [datetime] NULL,
[AttorneyLawList] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AttorneyStatus] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ClassOfBusiness] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ClaimType] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AttorneyAccountID] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InterestBuckets] [smallint] NULL,
[BlanketSIFOverride] [float] NULL,
[Archived] [datetime] NULL,
[PreventLinking] [bit] NOT NULL CONSTRAINT [DF__NewBizBmaster__PreventLinking] DEFAULT ((0)),
[IsInterestDeferred] [bit] NOT NULL CONSTRAINT [DF__NewBizBmaster__IsInterestDeferred] DEFAULT ((0)),
[DeferredInterest] [money] NULL,
[SettlementID] [int] NULL
) ON [PRIMARY]
GO
