CREATE TABLE [dbo].[Custom_AFF_Outsourcer_AccountHolder_Import]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[ACCOUNTHOLDER_PLACEMENT_ACCOUNTHOLDER] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ACCOUNTHOLDER_OUTSOURCERACCOUNTID] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ACCOUNTHOLDER_ACCOUNTHOLDERREF] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ACCOUNTHOLDER_NATIONALID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ACCOUNTHOLDER_FIRSTNAME] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ACCOUNTHOLDER_MIDDLENAME] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ACCOUNTHOLDER_LASTNAME] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ACCOUNTHOLDER_SUFFIX] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ACCOUNTHOLDER_DATEOFBIRTH] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ACCOUNTHOLDER_LANGUAGESPOKEN] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ACCOUNTHOLDER_ISRESPONSIBLE] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Custom_AFF_Outsourcer_AccountHolder_Import] ADD CONSTRAINT [PK_Custom_AFF_Outsourcer_AccountHolder_Import] PRIMARY KEY CLUSTERED ([ID]) ON [PRIMARY]
GO
