CREATE TABLE [dbo].[Native_OOS_COBs]
(
[COB] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[OOSTypeId] [tinyint] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Native_OOS_COBs] ADD CONSTRAINT [PK__Native_O__C1FF6EAF1E4BC1E4] PRIMARY KEY CLUSTERED ([COB]) ON [PRIMARY]
GO
