CREATE TABLE [dbo].[Services_IdInfo_Bankruptcy]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[RequestID] [int] NULL,
[Domain] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Ssn] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BankruptcyState] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AccountKey] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FilingNumber] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FilingYear] [int] NULL,
[InternalCourtNumber] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FilingDate] [datetime] NULL,
[DebtorType] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FirstName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MiddleName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Generation] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LinkCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StreetNumber] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StreetDirection] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StreetName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StreetType] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Street2] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[City] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[State] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Zipcode] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Chapter] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DischargeDate] [datetime] NULL,
[DismissedDate] [datetime] NULL,
[ClosedDate] [datetime] NULL,
[HearingDate] [datetime] NULL,
[Assets] [money] NULL,
[DebtorKey] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CaseVoluntary] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrusteeName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrusteeAddress] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrusteeCity] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrusteeState] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrusteeZip] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrusteePhone] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HearingTime] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HearingLocation] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[JudgeName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[JudgeInitials] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IndividualJoin] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NewConversionChNumber] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ChapterConversionDate] [datetime] NULL,
[ProofOfClaimsDate] [datetime] NULL,
[ObjectionToPlanDate] [datetime] NULL,
[AttyName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AttyFirmName] [varchar] (300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AttyStreet1] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AttyStreet2] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AttyCity] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AttyState] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AttyZip] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AttyPhone] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ResolvedSsn] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Last4Ssn] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CaseNumber] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CourtVenue] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Bankrupt] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DispositionCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Services_IdInfo_Bankruptcy] ADD CONSTRAINT [PK_Services_IdInfo_Bankruptcy] PRIMARY KEY CLUSTERED ([ID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
