CREATE TABLE [dbo].[Custom_MT_Temp_LegalData]
(
[UID] [int] NOT NULL IDENTITY(1, 1),
[AgencyId] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LocationCode] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AcctNumber] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TransCode] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TransDate] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FilingFees] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StipulationBalance] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FirstStipPayDueD] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StipulationPayCnt] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DayStipulationPay] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FinalStipulationPa] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FinalStipulationAm] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StipContractSentD] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StipContractSigned] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MTHStipulationAmt] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FinanceChargePercent] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AttorneyFee] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AttorneyDataText1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AttorneyDataText2] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AttorneyDataText3] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AttorneyDataText4] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AttorneyDataText5] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AttorneyDataText6] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AttorneyDataText7] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CourtName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DocketNumber] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AbstractDate] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PostJudgementExpen] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[JudgementAmt] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[JudgementDate] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DismissSatisfiedCo] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DismissSatisfiedDa] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LevyAmt] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LevyType] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LevyDate] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CountyName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LevyRequestDate] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LevyRequestAmt] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PrincipalAmt] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OthDelinqAmt] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IntOwingAtCo] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ChargeOffDate] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COAmount] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AcctOpenDate] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ModelYear] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Manufacturer] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Model] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReposessionDate] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SaleDate] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GrossProceeds] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BBRepoDate] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BBSaleDate] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BBSoldAmount] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreditScore] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OfficerNum] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CollateralCode] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateOfDeathPrimary] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateOfDeathSSCoMaker] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateOfDeathGuarantor] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TotalCOBalance] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PmtsCrdtsSinceCO] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Custom_MT_Temp_LegalData] ADD CONSTRAINT [PK_M&T_Temp_LegalData] PRIMARY KEY CLUSTERED ([UID]) ON [PRIMARY]
GO
