CREATE TABLE [dbo].[NewBizBMasterMidland]
(
[number] [int] NOT NULL,
[link] [int] NULL,
[desk] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__NewBizBMas__desk__66518184] DEFAULT ((0)),
[Name] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Street1] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Street2] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[City] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[State] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Zipcode] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ctl] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[other] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MR] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[account] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[homephone] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[workphone] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[specialnote] [varchar] (75) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[received] [datetime] NULL,
[closed] [datetime] NULL,
[returned] [datetime] NULL,
[lastpaid] [datetime] NULL,
[lastpaidamt] [money] NULL,
[lastinterest] [datetime] NULL,
[interestrate] [money] NULL,
[worked] [datetime] NULL,
[userdate1] [datetime] NULL,
[userdate2] [datetime] NULL,
[userdate3] [datetime] NULL,
[contacted] [datetime] NULL,
[status] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[customer] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSN] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[original] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__origi__6745A5BD] DEFAULT ((0)),
[original1] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__origi__6839C9F6] DEFAULT ((0)),
[original2] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__origi__692DEE2F] DEFAULT ((0)),
[original3] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__origi__6A221268] DEFAULT ((0)),
[original4] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__origi__6B1636A1] DEFAULT ((0)),
[original5] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__origi__6C0A5ADA] DEFAULT ((0)),
[original6] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__origi__6CFE7F13] DEFAULT ((0)),
[original7] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__origi__6DF2A34C] DEFAULT ((0)),
[original8] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__origi__6EE6C785] DEFAULT ((0)),
[original9] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__origi__6FDAEBBE] DEFAULT ((0)),
[original10] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__origi__70CF0FF7] DEFAULT ((0)),
[Accrued2] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__Accru__71C33430] DEFAULT ((0)),
[Accrued10] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__Accru__72B75869] DEFAULT ((0)),
[paid] [money] NOT NULL CONSTRAINT [DF__NewBizBMas__paid__73AB7CA2] DEFAULT ((0)),
[paid1] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__paid1__749FA0DB] DEFAULT ((0)),
[paid2] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__paid2__7593C514] DEFAULT ((0)),
[paid3] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__paid3__7687E94D] DEFAULT ((0)),
[paid4] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__paid4__777C0D86] DEFAULT ((0)),
[paid5] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__paid5__787031BF] DEFAULT ((0)),
[paid6] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__paid6__796455F8] DEFAULT ((0)),
[paid7] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__paid7__7A587A31] DEFAULT ((0)),
[paid8] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__paid8__7B4C9E6A] DEFAULT ((0)),
[paid9] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__paid9__7C40C2A3] DEFAULT ((0)),
[paid10] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__paid1__7D34E6DC] DEFAULT ((0)),
[current0] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__curre__7E290B15] DEFAULT ((0)),
[current1] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__curre__7F1D2F4E] DEFAULT ((0)),
[current2] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__curre__00115387] DEFAULT ((0)),
[current3] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__curre__010577C0] DEFAULT ((0)),
[current4] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__curre__01F99BF9] DEFAULT ((0)),
[current5] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__curre__02EDC032] DEFAULT ((0)),
[current6] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__curre__03E1E46B] DEFAULT ((0)),
[current7] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__curre__04D608A4] DEFAULT ((0)),
[current8] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__curre__05CA2CDD] DEFAULT ((0)),
[current9] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__curre__06BE5116] DEFAULT ((0)),
[current10] [money] NOT NULL CONSTRAINT [DF__NewBizBMa__curre__07B2754F] DEFAULT ((0)),
[attorney] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[assignedattorney] [datetime] NULL,
[promamt] [money] NULL,
[promdue] [datetime] NULL,
[sifpct] [money] NULL,
[queue] [varchar] (26) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[qflag] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[qdate] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[qlevel] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[qtime] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[extracodes] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Salary] [money] NULL,
[feecode] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[clidlc] [datetime] NULL,
[clidlp] [datetime] NULL,
[seq] [int] NULL,
[Pseq] [int] NOT NULL CONSTRAINT [DF__NewBizBMas__Pseq__08A69988] DEFAULT ((0)),
[Branch] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__NewBizBMa__Branc__099ABDC1] DEFAULT ((0)),
[Finders] [datetime] NULL,
[COMPLETE1] [datetime] NULL,
[Complete2] [datetime] NULL,
[DESK1] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DESK2] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Full0] [datetime] NULL,
[TotalViewed] [int] NOT NULL,
[TotalWorked] [int] NOT NULL,
[TotalContacted] [int] NOT NULL,
[nsf] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HasBigNote] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FirstDesk] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FirstReceived] [datetime] NULL,
[AgencyFlag] [tinyint] NULL,
[AgencyCode] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FeeSchedule] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustDivision] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustDistrict] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustBranch] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Delinquencydate] [datetime] NULL,
[CurrencyType] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DOB] [datetime] NULL,
[sysmonth] [tinyint] NULL,
[SysYear] [smallint] NULL,
[DMDateStamp] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__NewBizBMa__DMDat__0A8EE1FA] DEFAULT (''),
[id1] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[id2] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PurchasedPortfolio] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SoldPortfolio] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OriginalCreditor] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AttorneyID] [int] NULL,
[BPDate] [datetime] NULL,
[NSFDate] [datetime] NULL,
[ContractDate] [datetime] NULL,
[ChargeOffDate] [datetime] NULL,
[ShouldQueue] [bit] NOT NULL CONSTRAINT [DF__NewBizBMa__Shoul__0B830633] DEFAULT ((1)),
[RestrictedAccess] [bit] NOT NULL CONSTRAINT [DF__NewBizBMa__Restr__0C772A6C] DEFAULT ((0)),
[LinkDriver] [bit] NOT NULL CONSTRAINT [DF__NewBizBMa__LinkD__0D6B4EA5] DEFAULT ((1)),
[Score] [smallint] NULL,
[Salesman1ID] [int] NOT NULL CONSTRAINT [DF__NewBizBMa__Sales__0E5F72DE] DEFAULT ((0)),
[Salesman2ID] [int] NOT NULL CONSTRAINT [DF__NewBizBMa__Sales__0F539717] DEFAULT ((0)),
[Salesman3ID] [int] NOT NULL CONSTRAINT [DF__NewBizBMa__Sales__1047BB50] DEFAULT ((0)),
[AIMAgency] [int] NULL,
[AIMAssigned] [datetime] NULL,
[cbrPrevent] [bit] NOT NULL CONSTRAINT [DF__NewBizBMa__cbrPr__113BDF89] DEFAULT ((0)),
[cbrException] [smallint] NOT NULL CONSTRAINT [DF__NewBizBMa__cbrEx__123003C2] DEFAULT ((0)),
[cbrExtendDays] [int] NULL,
[clialp] [money] NULL,
[clialc] [money] NULL,
[cbrOverride] [bit] NOT NULL CONSTRAINT [DF__NewBizBMa__cbrOv__132427FB] DEFAULT ((0)),
[viewed] [datetime] NULL,
[QueueHold] [datetime] NULL,
[Secured] [bit] NOT NULL CONSTRAINT [DF__NewBizBMa__Secur__14184C34] DEFAULT ((0)),
[PreviousCreditor] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StatuteDate] [datetime] NULL,
[AttorneyLawList] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AttorneyStatus] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ClassOfBusiness] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ClaimType] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AttorneyAccountID] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InterestBuckets] [smallint] NULL,
[BlanketSIFOverride] [float] NULL,
[Archived] [datetime] NULL,
[PreventLinking] [bit] NOT NULL CONSTRAINT [DF__NewBizBMa__Preve__150C706D] DEFAULT ((0)),
[IsInterestDeferred] [bit] NOT NULL CONSTRAINT [DF__NewBizBMa__IsInt__160094A6] DEFAULT ((0)),
[DeferredInterest] [money] NULL,
[SettlementID] [int] NULL
) ON [PRIMARY]
GO
