CREATE TABLE [dbo].[Custom_SunTrust_CACS_Contact_Base_Data_Maintenance]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[AgencyID] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LocationCode] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AcctNumber] [varchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TransCode] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TransDate] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ContactID] [varchar] (24) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ContactRecType] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Filler] [varchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ActionCode] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Name] [varchar] (45) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Prefix] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FirstName] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MiddleName] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastName] [varchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Suffix] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MaternalName] [varchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NationalIDNumber] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NationalIDNumberType] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateOfBirth] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PreferredContactMethod1] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PreferredContactMethod2] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PreferredContactMethod3] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RightToPrivacy] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ISOLanguageCode] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AddressDisplayFormat] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Notes] [varchar] (34) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Employer] [varchar] (45) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerSinceDate] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UserDefinedStatus1] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UserDefinedStatus2] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UserDefinedStatus3] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UserDefinedStatus4] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UserDefinedStatus5] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UserDefinedDate1] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UserDefinedDate2] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UserDefinedDate3] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UserDefinedDate4] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UserDefinedDate5] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UserDefinedText1] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UserDefinedText2] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UserDefinedText3] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UserDefinedText4] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UserDefinedText5] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SearchName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UserDefinedSearch1] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UserDefinedSearch2] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fill] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateLastVerified] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Custom_SunTrust_CACS_Contact_Base_Data_Maintenance] ADD CONSTRAINT [PK_Custom_SunTrust_CACS_Contact_Base_Data_Maintenance] PRIMARY KEY CLUSTERED ([ID]) ON [PRIMARY]
GO
