CREATE TABLE [dbo].[Services_LexisNexis_Batch_B2]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[RequestID] [int] NOT NULL,
[prop_1_parcel] [varchar] (45) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[prop_1_owner_name] [varchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[prop_1_co_owner_name] [varchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[prop_1_property_address] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[prop_1_property_city] [varchar] (28) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[prop_1_property_state] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[prop_1_property_zip] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[prop_1_sale_date] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[prop_1_sale_price] [varchar] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[prop_1_total_value] [varchar] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[prop_1_type_financing] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[prop_1_loan_term_months] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[prop_1_foreclosure] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[prop_1_refi_flag] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[prop_1_equity_flag] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[prop_1_assessment_match_land_use_code] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[prop_1_use_code] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[prop_1_type] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[prop_2_parcel] [varchar] (45) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[prop_2_owner_name] [varchar] (62) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[prop_2_co_owner_name] [varchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[prop_2_property_address] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[prop_2_property_city] [varchar] (28) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[prop_2_property_state] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[prop_2_property_zip] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[prop_2_sale_date] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[prop_2_sale_price] [varchar] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[prop_2_total_value] [varchar] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[prop_2_type_financing] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[prop_2_loan_term_months] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[prop_2_foreclosure] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[prop_2_refi_flag] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[prop_2_equity_flag] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[prop_2_assessment_match_land_use_code] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[prop_2_use_code] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[prop_2_type] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Services_LexisNexis_Batch_B2] ADD CONSTRAINT [PK_ServicesLexNexBatch_B2] PRIMARY KEY CLUSTERED ([ID]) ON [PRIMARY]
GO
