CREATE TABLE [dbo].[ztemppresidioPCC]
(
[Number] [int] NOT NULL,
[Name] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Street1] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Street2] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[City] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[State] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Zipcode] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CardNumber] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EXPMonth] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EXPYear] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreditCard] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Amount] [money] NULL,
[Printed] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ApprovedBy] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Approved] [datetime] NULL,
[Code] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ID] [int] NOT NULL,
[CollectorFee] [money] NULL,
[DebtorID] [int] NULL,
[DateEntered] [smalldatetime] NOT NULL,
[DepositDate] [smalldatetime] NOT NULL,
[NITDSentDate] [datetime] NULL,
[OnHoldDate] [smalldatetime] NULL,
[LetterCode] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NITDSendDate] [smalldatetime] NULL,
[ProjectedFee] [money] NULL,
[UseProjectedFee] [bit] NOT NULL,
[Surcharge] [money] NOT NULL,
[IsActive] [bit] NOT NULL,
[PromiseMode] [tinyint] NULL,
[AuthDate] [smalldatetime] NULL,
[AuthCode] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AuthErrCode] [int] NULL,
[AuthErrDesc] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AuthAVS] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AuthCVV2] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AuthSource] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BatchNumber] [int] NULL,
[DateCreated] [datetime] NULL,
[DateUpdated] [datetime] NULL,
[CreatedBy] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PrintedDate] [datetime] NULL,
[NSFCount] [int] NULL,
[ProcessStatus] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
