CREATE TABLE [dbo].[Custom_AFF_Outsourcer_Extended_Import]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[EXTENDED_PLACEMENT_ACCOUNTHOLDER_EXTENDED] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EXTENDED_OUTSOURCERACCOUNTID] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EXTENDED_ACCOUNTREF] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EXTENDED_EXTENDEDPROPERTY] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EXTENDED_EXTENDEDPROPERTY_VALUE] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Custom_AFF_Outsourcer_Extended_Import] ADD CONSTRAINT [PK_Custom_AFF_Ourtsourcer_Extended_Import] PRIMARY KEY CLUSTERED ([ID]) ON [PRIMARY]
GO
