CREATE TABLE [dbo].[Custom_Fortress_Debtor_Info]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[LastName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FirstName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSN] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address2] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[City] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[state] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[zip] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[homephone] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[workphone] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[validaddress] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[filler] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ref1acctnum] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ref1lastname] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ref1firstname] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ref1address1] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ref1address2] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ref1city] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ref1state] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ref1zip] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ref1homephone] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ref1workphone] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ref2acctnum] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ref2lastname] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ref2firstname] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ref2address1] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ref2address2] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ref2city] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ref2state] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ref2zip] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ref2homephone] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ref2workphone] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ref3acctnum] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ref3lastname] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ref3firstname] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ref3address1] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ref3address2] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ref3city] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ref3state] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ref3zip] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ref3homephone] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ref3workphone] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[birthdate] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cellphone] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[filler2] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Custom_Fortress_Debtor_Info] ADD CONSTRAINT [PK_Custom_Fortress_Debtor_Info] PRIMARY KEY CLUSTERED ([ID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
