CREATE TABLE [dbo].[ShermanPaymentBatchItems]
(
[UID] [int] NOT NULL IDENTITY(1, 1),
[BatchNumber] [int] NOT NULL,
[FileNum] [int] NULL,
[DatePaid] [datetime] NULL,
[Entered] [datetime] NULL,
[PmtType] [tinyint] NULL,
[Paid0] [money] NULL,
[Paid1] [money] NULL,
[Paid2] [money] NULL,
[Paid3] [money] NULL,
[Paid4] [money] NULL,
[Paid5] [money] NULL,
[Paid6] [money] NULL,
[Paid7] [money] NULL,
[Paid8] [money] NULL,
[Paid9] [money] NULL,
[Paid10] [money] NULL,
[Fee0] [money] NULL,
[Fee1] [money] NULL,
[Fee2] [money] NULL,
[Fee3] [money] NULL,
[Fee4] [money] NULL,
[Fee5] [money] NULL,
[Fee6] [money] NULL,
[Fee7] [money] NULL,
[Fee8] [money] NULL,
[Fee9] [money] NULL,
[Fee10] [money] NULL,
[InvoiceFlags] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comment] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FeeSched] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateRan] [datetime] NULL
) ON [PRIMARY]
GO
