CREATE TABLE [dbo].[Services_LexisNexis_SkipTrace_Nixie]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[RequestId] [int] NOT NULL,
[RecordId] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Agency] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Batch] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DocumentId] [int] NULL,
[Reserved1] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ClientId] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reserved2] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[A] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[B] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[C] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[D] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[E] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[G] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[H] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[I] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[J] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[K] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[L] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[M] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[N] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[O] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[P] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[R] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[S] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[T] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[U] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[V] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[W] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[X] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reserved3] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NCOADeliverableCode] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reserved4] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Branch] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reserved5] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Services_LexisNexis_SkipTrace_Nixie] ADD CONSTRAINT [PK_Services_LexisNexis_SkipTrace_Nixie] PRIMARY KEY CLUSTERED ([ID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
