CREATE TABLE [dbo].[Services_IdInfo_CreditHolder]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[RequestID] [int] NULL,
[LastName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FirstName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MiddleName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SecondLastName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SpouseFirstName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Ssn] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gender] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MostRecentAddress] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MostRecentAddressDate] [datetime] NULL,
[MostRecentAddressNoPO] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MostRecentCityNoPO] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MostRecentCity] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MostRecentState] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MostRecentStateNoPO] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MostRecentZip] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MostRecentZipNoPO] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[2MostRecentAddressDate] [datetime] NULL,
[2MostRecentAddress] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[2MostRecentCity] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[2MostRecentState] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[2MostRecentZipcode] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[3MostRecentAddressDate] [datetime] NULL,
[3MostRecentAddress] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[3MostRecentCity] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[3MostRecentState] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[3MostRecentZipcode] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1CreateDate] [datetime] NULL,
[Address1StreetNumber] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1PreDirection] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1StreetName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1StreetSuffix] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1PostDirection] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1UnitType] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1UnitId] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1City] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1State] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1Zip] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1Zip4] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ConsumersInHousehold] [int] NULL,
[DeceasedFlag] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PreviousAddressCount] [int] NULL,
[Address2CreateDate] [datetime] NULL,
[Address2StreetNumber] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address2PreDirection] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address2StreetName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address2StreetSuffix] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address2PostDirection] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address2UnitType] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address2UnitID] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address2City] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address2State] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address2Zip] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address2Zip4] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address3CreateDate] [datetime] NULL,
[Address3StreetNumber] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address3PreDirection] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address3StreetName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address3StreetSuffix] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address3PostDirection] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address3UnitType] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address3UnitID] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address3City] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address3State] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address3Zip] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address3Zip4] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateOfBirth] [datetime] NULL,
[Telephone] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Services_IdInfo_CreditHolder] ADD CONSTRAINT [PK_Services_IdInfo_CreditHolder] PRIMARY KEY CLUSTERED ([ID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
