CREATE TABLE [dbo].[Services1]
(
[Number] [int] NULL,
[uid] [int] NOT NULL IDENTITY(1, 1),
[Serviceid] [int] NULL,
[ServiceDate] [datetime] NULL,
[ServiceMsg] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Screen] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CaseNumber] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Chapter] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FileDate] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StatusDate] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DispositionCode] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Suffix] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Zipcode] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSN] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CityFiled] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StateFiled] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[County] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FirstName] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Middlename] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Lastname] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Business] [varchar] (45) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Business1] [varchar] (45) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Business2] [varchar] (45) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Business3] [varchar] (45) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DebtorsCity] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DebtorsState] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Ecoa] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lawFirm] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AttorneyName] [varchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AttorneyAddress] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Attorneycity] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Attorneystate] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Attorneyzipcode] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AttorneyPhone] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[The341Date] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[The341Time] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[The341Location] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Trustee] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrusteeAddress] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrusteeCity] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrusteeZipcode] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrusteePhone] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[JudgesInt] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Funds] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BarDate] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[matchCode] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ClientCode] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CourtDistrict] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CourtAddress1] [varchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CourtAddress2] [varchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CourtCity] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CourtZip] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CourtPhone] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DebtorPhone] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VID] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProofofClaimdate] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DecdFirstName] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DecdLastName] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DecdState] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DecdZipcode] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DecdDOB] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DecdDOD] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Decdcode] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DebtorID] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Services1] ADD CONSTRAINT [PK_Services1] PRIMARY KEY NONCLUSTERED ([uid]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_Services1_DebtorID] ON [dbo].[Services1] ([DebtorID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE CLUSTERED INDEX [IX_Services1_Number] ON [dbo].[Services1] ([Number]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
